//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface APMAnalytics : NSObject
{
}

+ (id)addLogEventListener:(CDUnknownBlockType)arg1;
+ (id)appInstanceID;
+ (id)appInstanceIDAfterReset;
+ (void)clearConsent;
+ (id)consentSettings1P;
+ (id)consentSettings1PStart;
+ (id)consentSettings3P;
+ (void)createAppDelegateProxy;
+ (id)deferredAnalyticsCollection;
+ (id)deferredResetOnDeniedConsent;
+ (void)dispatchAsyncOnSerialQueue:(CDUnknownBlockType)arg1;
+ (void)handleEventsForBackgroundURLSession:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)handleOpenURL:(id)arg1;
+ (void)handleSetEnabled:(id)arg1;
+ (void)handleUserActivity:(id)arg1;
+ (void)initialize;
+ (_Bool)isCurrentQueueSerialQueue;
+ (void)load;
+ (void)loadPersistedConsentSettings;
+ (double)loadTimestamp;
+ (void)logEventOnSerialQueueWithOrigin:(id)arg1 isPublicEvent:(_Bool)arg2 name:(id)arg3 parameters:(id)arg4 timestamp:(double)arg5 ignoreEnabled:(_Bool)arg6 ignoreInterceptor:(_Bool)arg7 addedScreenParameters:(id)arg8;
+ (void)logEventWithName:(id)arg1 parameters:(id)arg2;
+ (void)logEventWithOrigin:(id)arg1 isPublicEvent:(_Bool)arg2 name:(id)arg3 parameters:(id)arg4;
+ (void)logEventWithOrigin:(id)arg1 isPublicEvent:(_Bool)arg2 name:(id)arg3 parameters:(id)arg4 timestamp:(double)arg5 ignoreEnabled:(_Bool)arg6 ignoreInterceptor:(_Bool)arg7;
+ (void)logEventWithOrigin:(id)arg1 name:(id)arg2 parameters:(id)arg3;
+ (void)logInternalEventWithOrigin:(id)arg1 name:(id)arg2 parameters:(id)arg3;
+ (void)logInternalEventWithOrigin:(id)arg1 name:(id)arg2 timestamp:(double)arg3 parameters:(id)arg4;
+ (void)maybeEnableTagManager;
+ (_Bool)needFirstOpenAfterReset;
+ (void)notifyEventListeners:(id)arg1;
+ (void)notifyEventListenersOnSerialQueue:(id)arg1;
+ (void)observeNotificationsForAnalyticsConfiguration:(id)arg1;
+ (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
+ (void)persistConsentSettings:(id)arg1 source:(long long)arg2;
+ (long long)persistedConsentSource;
+ (id)queue;
+ (void)queueOperationWithBlock:(CDUnknownBlockType)arg1;
+ (void)removeDeferredResetOnDeniedConsent;
+ (void)removeInternalUserAttributeForName:(id)arg1;
+ (void)removeLogEventListener:(id)arg1;
+ (void)removeNeedFirstOpenAfterReset;
+ (void)removeStartUpConsentSettings;
+ (void)removeUserAttributeForName:(id)arg1;
+ (void)resetAnalyticsData;
+ (long long)resetRetryCount;
+ (void)setAnalyticsEnabled:(_Bool)arg1;
+ (void)setAnalyticsEnabled:(_Bool)arg1 persistSetting:(_Bool)arg2;
+ (void)setAppInstanceIDAfterReset:(id)arg1;
+ (void)setConsent:(id)arg1;
+ (void)setConsent:(id)arg1 forKey:(id)arg2;
+ (void)setDefaultEventParameters:(id)arg1;
+ (void)setDeferredAnalyticsCollection:(id)arg1;
+ (void)setLoadTimestamp:(double)arg1;
+ (void)setLogEventInterceptor:(CDUnknownBlockType)arg1;
+ (void)setNeedFirstOpenAfterReset:(_Bool)arg1;
+ (void)setOpenURLListener:(CDUnknownBlockType)arg1;
+ (void)setResetRetryCount:(long long)arg1;
+ (void)setScreenName:(id)arg1 screenClass:(id)arg2;
+ (void)setSessionTimeoutInterval:(double)arg1;
+ (void)setUserAttributeNumber:(id)arg1 forName:(id)arg2;
+ (void)setUserID:(id)arg1;
+ (void)setUserPropertyString:(id)arg1 forName:(id)arg2;
+ (id)sharedInstance;
+ (void)startWithAppID:(id)arg1 origin:(id)arg2 options:(id)arg3;
+ (void)unsuspendOperationQueue;
+ (void)userPropertiesIncludingInternal:(_Bool)arg1 queue:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (void)logInternalEventWithOrigin:(id)arg1 name:(id)arg2 parameters:(id)arg3;
- (void)maxUserPropertiesForOrigin:(id)arg1 queue:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)setInternalUserProperty:(id)arg1 forName:(id)arg2 withOrigin:(id)arg3;

@end

