//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface APMConsentSettingsUtil : NSObject
{
}

+ (id)consentSettings;
+ (id)consentSettingsFromDictionary:(id)arg1;
+ (id)consentSettingsFromPlist;
+ (id)consentSignals;
+ (long long)consentSource;
+ (id)description;
+ (_Bool)didWithdrawPreviousConsent:(id)arg1;
+ (_Bool)isAdStorageDenied;
+ (_Bool)isAnalyticsStorageDenied;
+ (_Bool)isConsentSourceHigherPriority:(long long)arg1;
+ (id)serialQueue;
+ (void)setConsentSettings:(id)arg1;
+ (void)setConsentSource:(long long)arg1;
+ (void)updateSettings:(id)arg1;

@end

