//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APMPFunctionValue.h"

@protocol APMPLoggerDelegate;

@interface APMPFunctionLog : APMPFunctionValue
{
    _Bool _silent;
    _Bool _monitored;
    id <APMPLoggerDelegate> _logger;
}

- (void).cxx_destruct;
- (id)initWithLogger:(id)arg1 silent:(_Bool)arg2 monitored:(_Bool)arg3;
- (id)invokeWithArguments:(id)arg1 scope:(id)arg2 error:(id *)arg3;

@end

