//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APMPFunctionValue.h"

@class APMPEventContext;

@interface APMPEventLogger : APMPFunctionValue
{
    APMPEventContext *_eventContext;
}

- (void).cxx_destruct;
- (id)initWithEventContext:(id)arg1;
- (id)invokeWithArguments:(id)arg1 scope:(id)arg2 error:(id *)arg3;

@end

