//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APMPEvent, NSArray, NSMutableArray;

@interface APMPEventContext : NSObject
{
    NSMutableArray *_loggedEvents;
    APMPEvent *_inputEvent;
    APMPEvent *_outputEvent;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *eventsToLog;
- (id)init;
- (id)initWithEvent:(id)arg1;
@property(retain, nonatomic) APMPEvent *inputEvent; // @synthesize inputEvent=_inputEvent;
- (void)logEventWithName:(id)arg1 timestamp:(double)arg2 parameters:(id)arg3;
@property(retain, nonatomic) APMPEvent *outputEvent; // @synthesize outputEvent=_outputEvent;

@end

