//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APMPPropertyMap;

@interface APMPScope : NSObject
{
    APMPScope *_parentScope;
    APMPPropertyMap *_contents;
}

- (void).cxx_destruct;
- (void)addImmutableValue:(id)arg1 forName:(id)arg2;
- (void)addValue:(id)arg1 forName:(id)arg2;
- (id)createChildScope;
- (_Bool)hasName:(id)arg1;
- (id)initWithParentScope:(id)arg1;
- (void)makeImmutable;
- (void)setValue:(id)arg1 forName:(id)arg2;
- (id)valueForName:(id)arg1;

@end

