//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BarrageSpriteQueue, NSArray, NSMutableArray;
@protocol BarrageDispatcherDelegate;

@interface BarrageDispatcher : NSObject
{
    NSMutableArray *_activeSprites;
    BarrageSpriteQueue *_waitingSpriteQueue;
    NSMutableArray *_deadSprites;
    double _previousTime;
    double _smoothness;
    _Bool _cacheDeadSprites;
    id <BarrageDispatcherDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)activeSprite:(id)arg1;
@property(readonly, nonatomic) NSArray *activeSprites; // @synthesize activeSprites=_activeSprites;
- (void)addSprite:(id)arg1;
@property(nonatomic) _Bool cacheDeadSprites; // @synthesize cacheDeadSprites=_cacheDeadSprites;
- (double)currentTime;
- (void)deactiveAllSprites;
- (void)deactiveSprite:(id)arg1;
@property(nonatomic) __weak id <BarrageDispatcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dispatchSprites;
- (id)init;
@property(nonatomic) double smoothness; // @synthesize smoothness=_smoothness;
- (_Bool)shouldActiveSprite:(id)arg1;

@end

