//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BU_Node.h"

@class BU_Element, NSString;

@interface BU_Attr : BU_Node
{
    _Bool specified;
    NSString *name;
    NSString *value;
    BU_Element *ownerElement;
}

- (void).cxx_destruct;
- (id)initWithName:(id)arg1 value:(id)arg2;
- (id)initWithNamespace:(id)arg1 qualifiedName:(id)arg2 value:(id)arg3;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) BU_Element *ownerElement; // @synthesize ownerElement;
@property(nonatomic) _Bool specified; // @synthesize specified;
@property(retain, nonatomic) NSString *value; // @synthesize value;

@end

