//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BU_CSSValue.h"

@class NSArray;

@interface BU_CSSValueList : BU_CSSValue
{
    NSArray *internalArray;
}

- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) NSArray *internalArray; // @synthesize internalArray;
- (id)item:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long length;
- (void)setCssText:(id)arg1;

@end

