//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BU_CSSRule, NSMutableDictionary, NSString;

@interface BU_CSSStyleDeclaration : NSObject
{
    NSMutableDictionary *internalDictionaryOfStylesByCSSClass;
    NSString *_cssText;
    unsigned long long length;
    BU_CSSRule *parentRule;
}

- (void).cxx_destruct;
- (id)NSDictionaryFromCSSAttributes:(id)arg1;
@property(retain, nonatomic) NSString *cssText; // @synthesize cssText=_cssText;
- (id)description;
- (id)getPropertyCSSValue:(id)arg1;
- (id)getPropertyPriority:(id)arg1;
- (id)getPropertyValue:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSMutableDictionary *internalDictionaryOfStylesByCSSClass; // @synthesize internalDictionaryOfStylesByCSSClass;
- (id)item:(long long)arg1;
@property(nonatomic) unsigned long long length; // @synthesize length;
@property(retain, nonatomic) BU_CSSRule *parentRule; // @synthesize parentRule;
- (id)removeProperty:(id)arg1;
- (void)setProperty:(id)arg1 value:(id)arg2 priority:(id)arg3;

@end

