//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BU_Node.h"

@class BU_AppleSucksDOMImplementation, BU_DocumentType, BU_Element;

@interface BU_Document : BU_Node
{
    BU_DocumentType *doctype;
    BU_AppleSucksDOMImplementation *implementation;
    BU_Element *documentElement;
}

- (void).cxx_destruct;
- (id)createAttribute:(id)arg1;
- (id)createAttributeNS:(id)arg1 qualifiedName:(id)arg2;
- (id)createCDATASection:(id)arg1;
- (id)createComment:(id)arg1;
- (id)createDocumentFragment;
- (id)createElement:(id)arg1;
- (id)createElementNS:(id)arg1 qualifiedName:(id)arg2;
- (id)createEntityReference:(id)arg1;
- (id)createProcessingInstruction:(id)arg1 data:(id)arg2;
- (id)createTextNode:(id)arg1;
@property(readonly, nonatomic) BU_DocumentType *doctype; // @synthesize doctype;
@property(retain, nonatomic) BU_Element *documentElement; // @synthesize documentElement;
- (id)getElementById:(id)arg1;
- (id)getElementsByTagName:(id)arg1;
- (id)getElementsByTagNameNS:(id)arg1 localName:(id)arg2;
@property(readonly, nonatomic) BU_AppleSucksDOMImplementation *implementation; // @synthesize implementation;
- (id)importNode:(id)arg1 deep:(_Bool)arg2;

@end

