//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;
@protocol BU_IESGurdApplyPackageManagerDelegate;

@interface BU_IESGurdApplyPackageManager : NSObject
{
    id <BU_IESGurdApplyPackageManagerDelegate> _delegate;
    CDUnknownBlockType _zipBlock;
    NSMutableDictionary *_applyCompletionDictionary;
    NSMutableArray *_unzippingTempDirectorys;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)applyAllInactiveCacheWithCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableDictionary *applyCompletionDictionary; // @synthesize applyCompletionDictionary=_applyCompletionDictionary;
- (void)applyInactiveCacheForAccessKey:(id)arg1 channel:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)cleanTempFiles;
- (void)copyInactiveCacheWithMeta:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(nonatomic) __weak id <BU_IESGurdApplyPackageManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)gurdDidApplyPackageWithInactiveMeta:(id)arg1;
- (void)handleApplyResult:(_Bool)arg1 error:(id)arg2 inactiveMeta:(id)arg3 startDate:(id)arg4;
- (void)innerUnzipWebCacheWithMeta:(id)arg1 zipFilePath:(id)arg2 tempDirectory:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)saveInactivePackageMetaDataWithAccessKey:(id)arg1 config:(id)arg2 isPatch:(_Bool)arg3;
@property(retain, nonatomic) NSMutableArray *unzippingTempDirectorys; // @synthesize unzippingTempDirectorys=_unzippingTempDirectorys;
@property(copy, nonatomic) CDUnknownBlockType zipBlock; // @synthesize zipBlock=_zipBlock;
- (void)traceEventWithInactiveMeta:(id)arg1 message:(id)arg2 hasError:(_Bool)arg3;
- (void)unzipInactiveCacheWithMeta:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)unzipWebCacheWithMeta:(id)arg1 zipFilePath:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateResourcesWithMetaData:(id)arg1 tempDirectory:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

