//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSError;

@interface BU_IESGurdNetworkResponse : NSObject
{
    long long _statusCode;
    id _responseObject;
    NSError *_error;
    NSDictionary *_allHeaderFields;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *allHeaderFields; // @synthesize allHeaderFields=_allHeaderFields;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) id responseObject; // @synthesize responseObject=_responseObject;
@property(nonatomic) long long statusCode; // @synthesize statusCode=_statusCode;

@end

