//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BU_IESGurdDownloadPackageInfo, BU_IESGurdUnzipPackageInfo, NSDictionary, NSError, NSString;

@protocol BU_IESGurdEventDelegate <NSObject>

@optional
- (void)gurdDidCleanCachePackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2;
- (void)gurdDidFinishApplyingPackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2 succeed:(_Bool)arg3 error:(NSError *)arg4;
- (void)gurdDidFinishDownloadingPackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2 packageInfo:(BU_IESGurdDownloadPackageInfo *)arg3;
- (void)gurdDidFinishUnzippingPackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2 packageInfo:(BU_IESGurdUnzipPackageInfo *)arg3;
- (void)gurdDidRequestConfigForAccessKey:(NSString *)arg1 configsDictionary:(NSDictionary *)arg2;
- (void)gurdWillDownloadPackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2 isPatch:(_Bool)arg3;
@end

