//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BU_IESGurdFilePaths : NSObject
{
}

+ (id)activeMetaDataPath;
+ (id)backupDirectoryPath;
+ (id)backupPathForMd5:(id)arg1;
+ (id)briefFilePathWithFullPath:(id)arg1;
+ (id)cacheRootDirectoryPath;
+ (id)directoryPathForAccessKey:(id)arg1;
+ (id)directoryPathForAccessKey:(id)arg1 channel:(id)arg2;
+ (id)directoryPathForAccessKey:(id)arg1 channel:(id)arg2 path:(id)arg3;
+ (unsigned long long)fileSizeAtPath:(id)arg1;
+ (id)fileSizeStringAtPath:(id)arg1;
+ (id)inactiveDirectoryPath;
+ (id)inactiveMetaDataPath;
+ (id)inactivePathForAccessKey:(id)arg1 channel:(id)arg2;
+ (id)inactiveZipPathForAccessKey:(id)arg1 channel:(id)arg2 version:(long long)arg3 md5:(id)arg4;
+ (void)initialize;
+ (void)setCacheRootDirectoryPath:(id)arg1;

@end

