//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BU_IESGurdFileMetaManager : NSObject
{
}

+ (id)activeChannelsDictionary;
+ (id)activeMetaDictionary;
+ (id)activeMetaForAccessKey:(id)arg1 channel:(id)arg2;
+ (_Bool)checkIfVersionUpdate;
+ (void)cleanCacheMetaData;
+ (id)copiedDictionaryWithMetaDictionary:(id)arg1;
+ (id)currentVersionKey;
+ (void)deleteActiveMetaForAccessKey:(id)arg1 channel:(id)arg2;
+ (void)deleteInactiveMetaForAccessKey:(id)arg1 channel:(id)arg2;
+ (id)inactiveChannelsDictionary;
+ (id)inactiveMetaDictionary;
+ (id)inactiveMetaForAccessKey:(id)arg1 channel:(id)arg2;
+ (void)innerSaveMetaWithMetaDictionary:(id)arg1 accessKey:(id)arg2 channel:(id)arg3 meta:(id)arg4;
+ (void)innerSynchronizeMetaDataWithDictionary:(id)arg1 path:(id)arg2;
+ (id)localMetaDataWithPath:(id)arg1;
+ (_Bool)needSynchronizeActiveMeta;
+ (_Bool)needSynchronizeInactiveMeta;
+ (void)saveActiveMeta:(id)arg1;
+ (void)saveInactiveMeta:(id)arg1;
+ (void)setActiveMetaDictionary:(id)arg1;
+ (void)setInactiveMetaDictionary:(id)arg1;
+ (void)setNeedSynchronizeActiveMeta:(_Bool)arg1;
+ (void)setNeedSynchronizeInactiveMeta:(_Bool)arg1;
+ (void)setupMetaDataIfNeeded;
+ (void)setupMetaDataNotification;
+ (void)synchronizeMetaData;

@end

