//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BU_IESGurdApplyPackageManager, NSString;

@protocol BU_IESGurdApplyPackageManagerDelegate <NSObject>
- (void)applyPackageManager:(BU_IESGurdApplyPackageManager *)arg1 didApplyPackageForAccessKey:(NSString *)arg2 channel:(NSString *)arg3;
@end

