//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSMutableDictionary;
@protocol BU_IESGurdCacheCleanerManagerDelegate;

@interface BU_IESGurdCacheCleanerManager : NSObject
{
    id <BU_IESGurdCacheCleanerManagerDelegate> _delegate;
    NSMutableDictionary *_cleanerDictionary;
    NSLock *_cleanerLock;
    NSMutableDictionary *_channelsWhitelist;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)addChannelsWhitelist:(id)arg1 forAccessKey:(id)arg2;
- (id)channelWhitelistForAccessKey:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *channelsWhitelist; // @synthesize channelsWhitelist=_channelsWhitelist;
- (void)cleanCacheIfNeeded;
- (Class)cleanerClassWithPolicy:(long long)arg1;
@property(retain, nonatomic) NSMutableDictionary *cleanerDictionary; // @synthesize cleanerDictionary=_cleanerDictionary;
- (id)cleanerForAccessKey:(id)arg1;
@property(retain, nonatomic) NSLock *cleanerLock; // @synthesize cleanerLock=_cleanerLock;
- (id)cleaners;
@property(nonatomic) __weak id <BU_IESGurdCacheCleanerManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)isChannelInWhitelist:(id)arg1 accessKey:(id)arg2;
- (void)registerCacheCleanerForAccessKey:(id)arg1 configuration:(id)arg2;
- (void)setupNotification;

@end

