//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BU_SVGMatrix;

@interface BU_SVGTransform : NSObject
{
    int type;
    float angle;
    BU_SVGMatrix *matrix;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) float angle; // @synthesize angle;
@property(retain, nonatomic) BU_SVGMatrix *matrix; // @synthesize matrix;
- (void)setRotate:(float)arg1 cx:(float)arg2 cy:(float)arg3;
- (void)setScale:(float)arg1 sy:(float)arg2;
- (void)setSkewX:(float)arg1;
- (void)setSkewY:(float)arg1;
- (void)setTranslate:(float)arg1 ty:(float)arg2;
@property(nonatomic) int type; // @synthesize type;

@end

