//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BU_SVGDocument, BU_SVGSVGElement, NSMutableArray, NSMutableDictionary;

@interface BU_SVGKParseResult : NSObject
{
    _Bool libXMLFailed;
    BU_SVGDocument *parsedDocument;
    BU_SVGSVGElement *rootOfSVGTree;
    NSMutableDictionary *namespacesEncountered;
    NSMutableArray *warnings;
    NSMutableArray *errorsRecoverable;
    NSMutableArray *errorsFatal;
    double _parseProgressFractionApproximate;
}

- (void).cxx_destruct;
- (void)addParseErrorFatal:(id)arg1;
- (void)addParseErrorRecoverable:(id)arg1;
- (void)addParseWarning:(id)arg1;
- (void)addSAXError:(id)arg1;
- (void)addSourceError:(id)arg1;
- (id)description;
@property(retain, nonatomic) NSMutableArray *errorsFatal; // @synthesize errorsFatal;
@property(retain, nonatomic) NSMutableArray *errorsRecoverable; // @synthesize errorsRecoverable;
- (id)init;
@property(nonatomic) _Bool libXMLFailed; // @synthesize libXMLFailed;
@property(retain, nonatomic) NSMutableDictionary *namespacesEncountered; // @synthesize namespacesEncountered;
@property(nonatomic) double parseProgressFractionApproximate; // @synthesize parseProgressFractionApproximate=_parseProgressFractionApproximate;
@property(retain, nonatomic) BU_SVGDocument *parsedDocument; // @synthesize parsedDocument;
@property(retain, nonatomic) BU_SVGSVGElement *rootOfSVGTree; // @synthesize rootOfSVGTree;
@property(retain, nonatomic) NSMutableArray *warnings; // @synthesize warnings;

@end

