//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BU_SVGKImageView.h"

@class CAShapeLayer;

@interface BU_SVGKLayeredImageView : BU_SVGKImageView
{
    CAShapeLayer *_internalBorderLayer;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (id)image;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithSVGKImage:(id)arg1;
@property(retain, nonatomic) CAShapeLayer *internalBorderLayer; // @synthesize internalBorderLayer=_internalBorderLayer;
- (void)populateFromImage:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setShowBorder:(_Bool)arg1;
- (_Bool)showBorder;
- (double)timeIntervalForLastReRenderOfSVGFromMemory;

@end

