//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CAGradientLayer.h>

@class BU_SVGGradientElement;

@interface BU_SVGGradientLayer : CAGradientLayer
{
    BU_SVGGradientElement *_gradientElement;
    CDStruct_0f55ad9b _viewportRect;
    struct CGRect _objectRect;
    struct CGAffineTransform _absoluteTransform;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGAffineTransform absoluteTransform; // @synthesize absoluteTransform=_absoluteTransform;
- (struct CGGradient *)createCGGradient;
@property(retain, nonatomic) BU_SVGGradientElement *gradientElement; // @synthesize gradientElement=_gradientElement;
@property(nonatomic) struct CGRect objectRect; // @synthesize objectRect=_objectRect;
- (void)renderInContext:(struct CGContext *)arg1;
- (void)renderLinearGradientInContext:(struct CGContext *)arg1;
- (void)renderRadialGradientInContext:(struct CGContext *)arg1;
@property(nonatomic) CDStruct_0f55ad9b viewportRect; // @synthesize viewportRect=_viewportRect;

@end

