//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BU_SVGDocument, BU_SVGKParseResult, BU_SVGKSource, BU_SVGSVGElement, CALayer, NSString, UIImage;

@interface BU_SVGKImage : NSObject
{
    _Bool cameFromGlobalCache;
    BU_SVGDocument *DOMDocument;
    BU_SVGSVGElement *DOMTree;
    CALayer *CALayerTree;
    double _scale;
    BU_SVGKSource *source;
    BU_SVGKParseResult *parseErrorsAndWarnings;
    NSString *_nameUsedToInstantiate;
    struct CGSize _internalSizeThatWasSetExplicitlyByUser;
}

+ (id)animatedImageNamed:(id)arg1 duration:(double)arg2;
+ (id)animatedImageWithImages:(id)arg1 duration:(double)arg2;
+ (id)animatedResizableImageNamed:(id)arg1 capInsets:(struct UIEdgeInsets)arg2 duration:(double)arg3;
+ (void)clearCache;
+ (void)didReceiveMemoryWarningOrBackgroundNotification:(id)arg1;
+ (id)imageAsynchronouslyNamed:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
+ (id)imageNamed:(id)arg1;
+ (id)imageNamed:(id)arg1 inBundle:(id)arg2;
+ (id)imageNamed:(id)arg1 inBundle:(id)arg2 withCacheKey:(id)arg3;
+ (id)imageNamed:(id)arg1 withCacheKey:(id)arg2;
+ (id)imageParserWithContentsOfFileAsynchronously:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
+ (id)imageParserWithDataAsynchronously:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
+ (id)imageWithContentsOfFile:(id)arg1;
+ (id)imageWithContentsOfFileAsynchronously:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
+ (id)imageWithContentsOfURL:(id)arg1;
+ (id)imageWithData:(id)arg1;
+ (id)imageWithDataAsynchronously:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
+ (id)imageWithSource:(id)arg1;
+ (id)imageWithSource:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) CALayer *CALayerTree; // @synthesize CALayerTree;
@property(retain, nonatomic) BU_SVGDocument *DOMDocument; // @synthesize DOMDocument;
@property(retain, nonatomic) BU_SVGSVGElement *DOMTree; // @synthesize DOMTree;
@property(readonly, nonatomic) __weak UIImage *UIImage;
- (void)addSVGLayerTree:(id)arg1 withIdentifier:(id)arg2 toDictionary:(id)arg3;
- (void)dealloc;
- (id)dictionaryOfLayers;
- (void)drawAsPatternInRect:(struct CGRect)arg1;
- (void)drawAtPoint:(struct CGPoint)arg1;
- (void)drawAtPoint:(struct CGPoint)arg1 blendMode:(int)arg2 alpha:(double)arg3;
- (void)drawInRect:(struct CGRect)arg1;
- (void)drawInRect:(struct CGRect)arg1 blendMode:(int)arg2 alpha:(double)arg3;
- (_Bool)hasSize;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)initWithParsedSVG:(id)arg1 fromSource:(id)arg2;
- (id)initWithSource:(id)arg1;
@property(nonatomic) struct CGSize internalSizeThatWasSetExplicitlyByUser; // @synthesize internalSizeThatWasSetExplicitlyByUser=_internalSizeThatWasSetExplicitlyByUser;
- (_Bool)isElementVisible:(id)arg1;
- (id)layerWithIdentifier:(id)arg1;
- (id)layerWithIdentifier:(id)arg1 layer:(id)arg2;
@property(retain, nonatomic) NSString *nameUsedToInstantiate; // @synthesize nameUsedToInstantiate=_nameUsedToInstantiate;
- (id)newCALayerTree;
- (struct CGContext *)newCGContextAutosizedToFit;
- (id)newCopyPositionedAbsoluteLayerWithIdentifier:(id)arg1;
- (id)newCopyPositionedAbsoluteOfLayer:(id)arg1;
- (id)newCopyPositionedAbsoluteOfLayer:(id)arg1 withSubLayers:(_Bool)arg2;
- (id)newLayerWithElement:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) BU_SVGKParseResult *parseErrorsAndWarnings; // @synthesize parseErrorsAndWarnings;
- (void)renderInContext:(struct CGContext *)arg1;
- (void)renderToContext:(struct CGContext *)arg1 antiAliased:(_Bool)arg2 curveFlatnessFactor:(double)arg3 interpolationQuality:(int)arg4 flipYaxis:(_Bool)arg5;
@property(nonatomic) double scale; // @synthesize scale=_scale;
- (void)scaleToFitInside:(struct CGSize)arg1;
@property(nonatomic) struct CGSize size;
@property(retain, nonatomic) BU_SVGKSource *source; // @synthesize source;

@end

