//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUNetworkRequest.h"

@interface BUAdNetworkRequest : BUNetworkRequest
{
}

+ (id)bu_base_URL;
- (id)TNCServiceKey;
- (id)baseUrl;
- (CDUnknownBlockType)failureCompletionBlock;
- (id)initWithUrl:(id)arg1 method:(long long)arg2 parameter:(id)arg3;
- (CDUnknownBlockType)successCompletionBlock;

@end

