//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BUAdBannerSlot : NSObject
{
    long long _isRotateBanner;
    long long _rotateTime;
    long long _rotateOrder;
}

- (id)dictionaryValue;
@property(nonatomic) long long isRotateBanner; // @synthesize isRotateBanner=_isRotateBanner;
@property(nonatomic) long long rotateOrder; // @synthesize rotateOrder=_rotateOrder;
@property(nonatomic) long long rotateTime; // @synthesize rotateTime=_rotateTime;

@end

