//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUAdPCMThreadManagerDelegate-Protocol.h"

@class NSMutableArray, NSString, NSThread, NSTimer;
@protocol BUPersistenceProtocol;

@interface BUAdPCMTrackManager : NSObject <BUAdPCMThreadManagerDelegate>
{
    NSString *_uploadURL;
    id <BUPersistenceProtocol> _persistence_click;
    id <BUPersistenceProtocol> _persistence_conversion;
    NSTimer *_timer;
    NSThread *_pcmThread;
    NSMutableArray *_showArr;
    NSMutableArray *_clickArr;
    NSMutableArray *_conversionArr;
}

+ (void)addClickTrackData:(id)arg1;
+ (void)addConversionTrackData:(id)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)setUploadURL:(id)arg1;
+ (id)shareInstance;
+ (void)showPCMTrack:(id)arg1;
+ (void)task;
- (void).cxx_destruct;
- (void)addClickTrackData:(id)arg1;
- (void)addConversionTrackData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *clickArr; // @synthesize clickArr=_clickArr;
@property(retain, nonatomic) NSMutableArray *conversionArr; // @synthesize conversionArr=_conversionArr;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)couldUseAEM:(id)arg1;
- (void)creatNecessary;
@property(retain, nonatomic) NSThread *pcmThread; // @synthesize pcmThread=_pcmThread;
- (void)pcmThreadStateReady;
@property(retain, nonatomic) id <BUPersistenceProtocol> persistence_click; // @synthesize persistence_click=_persistence_click;
@property(retain, nonatomic) id <BUPersistenceProtocol> persistence_conversion; // @synthesize persistence_conversion=_persistence_conversion;
- (void)removeClickTrackData:(id)arg1;
- (void)removeConversionTrackData:(id)arg1;
- (void)removeTimeoutClick;
@property(retain, nonatomic) NSMutableArray *showArr; // @synthesize showArr=_showArr;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(copy) NSString *uploadURL; // @synthesize uploadURL=_uploadURL;
- (void)showPCMTrack:(id)arg1;
- (void)trackUpload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

