//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSThread;
@protocol BUAdPCMThreadManagerDelegate;

@interface BUAdPCMThreadManager : NSObject
{
    _Bool _pcmThreadStateReady;
    NSThread *_thread;
    id <BUAdPCMThreadManagerDelegate> _delegate;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shareInstance;
+ (void)taskWithDelegate:(id)arg1;
+ (id)thread;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) __weak id <BUAdPCMThreadManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly) _Bool pcmThreadStateReady; // @synthesize pcmThreadStateReady=_pcmThreadStateReady;
@property(retain, nonatomic) NSThread *thread; // @synthesize thread=_thread;
- (void)task;

@end

