//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BUCoverView, NSDictionary;

@protocol BUCoverViewDelegate <NSObject>
- (void)coverViewClick:(BUCoverView *)arg1 withClickExtraInfo:(NSDictionary *)arg2;
- (void)coverViewClickAdLogo:(BUCoverView *)arg1;
- (void)coverViewClickClose:(BUCoverView *)arg1;
- (void)coverViewClickDownload:(BUCoverView *)arg1 withClickExtraInfo:(NSDictionary *)arg2;
- (void)coverViewClickVideo:(BUCoverView *)arg1;
@end

