//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, NSTimer;

@interface BUDevice : NSObject
{
    _Bool _isAsiaZone;
    _Bool _isEuropeZone;
    NSString *_applog_did;
    NSString *_device_id;
    NSString *_imei;
    long long _type;
    long long _os;
    NSString *_osVersion;
    NSString *_buildVersion;
    NSString *_devLangLocalization;
    NSString *_vendor;
    NSString *_devModelType;
    long long _connType;
    NSString *_volume_capacity;
    unsigned long long _screenWidth;
    unsigned long long _screenHeight;
    NSString *_pb;
    NSString *_imsi;
    NSString *_carrierName;
    NSString *_MCC;
    NSString *_MNC;
    NSString *_boot;
    NSString *_powerOnTime;
    NSString *_phoneName;
    NSString *_devTagName;
    NSString *_ip;
    NSString *_userAgent;
    NSString *_timeFormatRegion;
    NSString *_deviceCity;
    NSString *_secondsFromGMT;
    NSString *_idfv;
    NSNumber *_deviceFreeSize;
    NSString *_countryOrderNum;
    NSString *_totalMemory;
    NSString *_deviceTotalSize;
    NSString *_localTimeZone;
    long long _cpuNum;
    NSString *_deviceType;
    NSString *_localeLanguage;
    NSString *_screenshot_time;
    NSString *_msdk_sec_did;
    long long _airplane;
    long long _darkmode;
    long long _headset;
    double _screenScale;
    NSTimer *_timer;
}

+ (long long)batteryState;
+ (float)battery_remaining_pct;
+ (long long)bu_currentOrientation;
+ (id)currentDevice;
+ (_Bool)is_screen_off;
+ (unsigned long long)supportLandscapeBySystemConfiguration;
+ (unsigned long long)supportOrientationBySystemConfiguration;
- (void).cxx_destruct;
- (long long)GetNetWorkType;
@property(copy) NSString *MCC; // @synthesize MCC=_MCC;
@property(copy) NSString *MNC; // @synthesize MNC=_MNC;
- (long long)_cpuNum;
- (id)_memory;
- (long long)_totalDiskSpace;
@property long long airplane; // @synthesize airplane=_airplane;
@property(copy) NSString *applog_did; // @synthesize applog_did=_applog_did;
@property(copy) NSString *boot; // @synthesize boot=_boot;
- (void)bu_checkUserInterfaceStyle;
- (id)bu_currentLanguage;
- (void)bu_setAirplane;
- (void)bu_setHeadset;
@property(copy) NSString *buildVersion; // @synthesize buildVersion=_buildVersion;
@property(copy) NSString *carrierName; // @synthesize carrierName=_carrierName;
@property long long connType; // @synthesize connType=_connType;
@property(copy) NSString *countryOrderNum; // @synthesize countryOrderNum=_countryOrderNum;
@property long long cpuNum; // @synthesize cpuNum=_cpuNum;
@property long long darkmode; // @synthesize darkmode=_darkmode;
- (void)dealloc;
@property(copy) NSString *devLangLocalization; // @synthesize devLangLocalization=_devLangLocalization;
@property(copy, nonatomic) NSString *devModelType; // @synthesize devModelType=_devModelType;
@property(copy) NSString *devTagName; // @synthesize devTagName=_devTagName;
@property(copy) NSString *deviceCity; // @synthesize deviceCity=_deviceCity;
@property(retain) NSNumber *deviceFreeSize; // @synthesize deviceFreeSize=_deviceFreeSize;
@property(readonly, copy) NSString *deviceTotalSize; // @synthesize deviceTotalSize=_deviceTotalSize;
@property(copy) NSString *deviceType; // @synthesize deviceType=_deviceType;
@property(copy, nonatomic) NSString *device_id; // @synthesize device_id=_device_id;
- (id)dictionaryValue;
- (id)getCarrierName;
- (long long)getCurrentDeviceType;
- (id)getCurrentIMSI;
- (id)getDeviceFreeSize;
- (id)getEtcTimeZone;
- (id)getLanguage;
- (id)getSecondsFromGMT;
- (id)getTimeZoneCity;
@property long long headset; // @synthesize headset=_headset;
@property(copy) NSString *idfv; // @synthesize idfv=_idfv;
@property(copy) NSString *imei; // @synthesize imei=_imei;
@property(copy) NSString *imsi; // @synthesize imsi=_imsi;
- (id)init;
@property(copy) NSString *ip; // @synthesize ip=_ip;
- (_Bool)isAmericaZone;
@property(nonatomic) _Bool isAsiaZone; // @synthesize isAsiaZone=_isAsiaZone;
@property(nonatomic) _Bool isEuropeZone; // @synthesize isEuropeZone=_isEuropeZone;
- (void)loadCurrentAppInfo;
- (void)loadOverSeaPrivateInfo;
@property(copy, nonatomic) NSString *localTimeZone; // @synthesize localTimeZone=_localTimeZone;
@property(copy) NSString *localeLanguage; // @synthesize localeLanguage=_localeLanguage;
@property(copy) NSString *msdk_sec_did; // @synthesize msdk_sec_did=_msdk_sec_did;
@property long long os; // @synthesize os=_os;
@property(copy) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(copy) NSString *pb; // @synthesize pb=_pb;
@property(copy) NSString *phoneName; // @synthesize phoneName=_phoneName;
@property(copy) NSString *powerOnTime; // @synthesize powerOnTime=_powerOnTime;
- (void)resetPrivateInfo;
@property unsigned long long screenHeight; // @synthesize screenHeight=_screenHeight;
@property(nonatomic) double screenScale; // @synthesize screenScale=_screenScale;
@property unsigned long long screenWidth; // @synthesize screenWidth=_screenWidth;
@property(copy) NSString *screenshot_time; // @synthesize screenshot_time=_screenshot_time;
@property(copy, nonatomic) NSString *secondsFromGMT; // @synthesize secondsFromGMT=_secondsFromGMT;
@property(copy) NSString *timeFormatRegion; // @synthesize timeFormatRegion=_timeFormatRegion;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(copy) NSString *totalMemory; // @synthesize totalMemory=_totalMemory;
@property long long type; // @synthesize type=_type;
@property(copy) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(copy) NSString *vendor; // @synthesize vendor=_vendor;
@property(copy, nonatomic) NSString *volume_capacity; // @synthesize volume_capacity=_volume_capacity;
- (id)systemUpdateTime;
- (long long)volume;

@end

