//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class BUDislikeNewRealInputView, UIImageView, UILabel, UITextField;
@protocol BUDislikeNewInputViewDelegate;

@interface BUDislikeNewInputView : UIView
{
    _Bool _validInputAccessoryView;
    _Bool _showKeyboard;
    id <BUDislikeNewInputViewDelegate> _delegate;
    UITextField *_placeholderTextField;
    UIImageView *_imageView;
    UILabel *_suggestionLabel;
    BUDislikeNewRealInputView *_dislikeNewRealInputView;
}

- (void).cxx_destruct;
- (double)backupInputViewRealHeight;
- (void)dealloc;
@property(nonatomic) __weak id <BUDislikeNewInputViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) BUDislikeNewRealInputView *dislikeNewRealInputView; // @synthesize dislikeNewRealInputView=_dislikeNewRealInputView;
- (void)handleCustomAccessoryViewWithNotification:(id)arg1;
- (void)hideKeyboard;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)inputAccessoryView;
- (double)inputViewRealHeight;
- (void)layoutSubviews;
@property(retain, nonatomic) UITextField *placeholderTextField; // @synthesize placeholderTextField=_placeholderTextField;
- (void)setDarkStyle;
- (void)setLightStyle;
@property(nonatomic) _Bool showKeyboard; // @synthesize showKeyboard=_showKeyboard;
@property(retain, nonatomic) UILabel *suggestionLabel; // @synthesize suggestionLabel=_suggestionLabel;
@property(nonatomic) _Bool validInputAccessoryView; // @synthesize validInputAccessoryView=_validInputAccessoryView;
- (void)traitCollectionDidChange:(id)arg1;
- (void)uiKeyboardDidHideNotification:(id)arg1;
- (void)uiKeyboardDidShowNotification:(id)arg1;
- (void)uiKeyboardWillHideNotification:(id)arg1;
- (void)uiKeyboardWillShowNotification:(id)arg1;

@end

