//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface BUDirectLandingPageInfo : NSObject <NSCoding>
{
    NSString *_directLandingUrl;
    long long _displayDuration;
    long long _closeTime;
}

- (void).cxx_destruct;
@property(nonatomic) long long closeTime; // @synthesize closeTime=_closeTime;
- (id)convertToPlayableInfo;
@property(copy, nonatomic) NSString *directLandingUrl; // @synthesize directLandingUrl=_directLandingUrl;
@property(nonatomic) long long displayDuration; // @synthesize displayDuration=_displayDuration;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (_Bool)isValid;
- (void)setupDataWithDictionary:(id)arg1;

@end

