//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BUDownloadSpeedModel : NSObject
{
    double _startDownloadTime;
    double _finishDownloadTime;
    long long _downloadSize;
    double _speed;
}

@property long long downloadSize; // @synthesize downloadSize=_downloadSize;
@property double finishDownloadTime; // @synthesize finishDownloadTime=_finishDownloadTime;
@property(nonatomic) double speed; // @synthesize speed=_speed;
@property double startDownloadTime; // @synthesize startDownloadTime=_startDownloadTime;

@end

