//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUDynamicInteractionAbstractDecorator.h"

@class BUSplashBottomUpSwipeAnimationComponentView;

@interface BUDynamicInteractionSlide5Decorator : BUDynamicInteractionAbstractDecorator
{
    BUSplashBottomUpSwipeAnimationComponentView *_slideAnimationView;
}

- (void).cxx_destruct;
- (void)render;
@property(retain, nonatomic) BUSplashBottomUpSwipeAnimationComponentView *slideAnimationView; // @synthesize slideAnimationView=_slideAnimationView;
- (void)showInteractionDecorator:(id)arg1;

@end

