//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUDynamicAbstractDecorator.h"

@class UILabel;

@interface BUDynamicLabelDecorator : BUDynamicAbstractDecorator
{
    UILabel *_label;
}

- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void)render;
- (void)sizeToFitIfNeed;
- (void)updateTheme;

@end

