//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUDynamicInteractionAbstractDecorator.h"

@class BUSplashBottomShakeAnimationView, BUSplashMotionManager;

@interface BUDynamicInteractionShake2Decorator : BUDynamicInteractionAbstractDecorator
{
    BUSplashBottomShakeAnimationView *_shakeAnimationMask;
    BUSplashMotionManager *_motionManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BUSplashMotionManager *motionManager; // @synthesize motionManager=_motionManager;
- (void)render;
@property(retain, nonatomic) BUSplashBottomShakeAnimationView *shakeAnimationMask; // @synthesize shakeAnimationMask=_shakeAnimationMask;
- (void)showInteractionDecorator:(id)arg1;

@end

