//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUDynamicRenderNativeStrategy.h"

@interface BUDynamicRenderNative2Strategy : BUDynamicRenderNativeStrategy
{
}

- (long long)dynamicEngineVersion;
- (id)dynamic_render_error;
- (id)dynamic_render_start;
- (id)dynamic_render_success;
- (id)layoutDebugInfoKey;
- (id)logKeyName;
- (long long)renderType;
- (long long)timeoutErrorCode;

@end

