//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BURenderStrategyDelegate-Protocol.h"

@class BUDynamicRenderStrategy, NSError, NSString;

@protocol BUDynamicRenderStrategyDelegate <BURenderStrategyDelegate>

@optional
- (void)dynamicRenderStrategy:(BUDynamicRenderStrategy *)arg1 reportError:(NSError *)arg2;
- (void)dynamicRenderStrategy:(BUDynamicRenderStrategy *)arg1 reportLabel:(NSString *)arg2;
- (long long)playPercentInDynamicRenderStrategy:(BUDynamicRenderStrategy *)arg1;
- (double)renderTimeoutInDynamicRenderStrategy:(BUDynamicRenderStrategy *)arg1;
@end

