//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BUDynamicCreativeImageModel : NSObject
{
    long long _height;
    NSString *_url;
    long long _width;
}

- (void).cxx_destruct;
@property(nonatomic) long long height; // @synthesize height=_height;
- (id)initWithDictionary:(id)arg1;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long width; // @synthesize width=_width;

@end

