//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BUDynamicAdSizeModel, BUDynamicCreativeModel, BUDynamicSettingModel, NSDictionary, NSString;

@interface BUDynamicTemplateInfoModel : NSObject
{
    BUDynamicAdSizeModel *_adSize;
    BUDynamicCreativeModel *_creative;
    BUDynamicSettingModel *_setting;
    NSString *_diff_template_Plugin;
    NSDictionary *_diff_template_PluginDict;
    NSDictionary *_synthesis_template_PluginDict;
    NSString *_platform;
    NSString *_template_Plugin;
    NSDictionary *_template_PluginDict;
}

- (void).cxx_destruct;
- (void)_pbu_diff_template_Plugin_ifNeed;
- (void)_pbu_synthesis;
@property(retain, nonatomic) BUDynamicAdSizeModel *adSize; // @synthesize adSize=_adSize;
@property(retain, nonatomic) BUDynamicCreativeModel *creative; // @synthesize creative=_creative;
@property(copy, nonatomic) NSString *diff_template_Plugin; // @synthesize diff_template_Plugin=_diff_template_Plugin;
@property(copy, nonatomic) NSDictionary *diff_template_PluginDict; // @synthesize diff_template_PluginDict=_diff_template_PluginDict;
- (id)initWithDictionary:(id)arg1;
@property(copy, nonatomic) NSString *platform; // @synthesize platform=_platform;
@property(retain, nonatomic) BUDynamicSettingModel *setting; // @synthesize setting=_setting;
@property(copy, nonatomic) NSDictionary *synthesis_template_PluginDict; // @synthesize synthesis_template_PluginDict=_synthesis_template_PluginDict;
@property(copy, nonatomic) NSString *template_Plugin; // @synthesize template_Plugin=_template_Plugin;
@property(copy, nonatomic) NSDictionary *template_PluginDict; // @synthesize template_PluginDict=_template_PluginDict;

@end

