//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BUTimer;

@interface BUDynamicRenderTimeOutControlServer : NSObject
{
    _Bool _hasRenderFinish;
    double _delayTime;
    double _timeout;
    BUTimer *_renderTimer;
}

- (void).cxx_destruct;
- (void)delayRender:(CDUnknownBlockType)arg1;
@property(nonatomic) double delayTime; // @synthesize delayTime=_delayTime;
@property(nonatomic) _Bool hasRenderFinish; // @synthesize hasRenderFinish=_hasRenderFinish;
@property(retain, nonatomic) BUTimer *renderTimer; // @synthesize renderTimer=_renderTimer;
@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
- (void)startRenderWithDelayTime:(double)arg1 delayRender:(CDUnknownBlockType)arg2;

@end

