//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BUFullScreenInterstitialAdView, NSDictionary, NSError;

@protocol BUFullScreenInterstitialAdDelegate <NSObject>

@optional
- (void)fullScreenImageAdDidClick:(BUFullScreenInterstitialAdView *)arg1 extraDic:(NSDictionary *)arg2;
- (void)fullScreenInterstitialAdPlayerDidPlayFinish:(BUFullScreenInterstitialAdView *)arg1;
- (void)fullScreenInterstitialAdPlayerReadyToPlay:(BUFullScreenInterstitialAdView *)arg1;
- (void)fullScreenInterstitialAdVideoViewDidClick:(BUFullScreenInterstitialAdView *)arg1;
- (void)fullScreenInterstitialAdView:(BUFullScreenInterstitialAdView *)arg1 downloadBarTapped:(id)arg2 extraDic:(NSDictionary *)arg3;
- (void)fullScreenInterstitialAdView:(BUFullScreenInterstitialAdView *)arg1 downloadButtonTapped:(id)arg2 extraDic:(NSDictionary *)arg3;
- (void)fullScreenInterstitialAdView:(BUFullScreenInterstitialAdView *)arg1 videoDidLoadFailWithError:(NSError *)arg2;
- (void)fullScreenInterstitialAdView:(BUFullScreenInterstitialAdView *)arg1 videoStateDidChanged:(long long)arg2;
- (void)fullScreenInterstitialAdViewDidClick:(BUFullScreenInterstitialAdView *)arg1 extraDic:(NSDictionary *)arg2;
- (void)fullScreenInterstitialAdViewDidTapCloseButton:(BUFullScreenInterstitialAdView *)arg1;
- (void)fullScreenInterstitialAdViewDidTapDislikeButton:(BUFullScreenInterstitialAdView *)arg1;
- (void)fullScreenInterstitialAdViewDidTapLogoImageView:(BUFullScreenInterstitialAdView *)arg1;
@end

