//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BUThreadSafeDictionary, BUThreadSafeMutableArray;

@interface BUFullLinkTrackInfo : NSObject
{
    BUThreadSafeDictionary *_logDict;
    BUThreadSafeMutableArray *_sequenceArray;
}

- (void).cxx_destruct;
- (void)addWithLogKey:(id)arg1 extraDic:(id)arg2;
- (id)dictionaryValue;
- (id)init;
@property(retain, nonatomic) BUThreadSafeDictionary *logDict; // @synthesize logDict=_logDict;
@property(retain, nonatomic) BUThreadSafeMutableArray *sequenceArray; // @synthesize sequenceArray=_sequenceArray;

@end

