//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUCoverView.h"

#import "BUVideoAdViewDelegate-Protocol.h"

@class BUNativeAdRelatedView, NSString;
@protocol BUInterstitialCoverViewDelegate;

@interface BUInterstitialCoverView : BUCoverView <BUVideoAdViewDelegate>
{
    _Bool _haveVideoView;
    id <BUInterstitialCoverViewDelegate> _interstitialDelegate;
    BUNativeAdRelatedView *_nativeAdRelatedView;
}

- (void).cxx_destruct;
- (void)addVideoViewIfNeed;
- (void)dealloc;
@property(nonatomic) _Bool haveVideoView; // @synthesize haveVideoView=_haveVideoView;
@property(nonatomic) id <BUInterstitialCoverViewDelegate> interstitialDelegate; // @synthesize interstitialDelegate=_interstitialDelegate;
- (void)interstitialVideoDidClick:(id)arg1;
@property(retain, nonatomic) BUNativeAdRelatedView *nativeAdRelatedView; // @synthesize nativeAdRelatedView=_nativeAdRelatedView;
- (void)pbu_override_buildView;
- (void)pbu_override_buildViewData;
- (double)playerCurrentTime;
- (void)playerDidPlayFinish:(id)arg1;
- (void)playerReadyToPlay:(id)arg1;
- (double)playerTotalTime;
- (void)videoAdView:(id)arg1 didLoadFailWithError:(id)arg2;
- (void)videoAdView:(id)arg1 stateDidChanged:(long long)arg2;
- (void)videoAdViewDidClick:(id)arg1;
- (void)videoAdViewDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (void)videoAdViewFinishViewDidClick:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

