//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BUInterstitialCoverView, NSError;

@protocol BUInterstitialCoverViewDelegate <NSObject>

@optional
- (void)interstitialCoverView:(BUInterstitialCoverView *)arg1 videoDidLoadFailWithError:(NSError *)arg2;
- (void)interstitialCoverView:(BUInterstitialCoverView *)arg1 videoStateDidChanged:(long long)arg2;
- (void)playerDidPlayFinish:(BUInterstitialCoverView *)arg1;
- (void)playerReadyToPlay:(BUInterstitialCoverView *)arg1;
- (void)videoAdViewDidClick:(BUInterstitialCoverView *)arg1;
- (void)videoAdViewDidCloseOtherController:(BUInterstitialCoverView *)arg1 interactionType:(long long)arg2;
- (void)videoAdViewFinishViewDidClick:(BUInterstitialCoverView *)arg1;
@end

