//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUSplashCoverView.h"

@class UIView;

@interface BUMiddleSplashCoverView : BUSplashCoverView
{
    UIView *_titleView;
}

- (void).cxx_destruct;
- (void)pbu_override_buildView;
- (void)pbu_override_buildViewData;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;

@end

