//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUAdClientBiddingProtocol-Protocol.h"
#import "BUMopubAdMarkUpDelegate-Protocol.h"
#import "BUNativeExpressAdViewDelegate-Protocol.h"

@class BUAdClientBiddingHandle, BUAdSlot, BUNativeExpressAdManager, BUNativeExpressAdView, NSDictionary, NSString;
@protocol BUNativeExpresInterstitialAdDelegate;

@interface BUNativeExpressInterstitialAd : NSObject <BUNativeExpressAdViewDelegate, BUMopubAdMarkUpDelegate, BUAdClientBiddingProtocol>
{
    id <BUNativeExpresInterstitialAdDelegate> _delegate;
    BUAdSlot *_slot;
    NSDictionary *_mediaExtInfo;
    BUAdClientBiddingHandle *_clientBiddingHandle;
    BUNativeExpressAdManager *_nativeExpressAdManager;
    BUNativeExpressAdView *_expressAdView;
    long long _realSlotRenderType;
    struct CGSize _adSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize adSize; // @synthesize adSize=_adSize;
- (id)biddingToken;
@property(retain, nonatomic) BUAdClientBiddingHandle *clientBiddingHandle; // @synthesize clientBiddingHandle=_clientBiddingHandle;
@property(nonatomic) __weak id <BUNativeExpresInterstitialAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) BUNativeExpressAdView *expressAdView; // @synthesize expressAdView=_expressAdView;
- (id)getAdCreativeToken;
- (id)initWithSlot:(id)arg1 adSize:(struct CGSize)arg2;
- (id)initWithSlotID:(id)arg1 adSize:(struct CGSize)arg2;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
- (void)loadAdData;
- (void)loss:(id)arg1 lossReason:(id)arg2 winBidder:(id)arg3;
@property(readonly, copy, nonatomic) NSDictionary *mediaExt;
@property(copy, nonatomic) NSDictionary *mediaExtInfo; // @synthesize mediaExtInfo=_mediaExtInfo;
- (void)nativeExpressAdFailToLoad:(id)arg1 error:(id)arg2;
@property(retain, nonatomic) BUNativeExpressAdManager *nativeExpressAdManager; // @synthesize nativeExpressAdManager=_nativeExpressAdManager;
- (void)nativeExpressAdSuccessToLoad:(id)arg1 views:(id)arg2;
- (void)nativeExpressAdView:(id)arg1 dislikeWithReason:(id)arg2;
- (void)nativeExpressAdView:(id)arg1 stateDidChanged:(long long)arg2;
- (void)nativeExpressAdViewDidClick:(id)arg1;
- (void)nativeExpressAdViewDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (void)nativeExpressAdViewPlayerDidPlayFinish:(id)arg1 error:(id)arg2;
- (void)nativeExpressAdViewRenderFail:(id)arg1 error:(id)arg2;
- (void)nativeExpressAdViewRenderSuccess:(id)arg1;
- (void)nativeExpressAdViewWillPresentScreen:(id)arg1;
- (void)nativeExpressAdViewWillShow:(id)arg1;
@property(nonatomic) long long realSlotRenderType; // @synthesize realSlotRenderType=_realSlotRenderType;
- (void)safeDelegate_nativeExpresInterstitialAd:(id)arg1 didFailWithError:(id)arg2;
- (void)safeDelegate_nativeExpresInterstitialAdDidClick:(id)arg1;
- (void)safeDelegate_nativeExpresInterstitialAdDidClose:(id)arg1;
- (void)safeDelegate_nativeExpresInterstitialAdDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (void)safeDelegate_nativeExpresInterstitialAdDidLoad:(id)arg1;
- (void)safeDelegate_nativeExpresInterstitialAdRenderFail:(id)arg1 error:(id)arg2;
- (void)safeDelegate_nativeExpresInterstitialAdRenderSuccess:(id)arg1;
- (void)safeDelegate_nativeExpresInterstitialAdWillClose:(id)arg1;
- (void)safeDelegate_nativeExpresInterstitialAdWillVisible:(id)arg1;
- (void)setMopubAdMarkUp:(id)arg1;
- (void)setPrice:(id)arg1;
@property(retain, nonatomic) BUAdSlot *slot; // @synthesize slot=_slot;
- (_Bool)showAdFromRootViewController:(id)arg1;
- (void)win:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

