//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class BUAdSlot, BUExpressRewardFullScreenVM;
@protocol BUNativeExpressVideoAdDelegate;

@interface BUNativeExpressRewardedVideoAdViewController : UIViewController
{
    BUExpressRewardFullScreenVM *_viewModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BUAdSlot *adSlot;
- (id)initWithNativeExpressAdView:(id)arg1 purePlayableNativeAd:(id)arg2;
@property(nonatomic) _Bool isRewardedVideo;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)prefersStatusBarHidden;
@property(copy, nonatomic) CDUnknownBlockType purePlayableClickBlock;
- (id)reallyMaterialMeta;
@property(nonatomic) __weak id <BUNativeExpressVideoAdDelegate> rewardedVideoAd;
@property(retain, nonatomic) BUExpressRewardFullScreenVM *viewModel; // @synthesize viewModel=_viewModel;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end

