//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUMopubAdMarkUpDelegate-Protocol.h"
#import "BUNativeExpressAdConverterDelegate-Protocol.h"

@class BUAdSlot, BUNativeExpressAdConverter, NSArray, NSMutableArray, NSString;
@protocol BUNativeAdsManagerDelegate, BUNativeExpressAdViewDelegate;

@interface BUNativeAdsManager : NSObject <BUNativeExpressAdConverterDelegate, BUMopubAdMarkUpDelegate>
{
    BUAdSlot *_adslot;
    NSArray *_data;
    id <BUNativeAdsManagerDelegate> _delegate;
    id <BUNativeExpressAdViewDelegate> _nativeExpressAdViewDelegate;
    NSMutableArray *_adData;
    BUNativeExpressAdConverter *_nativeExpressAdConverter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *adData; // @synthesize adData=_adData;
@property(nonatomic) struct CGSize adSize;
@property(retain, nonatomic) BUAdSlot *adslot; // @synthesize adslot=_adslot;
- (id)assemblyNativeADWithMaterials:(id)arg1;
- (id)biddingToken;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
@property(nonatomic) __weak id <BUNativeAdsManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)expressAdViewDelegateInNativeExpressAdConverter:(id)arg1;
- (id)expressAdViewDismissDelegateInNativeExpressAdConverter:(id)arg1;
- (void)fetchAdDataWithTimes:(long long)arg1;
- (id)init;
- (id)initWithSlot:(id)arg1;
- (void)loadAdDataWithCount:(long long)arg1;
@property(retain, nonatomic) BUNativeExpressAdConverter *nativeExpressAdConverter; // @synthesize nativeExpressAdConverter=_nativeExpressAdConverter;
- (void)nativeExpressAdConverter:(id)arg1 nativeExpressAdViewArray:(id)arg2;
@property(nonatomic) __weak id <BUNativeExpressAdViewDelegate> nativeExpressAdViewDelegate; // @synthesize nativeExpressAdViewDelegate=_nativeExpressAdViewDelegate;
- (void)preLoadMiddlePage;
- (void)preLoadVideoData;
- (void)reportReceiveUnionPlatformMaterialsTimeTracker;
- (void)safeDelegate_nativeAdsManager:(id)arg1 didFailWithError:(id)arg2;
- (void)safeDelegate_nativeAdsManagerSuccessToLoad:(id)arg1 nativeAds:(id)arg2 isMopub:(_Bool)arg3;
- (void)safeDelegate_nativeExpressAdSuccessToLoad:(id)arg1 views:(id)arg2;
- (void)setMopubAdMarkUp:(id)arg1;
- (void)setMopubAdMarkUp:(id)arg1 successLoadVideo:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

