//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BUNetInfoHelper : NSObject
{
}

+ (id)GetNetWorkType;
+ (long long)GetNetWorkTypeCode;
+ (id)bu_addressOfHost:(id)arg1;
+ (id)bu_getIPAddress:(_Bool)arg1;
+ (id)bu_getIPAddresses;
+ (id)bu_userAgentString;
+ (id)carrierName;
+ (_Bool)isValidatIP:(id)arg1;

@end

