//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface BUPlayerItem : NSObject
{
    _Bool _enableH265;
    _Bool _enableH265DowngradePlay;
    _Bool _enableH264DowngradePlay;
    _Bool _enableCache;
    NSString *_title;
    NSURL *_videoURL_H264_Remote;
    NSURL *_videoURL_H264_Local;
    NSURL *_videoURL_H265_Remote;
    NSURL *_videoURL_H265_Local;
    NSString *_placeholderImageURLString;
    long long _placeholderImageContentMode;
    long long _seekTime;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool enableCache; // @synthesize enableCache=_enableCache;
@property(nonatomic) _Bool enableH264DowngradePlay; // @synthesize enableH264DowngradePlay=_enableH264DowngradePlay;
@property(nonatomic) _Bool enableH265; // @synthesize enableH265=_enableH265;
@property(nonatomic) _Bool enableH265DowngradePlay; // @synthesize enableH265DowngradePlay=_enableH265DowngradePlay;
@property(nonatomic) long long placeholderImageContentMode; // @synthesize placeholderImageContentMode=_placeholderImageContentMode;
@property(copy, nonatomic) NSString *placeholderImageURLString; // @synthesize placeholderImageURLString=_placeholderImageURLString;
@property(nonatomic) long long seekTime; // @synthesize seekTime=_seekTime;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSURL *videoURL_H264_Local; // @synthesize videoURL_H264_Local=_videoURL_H264_Local;
@property(retain, nonatomic) NSURL *videoURL_H264_Remote; // @synthesize videoURL_H264_Remote=_videoURL_H264_Remote;
@property(retain, nonatomic) NSURL *videoURL_H265_Local; // @synthesize videoURL_H265_Local=_videoURL_H265_Local;
@property(retain, nonatomic) NSURL *videoURL_H265_Remote; // @synthesize videoURL_H265_Remote=_videoURL_H265_Remote;

@end

