//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BUNativeAd, BURenderEngine, BURenderInteractionModel, NSDictionary, NSError, NSString, UIView;

@protocol BURenderEngineDelegate <NSObject>
- (BUNativeAd *)nativeAdInRenderEngine:(BURenderEngine *)arg1;
- (long long)playPercentInRenderEngine:(BURenderEngine *)arg1;
- (NSDictionary *)renderEngine:(BURenderEngine *)arg1 renderInteractionModel:(BURenderInteractionModel *)arg2;
- (NSDictionary *)renderEngine:(BURenderEngine *)arg1 renderInteractionModel:(BURenderInteractionModel *)arg2 withClickExtraInfo:(NSDictionary *)arg3;
- (void)renderEngine:(BURenderEngine *)arg1 reportError:(NSError *)arg2;
- (void)renderEngine:(BURenderEngine *)arg1 reportLabel:(NSString *)arg2;
- (void)renderEngine:(BURenderEngine *)arg1 report_webview_time_trackWithParams:(NSDictionary *)arg2;
- (void)renderEngine:(BURenderEngine *)arg1 successView:(UIView *)arg2 error:(NSError *)arg3;
- (double)renderTimeoutInRenderEngine:(BURenderEngine *)arg1;
@end

