//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUDynamicRenderStrategyDelegate-Protocol.h"
#import "BURenderStrategyDelegate-Protocol.h"

@class BUAdInfoViewModel, BUFullLinkTrackInfo, BURenderResultModel, BURenderStrategy, NSArray, NSString;
@protocol BURenderEngineDelegate;

@interface BURenderEngine : NSObject <BURenderStrategyDelegate, BUDynamicRenderStrategyDelegate>
{
    _Bool _haveRenderEnd;
    long long _renderIndex;
    id <BURenderEngineDelegate> _delegate;
    BURenderResultModel *_renderResultModel;
    BURenderStrategy *_resultRenderStrategy;
    BUFullLinkTrackInfo *_fullLinkTrackInfo;
    NSArray *_renderStrategyArray;
    NSArray *_interceptArray;
    long long _currentRenderIndex;
    long long _themeStatusWhenStartRender;
    long long _themeStatusWhenEndRender;
    BUAdInfoViewModel *_infoViewModel;
}

+ (id)renderEngineWithInfoViewModel:(id)arg1 containerView:(id)arg2 renderIndex:(long long)arg3;
- (void).cxx_destruct;
- (void)buadNotifyKey_ThemeStatusChanged:(id)arg1;
@property(nonatomic) long long currentRenderIndex; // @synthesize currentRenderIndex=_currentRenderIndex;
- (void)dealloc;
- (void)debug_renderEngineLogWithKey:(id)arg1 key2:(id)arg2 msg:(id)arg3;
- (void)debug_renderEngineLogWithKey:(id)arg1 msg:(id)arg2;
@property(nonatomic) __weak id <BURenderEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dynamicRenderStrategy:(id)arg1 reportError:(id)arg2;
- (void)dynamicRenderStrategy:(id)arg1 reportLabel:(id)arg2;
@property(retain, nonatomic) BUFullLinkTrackInfo *fullLinkTrackInfo; // @synthesize fullLinkTrackInfo=_fullLinkTrackInfo;
@property(nonatomic) _Bool haveRenderEnd; // @synthesize haveRenderEnd=_haveRenderEnd;
@property(retain, nonatomic) BUAdInfoViewModel *infoViewModel; // @synthesize infoViewModel=_infoViewModel;
- (id)initWithRenderStrategyArray:(id)arg1;
@property(copy, nonatomic) NSArray *interceptArray; // @synthesize interceptArray=_interceptArray;
- (void)internal_renderEngineLogWithKey:(id)arg1 key2:(id)arg2 msg:(id)arg3;
- (void)internal_renderEngineLogWithKey:(id)arg1 msg:(id)arg2;
- (_Bool)isRenderNative;
- (id)logKeyName;
- (id)nativeAdInRenderStrategy:(id)arg1;
- (void)pbu_checkTheme;
- (void)pbu_fullTrackInfoAddWith_fullTrackKey:(id)arg1 fullTrackInfo:(id)arg2;
- (void)pbu_renderWithIndex:(long long)arg1;
- (void)pbu_updateThemeWithNewType:(long long)arg1;
- (long long)playPercentInDynamicRenderStrategy:(id)arg1;
- (void)render;
@property(nonatomic) long long renderIndex; // @synthesize renderIndex=_renderIndex;
@property(retain, nonatomic) BURenderResultModel *renderResultModel; // @synthesize renderResultModel=_renderResultModel;
- (void)renderStrategy:(id)arg1 fullTrackKey:(id)arg2 fullTrackInfo:(id)arg3;
- (void)renderStrategy:(id)arg1 interceptArray:(id)arg2;
- (void)renderStrategy:(id)arg1 logWithMsg:(id)arg2 isInternal:(_Bool)arg3;
- (id)renderStrategy:(id)arg1 renderInteractionModel:(id)arg2;
- (id)renderStrategy:(id)arg1 renderInteractionModel:(id)arg2 withClickExtraInfo:(id)arg3;
- (void)renderStrategy:(id)arg1 report_webview_time_trackWithParams:(id)arg2;
- (void)renderStrategy:(id)arg1 successView:(id)arg2 error:(id)arg3;
@property(copy, nonatomic) NSArray *renderStrategyArray; // @synthesize renderStrategyArray=_renderStrategyArray;
- (double)renderTimeoutInDynamicRenderStrategy:(id)arg1;
@property(retain, nonatomic) BURenderStrategy *resultRenderStrategy; // @synthesize resultRenderStrategy=_resultRenderStrategy;
- (id)safeDelegate_nativeAdInRenderEngine:(id)arg1;
- (long long)safeDelegate_playPercentInRenderEngine:(id)arg1;
- (id)safeDelegate_renderEngine:(id)arg1 renderInteractionModel:(id)arg2 withClickExtraInfo:(id)arg3;
- (void)safeDelegate_renderEngine:(id)arg1 reportError:(id)arg2;
- (void)safeDelegate_renderEngine:(id)arg1 reportLabel:(id)arg2;
- (void)safeDelegate_renderEngine:(id)arg1 report_webview_time_trackWithParams:(id)arg2;
- (void)safeDelegate_renderEngine:(id)arg1 successView:(id)arg2 error:(id)arg3;
- (double)safeDelegate_renderTimeoutInRenderEngine:(id)arg1;
@property(nonatomic) long long themeStatusWhenEndRender; // @synthesize themeStatusWhenEndRender=_themeStatusWhenEndRender;
@property(nonatomic) long long themeStatusWhenStartRender; // @synthesize themeStatusWhenStartRender=_themeStatusWhenStartRender;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

