//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class BUAdSlot, BUMaterialMeta, BUStarView, NSString, UIButton, UIImageView, UILabel;
@protocol BURewardedVideoDownloadBarDelegate;

@interface BURewardedVideoDownloadBarView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _isPortrait;
    _Bool _isNewStyle;
    id <BURewardedVideoDownloadBarDelegate> _delegate;
    BUMaterialMeta *_materialMeta;
    BUAdSlot *_slot;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_evaluationLabel;
    UIButton *_downloadButton;
    UILabel *_scoreLabel;
    BUStarView *_starView;
    unsigned long long _downloadBarStyle;
}

- (void).cxx_destruct;
- (void)addAccessibilityIdentifier;
- (void)addGesture;
- (void)buildUpView;
- (id)buttonText;
@property(nonatomic) __weak id <BURewardedVideoDownloadBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long downloadBarStyle; // @synthesize downloadBarStyle=_downloadBarStyle;
@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
- (void)downloadButtonTapped;
- (void)downloadTapped;
@property(retain, nonatomic) UILabel *evaluationLabel; // @synthesize evaluationLabel=_evaluationLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (id)initDownloadBarWith:(id)arg1 slot:(id)arg2 barStyle:(unsigned long long)arg3;
@property(nonatomic) _Bool isNewStyle; // @synthesize isNewStyle=_isNewStyle;
@property(nonatomic) _Bool isPortrait; // @synthesize isPortrait=_isPortrait;
- (void)layoutNewStyle;
- (void)layoutNewWithDescStyle;
- (void)layoutOldStyle;
- (void)layoutSubviews;
@property(retain, nonatomic) BUMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) BUAdSlot *slot; // @synthesize slot=_slot;
@property(retain, nonatomic) BUStarView *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

