//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUWebViewController.h"

#import "BURewardedVideoWebDefaultViewDelegate-Protocol.h"

@class BURewardedVideoWebViewControllerVM, NSString, UIButton;
@protocol BURewardedVideoWebViewDelegate;

@interface BURewardedVideoWebViewController : BUWebViewController <BURewardedVideoWebDefaultViewDelegate>
{
    BURewardedVideoWebViewControllerVM *_videoWebVM;
    struct CGSize _originSize;
}

- (void).cxx_destruct;
- (void)appendURLParameters;
- (void)dealloc;
@property(nonatomic) __weak id <BURewardedVideoWebViewDelegate> delegate;
- (void)didReceiveMemoryWarning;
@property(nonatomic) _Bool hiddenEndCardClose;
- (id)initViewControllerWithAd:(id)arg1 isNativeExpress:(_Bool)arg2 pageType:(unsigned long long)arg3;
@property(nonatomic) _Bool isRewardedVideo;
@property(nonatomic) _Bool isTransform;
@property(nonatomic) _Bool mute;
@property(nonatomic) struct CGSize originSize; // @synthesize originSize=_originSize;
- (long long)preferredInterfaceOrientationForPresentation;
@property(copy, nonatomic) NSString *ritScene;
@property(nonatomic) __weak UIButton *superVCCloseBtn;
@property(nonatomic) unsigned long long transformDirection;
@property(retain, nonatomic) BURewardedVideoWebViewControllerVM *videoWebVM; // @synthesize videoWebVM=_videoWebVM;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)trackLoadFailWithError:(id)arg1;
- (void)trackLoadFinish;
- (void)trackLoading;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)webCloseButtonTapped;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

