//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class BUAdSlot, BUMaterialMeta, BUStarView, UIButton, UIImageView, UILabel;
@protocol BURewardedVideoWebDefaultViewDelegate;

@interface BURewardedVideoWebDefaultView : UIView
{
    _Bool _isPortrait;
    id <BURewardedVideoWebDefaultViewDelegate> _delegate;
    BUMaterialMeta *_materialMeta;
    BUAdSlot *_slot;
    UIButton *_closeButton;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    BUStarView *_starView;
    UILabel *_scoreLabel;
    UIButton *_downloadButton;
    UIImageView *_logoImageView;
    UILabel *_ADXLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *ADXLabel; // @synthesize ADXLabel=_ADXLabel;
- (void)addAccessibilityIdentifier;
- (void)buildUpView;
- (id)buttonText;
- (id)c_xyDict;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak id <BURewardedVideoWebDefaultViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
- (void)downloadButtonTapped;
- (void)endCardClickEvent;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (id)initViewWithSlot:(id)arg1 ad:(id)arg2;
@property(nonatomic) _Bool isPortrait; // @synthesize isPortrait=_isPortrait;
- (void)layoutFullScreenStyle;
- (void)layoutInterstitialStyle;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
- (void)logoImageViewAction;
@property(retain, nonatomic) BUMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
- (double)scaleRatio;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) BUAdSlot *slot; // @synthesize slot=_slot;
@property(retain, nonatomic) BUStarView *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

