//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUMediaDownloaderDelegate-Protocol.h"

@class BUMediaCacheWorker, NSMutableArray, NSMutableDictionary, NSString, NSURL;
@protocol BUResourceLoaderDelegate;

@interface BUResourceLoader : NSObject <BUMediaDownloaderDelegate>
{
    struct _opaque_pthread_mutexattr_t _shared_mutexattr_t;
    struct _opaque_pthread_mutex_t _lock;
    NSURL *_url;
    CDUnknownBlockType _loadeFinishBlock;
    CDUnknownBlockType _loadedCancelBlock;
    id <BUResourceLoaderDelegate> _delegate;
    BUMediaCacheWorker *_cacheWorker;
    NSMutableArray *_mediaDownlader;
    NSMutableDictionary *_requestDownladerDic;
    long long _resceiveSize;
}

- (void).cxx_destruct;
- (void)addRequest:(id)arg1;
@property(retain, nonatomic) BUMediaCacheWorker *cacheWorker; // @synthesize cacheWorker=_cacheWorker;
- (void)dealloc;
@property(nonatomic) __weak id <BUResourceLoaderDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithURL:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType loadeFinishBlock; // @synthesize loadeFinishBlock=_loadeFinishBlock;
@property(copy, nonatomic) CDUnknownBlockType loadedCancelBlock; // @synthesize loadedCancelBlock=_loadedCancelBlock;
@property(retain, nonatomic) NSMutableArray *mediaDownlader; // @synthesize mediaDownlader=_mediaDownlader;
- (void)mediaDownloader:(id)arg1 didReceiveLength:(long long)arg2 didFinishedWithError:(id)arg3 responseDesc:(id)arg4 localCache:(_Bool)arg5;
- (void)removeRequest:(id)arg1;
- (void)requestCancel;
@property(retain, nonatomic) NSMutableDictionary *requestDownladerDic; // @synthesize requestDownladerDic=_requestDownladerDic;
- (void)requestWithSize:(unsigned long long)arg1;
@property(nonatomic) long long resceiveSize; // @synthesize resceiveSize=_resceiveSize;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

