//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BUSplashControlSlideAreaModel, NSString;

@protocol BUSplashBottomViewInterface <NSObject>

@optional
- (long long)shakeValue;
- (BUSplashControlSlideAreaModel *)slideArea;
- (double)splashBottomViewAreaBlankHeight;
- (double)splashBottomViewAreaHeight;
- (double)splashBottomViewAreaWidth;
- (NSString *)splashBottomViewBtnBackgroundDestColor;
- (NSString *)splashBottomViewClickText;
- (double)splashBottomViewClickTextFontSize;
- (double)splashBottomViewClickTopTextFontSize;
- (double)splashBottomViewHalfBlankHeight;
- (double)splashBottomViewShakeAmplitude;
- (NSString *)splashBottomViewTopClickText;
- (long long)twistRotationThreshold;
@end

