//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CMMotionManager;

@interface BUSplashMotionManager : NSObject
{
    CDUnknownBlockType _shakeAction;
    CMMotionManager *_motionManager;
    double _amplitude;
}

- (void).cxx_destruct;
@property(nonatomic) double amplitude; // @synthesize amplitude=_amplitude;
- (void)dealloc;
- (id)initWithShakeAmplitude:(double)arg1;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
- (void)outputAccelertionData:(CDStruct_31142d93)arg1;
@property(copy, nonatomic) CDUnknownBlockType shakeAction; // @synthesize shakeAction=_shakeAction;
- (void)startAccelerometer;

@end

