//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface BUTemplateModel : NSObject
{
    _Bool _reload;
    NSString *_main;
    NSString *_name;
    NSString *_version;
    NSArray *_resources;
    NSString *_fallback;
}

- (void).cxx_destruct;
- (id)dictionaryValue;
@property(copy, nonatomic) NSString *fallback; // @synthesize fallback=_fallback;
- (id)init;
- (id)initWithDicitonary:(id)arg1;
@property(copy, nonatomic) NSString *main; // @synthesize main=_main;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool reload; // @synthesize reload=_reload;
@property(copy, nonatomic) NSArray *resources; // @synthesize resources=_resources;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
- (_Bool)valid;

@end

