//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol BUPersistenceProtocol;

@interface BUTrackerStorage : NSObject
{
    NSString *_name;
    id <BUPersistenceProtocol> _persistence;
}

- (void).cxx_destruct;
- (id)_pbu_internal_allV1TracksWithSendingStatus:(_Bool)arg1;
- (void)_pbu_internal_deleteV1TrackCreatedBefore:(double)arg1;
- (id)_pbu_internal_insertV1Track:(id)arg1;
- (void)_pbu_internal_resetSendingStatus;
- (void)_pbu_internal_updateV1TrackOfIDs:(id)arg1 sending:(_Bool)arg2;
- (void)_pbu_resetSendingStatus;
- (id)allV1Tracks;
- (void)deleteV1TrackCreatedBefore:(double)arg1;
- (id)initWithName:(id)arg1;
- (id)insertV1Track:(id)arg1;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) id <BUPersistenceProtocol> persistence; // @synthesize persistence=_persistence;
- (void)removeV1TracksByID:(id)arg1;
- (void)updateV1TrackOfIDs:(id)arg1 sending:(_Bool)arg2;

@end

