//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "EBAppLogDelegateProtocol-Protocol.h"

@class BUABTest, BULogRateConfigModel, BUThreadSafeDictionary, NSArray, NSDate, NSDictionary, NSLock, NSNumber, NSString;

@interface BUUSettingService : NSObject <EBAppLogDelegateProtocol>
{
    _Bool _isReadVideoFromCache;
    _Bool _silenceSDK;
    _Bool _isGrey;
    _Bool _collectCrash;
    _Bool _checkTypeOpen;
    _Bool _haveSending;
    BUThreadSafeDictionary *_configList;
    NSString *_xpath;
    NSDictionary *_policy;
    NSNumber *_vbtt;
    NSString *_adsUrl;
    NSString *_appLogUrl;
    NSString *_apmOverseaUrl;
    BUABTest *_abtest;
    NSArray *_playableInterceptAry;
    NSString *_purePyloadH5;
    NSDictionary *_headersExt;
    long long _bothOpen;
    long long _supportTNC;
    NSString *_privacy_url;
    NSString *_consent_url;
    long long _max_tpl_cnts;
    NSString *_dyn_draw_engine_url;
    long long _fetch_tpl_timeout_ctrl;
    NSString *_force_language;
    long long _circle_time;
    long long _circle_splash;
    NSArray *_scheme_wlist;
    long long _icon_show_time;
    NSArray *_gecko_hosts;
    long long _webViewPoolCacheMaxCount;
    long long _webViewRenderMaxConcurrentOperationCount;
    long long _rotateBannerDislike;
    long long _sdMaxMemoryCount;
    long long _sdMaxMemoryCost;
    NSArray *_network_id_list;
    BULogRateConfigModel *_logRateConf;
    NSDictionary *_setting;
    NSArray *_localNetworkIdList;
    NSDate *_sendDate;
    NSLock *_adsURLLock;
}

+ (void)_reportCryptStatsWithError:(id)arg1;
+ (void)deleteLocalSetting;
+ (id)jsActLogURLString;
+ (id)service;
+ (id)shouldEvaluateActLogJsWith:(id)arg1;
- (void).cxx_destruct;
- (void)_checkNetworkConfig;
- (id)_readLocalNetworkConfig;
- (void)_setUpCacheConfigData;
@property(retain, nonatomic) BUABTest *abtest; // @synthesize abtest=_abtest;
@property(retain, nonatomic) NSLock *adsURLLock; // @synthesize adsURLLock=_adsURLLock;
@property(copy, nonatomic) NSString *adsUrl; // @synthesize adsUrl=_adsUrl;
@property(copy, nonatomic) NSString *apmOverseaUrl; // @synthesize apmOverseaUrl=_apmOverseaUrl;
@property(copy, nonatomic) NSString *appLogUrl; // @synthesize appLogUrl=_appLogUrl;
- (id)appRequestFieldsAllowed;
- (void)appWillEnterForeground:(id)arg1;
@property(nonatomic) long long bothOpen; // @synthesize bothOpen=_bothOpen;
- (void)buildupService;
@property(nonatomic) _Bool checkTypeOpen; // @synthesize checkTypeOpen=_checkTypeOpen;
@property(nonatomic) long long circle_splash; // @synthesize circle_splash=_circle_splash;
@property(nonatomic) long long circle_time; // @synthesize circle_time=_circle_time;
@property(nonatomic) _Bool collectCrash; // @synthesize collectCrash=_collectCrash;
@property(retain, nonatomic) BUThreadSafeDictionary *configList; // @synthesize configList=_configList;
@property(copy, nonatomic) NSString *consent_url; // @synthesize consent_url=_consent_url;
- (void)dealloc;
@property(copy, nonatomic) NSString *dyn_draw_engine_url; // @synthesize dyn_draw_engine_url=_dyn_draw_engine_url;
- (void)fetchSetting;
@property(nonatomic) long long fetch_tpl_timeout_ctrl; // @synthesize fetch_tpl_timeout_ctrl=_fetch_tpl_timeout_ctrl;
@property(copy, nonatomic) NSString *force_language; // @synthesize force_language=_force_language;
@property(copy, nonatomic) NSArray *gecko_hosts; // @synthesize gecko_hosts=_gecko_hosts;
- (_Bool)hasWebViewRenderConcurrentFunction;
@property(nonatomic) _Bool haveSending; // @synthesize haveSending=_haveSending;
@property(retain, nonatomic) NSDictionary *headersExt; // @synthesize headersExt=_headersExt;
@property(nonatomic) long long icon_show_time; // @synthesize icon_show_time=_icon_show_time;
- (id)init;
- (void)insertConfigureRitWith:(id)arg1;
@property(nonatomic) _Bool isGrey; // @synthesize isGrey=_isGrey;
@property(nonatomic) _Bool isReadVideoFromCache; // @synthesize isReadVideoFromCache=_isReadVideoFromCache;
@property(copy, nonatomic) NSArray *localNetworkIdList; // @synthesize localNetworkIdList=_localNetworkIdList;
@property(retain, nonatomic) BULogRateConfigModel *logRateConf; // @synthesize logRateConf=_logRateConf;
@property(nonatomic) long long max_tpl_cnts; // @synthesize max_tpl_cnts=_max_tpl_cnts;
- (id)modelWithRit:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *network_id_list; // @synthesize network_id_list=_network_id_list;
- (void)observeToleranceCrashNotification;
- (void)pbu_anchorFetchSetting;
- (_Bool)pbu_canFetchSetting;
- (id)pbu_requestParams;
- (void)pbu_resetFetchSetting;
@property(retain, nonatomic) NSArray *playableInterceptAry; // @synthesize playableInterceptAry=_playableInterceptAry;
@property(retain, nonatomic) NSDictionary *policy; // @synthesize policy=_policy;
@property(copy, nonatomic) NSString *privacy_url; // @synthesize privacy_url=_privacy_url;
@property(copy, nonatomic) NSString *purePyloadH5; // @synthesize purePyloadH5=_purePyloadH5;
- (void)receiveToleranceCrashNotification:(id)arg1;
@property(nonatomic) long long rotateBannerDislike; // @synthesize rotateBannerDislike=_rotateBannerDislike;
- (id)saveForceLanguageAndFetchNewLanguageWithLanguage:(id)arg1;
@property(copy, nonatomic) NSArray *scheme_wlist; // @synthesize scheme_wlist=_scheme_wlist;
@property(nonatomic) long long sdMaxMemoryCost; // @synthesize sdMaxMemoryCost=_sdMaxMemoryCost;
@property(nonatomic) long long sdMaxMemoryCount; // @synthesize sdMaxMemoryCount=_sdMaxMemoryCount;
@property(retain, nonatomic) NSDate *sendDate; // @synthesize sendDate=_sendDate;
- (void)setRitModelConfigList:(id)arg1;
@property(copy, nonatomic) NSDictionary *setting; // @synthesize setting=_setting;
@property(nonatomic) _Bool silenceSDK; // @synthesize silenceSDK=_silenceSDK;
@property(nonatomic) long long supportTNC; // @synthesize supportTNC=_supportTNC;
@property(retain, nonatomic) NSNumber *vbtt; // @synthesize vbtt=_vbtt;
@property(nonatomic) long long webViewPoolCacheMaxCount; // @synthesize webViewPoolCacheMaxCount=_webViewPoolCacheMaxCount;
@property(nonatomic) long long webViewRenderMaxConcurrentOperationCount; // @synthesize webViewRenderMaxConcurrentOperationCount=_webViewRenderMaxConcurrentOperationCount;
@property(copy, nonatomic) NSString *xpath; // @synthesize xpath=_xpath;
- (void)switchWithRequest:(id)arg1 settingString:(id)arg2;
- (void)updateNetworkIdListDefaultValue;
- (void)updateTime;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

