//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "BUCustomNavigationBarDelegate-Protocol.h"
#import "BUWebViewDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class BUAdSlot, BUCustomNavigationBarView, BUDislikeContext, BUMaterialMeta, BUURitSettingModel, BUVideoAdView, BUWebViewController, NSMutableDictionary, NSString, NSURL, SKStoreProductViewController, UIScrollView, UIView;
@protocol BUWebView;

@interface BUVideoDetailPageViewController : UIViewController <BUWebViewDelegate, SKStoreProductViewControllerDelegate, UIViewControllerTransitioningDelegate, UIScrollViewDelegate, BUCustomNavigationBarDelegate>
{
    _Bool _autoPlayIfVideoFromOut;
    _Bool _isNavigationBarHidden;
    _Bool _canAnchor;
    _Bool _canVideoRedisplay;
    _Bool _videoViewHidden;
    _Bool _showVideo;
    UIViewController *_rootViewController;
    BUAdSlot *_adSlot;
    double _playTimeIfVideo;
    double _totalPlayTimeIfVideo;
    CDUnknownBlockType _CloseBlock;
    SKStoreProductViewController *_storeProductViewController;
    NSString *_appid;
    BUMaterialMeta *_material;
    NSURL *_requestURL;
    long long _bottomType;
    BUVideoAdView *_videoAdView;
    BUCustomNavigationBarView *_navBgView;
    UIView<BUWebView> *_webView;
    double _playProgressForAnchor;
    UIScrollView *_scrollView;
    BUWebViewController *_webViewController;
    double _currentPlayTime;
    BUDislikeContext *_dislikeContext;
    BUURitSettingModel *_ritModel;
    NSMutableDictionary *_productionParameters;
    struct CGRect _webviewFrameWithoutVideo;
    struct CGRect _webviewFrameWithVideo;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType CloseBlock; // @synthesize CloseBlock=_CloseBlock;
- (void)_createWebViewControllerWithFrame:(struct CGRect)arg1;
- (void)_dealLandpageAnchor;
- (void)_reDisplayVideoView;
- (void)_reHideVideoView;
- (void)_updateParametersForSKAdNetwork:(id)arg1;
@property(retain, nonatomic) BUAdSlot *adSlot; // @synthesize adSlot=_adSlot;
- (void)addAccessibilityIdentifier;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(copy, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property(nonatomic) _Bool autoPlayIfVideoFromOut; // @synthesize autoPlayIfVideoFromOut=_autoPlayIfVideoFromOut;
@property(nonatomic) long long bottomType; // @synthesize bottomType=_bottomType;
- (void)buildUpView;
@property(nonatomic) _Bool canAnchor; // @synthesize canAnchor=_canAnchor;
@property(nonatomic) _Bool canVideoRedisplay; // @synthesize canVideoRedisplay=_canVideoRedisplay;
- (void)closeVideo;
- (void)closeVideoDetailView;
- (void)createAppStoreViewWithFrame:(struct CGRect)arg1;
- (void)createBottomView;
- (void)createNavBar;
- (void)createVideoView;
@property(nonatomic) double currentPlayTime; // @synthesize currentPlayTime=_currentPlayTime;
- (void)customNavigationBarDidClickBackButton:(id)arg1;
- (void)customNavigationBarDidClickCloseButton:(id)arg1;
- (void)customNavigationBarDidClickDislikeButton:(id)arg1;
@property(retain, nonatomic) BUDislikeContext *dislikeContext; // @synthesize dislikeContext=_dislikeContext;
- (void)downloadCloseOtherControllerHandler;
- (id)getCurrentRitModel;
- (void)goBack;
- (void)hideCloseButton;
- (id)initWithMaterial:(id)arg1;
@property(nonatomic) _Bool isNavigationBarHidden; // @synthesize isNavigationBarHidden=_isNavigationBarHidden;
@property(retain, nonatomic) BUMaterialMeta *material; // @synthesize material=_material;
@property(retain, nonatomic) BUCustomNavigationBarView *navBgView; // @synthesize navBgView=_navBgView;
@property(nonatomic) double playProgressForAnchor; // @synthesize playProgressForAnchor=_playProgressForAnchor;
@property(nonatomic) double playTimeIfVideo; // @synthesize playTimeIfVideo=_playTimeIfVideo;
- (void)productViewControllerDidFinish:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *productionParameters; // @synthesize productionParameters=_productionParameters;
@property(retain, nonatomic) NSURL *requestURL; // @synthesize requestURL=_requestURL;
@property(retain, nonatomic) BUURitSettingModel *ritModel; // @synthesize ritModel=_ritModel;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool showVideo; // @synthesize showVideo=_showVideo;
@property(retain, nonatomic) SKStoreProductViewController *storeProductViewController; // @synthesize storeProductViewController=_storeProductViewController;
@property(nonatomic) double totalPlayTimeIfVideo; // @synthesize totalPlayTimeIfVideo=_totalPlayTimeIfVideo;
@property(retain, nonatomic) BUVideoAdView *videoAdView; // @synthesize videoAdView=_videoAdView;
@property(nonatomic) _Bool videoViewHidden; // @synthesize videoViewHidden=_videoViewHidden;
@property(retain, nonatomic) UIView<BUWebView> *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) BUWebViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(nonatomic) struct CGRect webviewFrameWithVideo; // @synthesize webviewFrameWithVideo=_webviewFrameWithVideo;
@property(nonatomic) struct CGRect webviewFrameWithoutVideo; // @synthesize webviewFrameWithoutVideo=_webviewFrameWithoutVideo;
- (_Bool)shouldAutorotate;
- (void)showCloseButton;
- (void)showDislike;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

