//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUVideoAdReportor-Protocol.h"

@class BUMaterialMeta, BUVideoAdTracker, NSString;

@interface BUVideoAdReportor : NSObject <BUVideoAdReportor>
{
    NSString *_slotId;
    BUMaterialMeta *_materialMeta;
    long long _drawVideoType;
    double _duration;
    double _currentTimeStamp;
    BUVideoAdTracker *_videoTracker;
}

- (void).cxx_destruct;
@property(nonatomic) double currentTimeStamp; // @synthesize currentTimeStamp=_currentTimeStamp;
- (void)didAutoStartPlayWithVideoDuration:(double)arg1;
- (void)didBreakVideoWithCurrentDuration:(double)arg1;
- (void)didClickVideoViewWithCurrentDuration:(double)arg1;
- (void)didFinishVideo;
- (void)didPauseVideoWithCurrentDuration:(double)arg1;
- (void)didPlayBufferEnd;
- (void)didPlayBufferStart;
- (void)didPlayFailedWithError:(id)arg1;
- (void)didPlayStartFailedWithError:(id)arg1;
- (void)didResumeVideoWithCurrentDuration:(double)arg1;
- (void)didStartPlayVideoWithVideoDuration:(double)arg1;
@property(nonatomic) long long drawVideoType; // @synthesize drawVideoType=_drawVideoType;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (id)getAdExtraDataDict:(long long)arg1 duration:(double)arg2 watchedDuration:(double)arg3 error:(id)arg4;
- (id)initWithNativeAd:(id)arg1;
@property(retain, nonatomic) BUMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
- (void)reportLabel:(id)arg1 adExtraDataType:(long long)arg2 duration:(double)arg3 watchedDuration:(double)arg4 error:(id)arg5;
@property(copy, nonatomic) NSString *slotId; // @synthesize slotId=_slotId;
@property(retain, nonatomic) BUVideoAdTracker *videoTracker; // @synthesize videoTracker=_videoTracker;
- (void)startPlayVideo;
- (id)trackTag;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

