//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSMapTable, NSMutableArray, UIView;

@interface BUWebViewPoolManager : NSObject
{
    NSMapTable *_usedMapTable;
    NSMutableArray *_webViewArray;
    NSLock *_webViewArrayLock;
    UIView *_zeroView;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long availableCacheCount;
- (void)clearAll;
- (id)init;
- (long long)maxCount;
- (void)pbu_checkInMainWindow;
- (id)pbu_createWebViewClient;
- (id)pbu_keyFromWebViewClient:(id)arg1;
- (void)promote_webViewPriorityWithView:(id)arg1;
- (void)removeCacheWebViewClient:(id)arg1;
- (void)resume_webViewPriorityWithView:(id)arg1;
@property(retain, nonatomic) NSMapTable *usedMapTable; // @synthesize usedMapTable=_usedMapTable;
@property(retain, nonatomic) NSMutableArray *webViewArray; // @synthesize webViewArray=_webViewArray;
@property(retain, nonatomic) NSLock *webViewArrayLock; // @synthesize webViewArrayLock=_webViewArrayLock;
@property(retain, nonatomic) UIView *zeroView; // @synthesize zeroView=_zeroView;
- (id)usableWebViewOwnerWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) long long usedCount;
@property(readonly, nonatomic) long long webviewCount;

@end

