//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

#import "BUWebViewDynamicRenderDelegate-Protocol.h"

@class NSMutableArray, NSString;
@protocol BUWebViewDynamicRenderInterface;

@interface BUWebViewDynamicRenderOperation : NSOperation <BUWebViewDynamicRenderDelegate>
{
    _Bool _executing;
    _Bool _finished;
    _Bool _haveDone;
    id <BUWebViewDynamicRenderInterface> _implementation;
    long long _renderIndex;
    double _beginTime;
    double _endTime;
    NSMutableArray *_logFlowArray;
}

- (void).cxx_destruct;
@property(nonatomic) double beginTime; // @synthesize beginTime=_beginTime;
- (void)dealloc;
- (void)done_3501;
@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(nonatomic) _Bool haveDone; // @synthesize haveDone=_haveDone;
@property(retain, nonatomic) id <BUWebViewDynamicRenderInterface> implementation; // @synthesize implementation=_implementation;
- (id)initWithImplementation:(id)arg1;
- (_Bool)isConcurrent;
@property(nonatomic, getter=isExecuting) _Bool executing; // @synthesize executing=_executing;
@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(retain, nonatomic) NSMutableArray *logFlowArray; // @synthesize logFlowArray=_logFlowArray;
- (void)pbu_addFlowLogWithMsg:(id)arg1;
@property(nonatomic) long long renderIndex; // @synthesize renderIndex=_renderIndex;
- (void)start;
- (void)webViewDidRenderInImplementation:(id)arg1;
- (void)webViewWillRenderInImplementation:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

