//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUCustomNavigationBarDelegate-Protocol.h"
#import "BUWebViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"
#import "WKScriptMessageHandler-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class BUAdSlot, BUCustomNavigationBarView, BUDislikeContext, BUTimer, BUWKWebViewClient, BUWebViewProgressView, BUWebViewViewModel, NSDate, NSDictionary, NSError, NSMutableArray, NSString, NSURL, UIView, UIViewController;
@protocol BUAd;

@interface BUWebViewControllerViewModel : NSObject <BUCustomNavigationBarDelegate, WKScriptMessageHandler, UIViewControllerTransitioningDelegate, WKUIDelegate, BUWebViewDelegate>
{
    _Bool _isNavBarHidden;
    _Bool _isHiddenProgress;
    _Bool _supportAlert;
    _Bool _hasTerminateTrack;
    _Bool _observingHeartBeat;
    _Bool _hasEnterBackground;
    BUWKWebViewClient *_webView;
    id <BUAd> _adInfo;
    BUAdSlot *_adSlot;
    NSString *_webTitle;
    BUWebViewViewModel *_viewModel;
    CDUnknownBlockType _CloseBlock;
    NSURL *_requestURL;
    NSDictionary *_relatedMaterialMeta;
    NSString *_createExtraString;
    CDUnknownBlockType _hasLoadLubanListPage;
    unsigned long long _pageType;
    CDUnknownBlockType _downloadDidCloseStoreController;
    UIView *_view;
    UIViewController *_parentVC;
    BUDislikeContext *_dislikeContext;
    NSString *_stashCid;
    NSString *_stashLogExtra;
    long long _heartBeatOverTime;
    CDUnknownBlockType _heartBeatCallback;
    BUTimer *_heartBeatTimer;
    BUCustomNavigationBarView *_customNavigationView;
    BUWebViewProgressView *_progressView;
    struct CGSize _size;
}

+ (_Bool)supportPlayableSDKWithMaterial:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType CloseBlock; // @synthesize CloseBlock=_CloseBlock;
- (id)_renderDict;
@property(readonly, nonatomic) id <BUAd> adInfo; // @synthesize adInfo=_adInfo;
@property(retain, nonatomic) BUAdSlot *adSlot; // @synthesize adSlot=_adSlot;
- (void)addAccessibilityIdentifier;
- (void)addScriptMessageHandleForName:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)appDidEnterBackgroundNotification:(id)arg1;
- (void)appWillEnterForegroundNotification:(id)arg1;
@property(nonatomic) long long backgroundStatus;
- (id)buJSB3_adInfoStashWithViewModel:(id)arg1;
- (id)buJSB3_adInfoWithViewModel:(id)arg1;
- (id)buJSB3_click_buttonWithViewModel:(id)arg1;
- (id)buJSB3_closeWithViewModel:(id)arg1;
- (id)buJSB3_download_app_adWithViewModel:(id)arg1;
- (id)buJSB3_getATTStatusWithViewModel:(id)arg1;
- (id)buJSB3_getMaterialMetaWithViewModel:(id)arg1;
- (id)buJSB3_getNativeSiteCustomDataWithViewModel:(id)arg1;
- (id)buJSB3_getNetworkDataWithViewModel:(id)arg1;
- (id)buJSB3_getTeMaiAdsWithViewModel:(id)arg1;
- (id)buJSB3_heart_beatWithViewModel:(id)arg1;
- (id)buJSB3_openAdLandPageLinksWithViewModel:(id)arg1;
- (id)buJSB3_sendLogWithViewModel:(id)arg1;
- (id)buJSB3_send_temai_product_idsWithViewModel:(id)arg1;
- (id)buJSB3_updatePCMDataWithViewModel:(id)arg1;
- (void)bu_loadRequest:(id)arg1;
- (_Bool)bu_shouldStartLoadWithRequestWithURL:(id)arg1;
- (void)buildCustormNavigationViewFrame;
- (void)buildRelatedMaterialMeta;
- (void)buildWebviewFrame;
- (void)cancelObserveHeartBeat;
- (void)configLubanInfoWithURL:(id)arg1;
- (void)creatNavigationItems;
@property(copy, nonatomic) NSString *createExtraString; // @synthesize createExtraString=_createExtraString;
- (void)createWebView;
@property(nonatomic) long long currentStatus;
- (void)customNavigationBarDidClickBackButton:(id)arg1;
- (void)customNavigationBarDidClickCloseButton:(id)arg1;
- (void)customNavigationBarDidClickDislikeButton:(id)arg1;
@property(retain, nonatomic) BUCustomNavigationBarView *customNavigationView; // @synthesize customNavigationView=_customNavigationView;
- (void)dealloc;
- (void)dislikeButtonTapped:(id)arg1;
@property(retain, nonatomic) BUDislikeContext *dislikeContext; // @synthesize dislikeContext=_dislikeContext;
@property(copy, nonatomic) CDUnknownBlockType downloadDidCloseStoreController; // @synthesize downloadDidCloseStoreController=_downloadDidCloseStoreController;
- (id)durationFromEnterForegroundDate;
- (id)durationFromFinishDate;
- (id)durationFromFinishShowDate;
- (id)durationFromStartDate;
- (id)enterForegrounddate;
- (id)fetchHookConsoleLog;
- (id)finishdate;
- (_Bool)getOfflineSwitch;
- (id)getTrackTag;
- (void)goClose;
- (void)goClose:(id)arg1;
- (void)goback:(id)arg1;
- (void)handleDidReceiveMemoryWarning;
- (void)handleError:(id)arg1;
- (void)handleFinishLoad;
- (_Bool)handleScrollPercentWith:(id)arg1;
- (void)handleStartLoad;
- (void)handleTapWithInfo:(id)arg1;
- (_Bool)handleTaptWith:(id)arg1;
- (void)handleViewDidAppear:(_Bool)arg1;
- (void)handleViewDidDisappear:(_Bool)arg1;
- (void)handleViewDidLoad;
- (void)handleViewWillAppear:(_Bool)arg1;
- (void)handleViewWillDisappear:(_Bool)arg1;
- (void)handleViewWillLayoutSubviews;
@property(nonatomic) _Bool hasEnterBackground; // @synthesize hasEnterBackground=_hasEnterBackground;
@property(copy, nonatomic) CDUnknownBlockType hasLoadLubanListPage; // @synthesize hasLoadLubanListPage=_hasLoadLubanListPage;
@property(nonatomic) _Bool hasTerminateTrack; // @synthesize hasTerminateTrack=_hasTerminateTrack;
@property(copy, nonatomic) CDUnknownBlockType heartBeatCallback; // @synthesize heartBeatCallback=_heartBeatCallback;
@property(nonatomic) long long heartBeatOverTime; // @synthesize heartBeatOverTime=_heartBeatOverTime;
@property(retain, nonatomic) BUTimer *heartBeatTimer; // @synthesize heartBeatTimer=_heartBeatTimer;
- (void)hiddenCloseButton;
- (id)initWithRequestURL:(id)arg1 adinfo:(id)arg2 size:(struct CGSize)arg3 isNavBarHidden:(_Bool)arg4;
@property(nonatomic) _Bool isFirstLoad_start;
@property(nonatomic) _Bool isHiddenProgress; // @synthesize isHiddenProgress=_isHiddenProgress;
@property(nonatomic) _Bool isLuban;
@property(nonatomic) _Bool isNavBarHidden; // @synthesize isNavBarHidden=_isNavBarHidden;
- (_Bool)isRealPlayablePage;
@property(nonatomic, getter=isSupportAlert) _Bool supportAlert; // @synthesize supportAlert=_supportAlert;
@property(nonatomic) _Bool isTrackLoad_Finish;
@property(nonatomic) _Bool isTrackLoad_result;
- (id)jsCallNative_adInfo;
- (void)jsCallNative_click_button;
- (void)jsCallNative_close;
- (id)jsCallNative_download_app_ad;
- (id)jsCallNative_getMaterialMeta;
- (id)jsCallNative_getNativeSiteCustomData;
- (id)jsCallNative_getTeMaiAds;
- (void)jsCallNative_openAdLandPageLinksWithParams:(id)arg1;
- (void)jsCallNative_sendLogWithParams:(id)arg1;
- (void)jsCallNative_send_temai_product_idsWithParams:(id)arg1;
@property(nonatomic) long long js_max_scroll_percent;
@property(retain, nonatomic) NSError *loadFailError;
@property(copy, nonatomic) CDUnknownBlockType loadLubanJsonFail;
@property(copy, nonatomic) NSDictionary *luban_json;
@property(retain, nonatomic) NSMutableArray *luban_product_ids;
- (void)observeHeartBeatWithOverTime:(long long)arg1 callback:(CDUnknownBlockType)arg2;
@property(nonatomic) _Bool observingHeartBeat; // @synthesize observingHeartBeat=_observingHeartBeat;
- (void)onHeartBeatTimerOut;
- (void)openInternalStore;
- (void)openWebViewNewPageWithUrl:(id)arg1;
- (id)origUA;
@property(nonatomic) unsigned long long pageType; // @synthesize pageType=_pageType;
@property(nonatomic) __weak UIViewController *parentVC; // @synthesize parentVC=_parentVC;
- (id)pbu_urlWithString:(id)arg1;
- (void)preloadEvent;
- (void)preloadLubanData;
- (void)preloadWebViewAndData;
@property(retain, nonatomic) BUWebViewProgressView *progressView; // @synthesize progressView=_progressView;
- (void)receiveH5HeartBeat:(id)arg1;
- (void)registJS_ScrollPercent;
- (void)registJS_Tap;
- (void)registShowConsole;
- (void)registerJSBridge3;
- (void)registerJSBridgePlugin;
- (void)registerLubanJSBridgePlugin;
- (void)registerUserAgent;
@property(retain, nonatomic) NSDictionary *relatedMaterialMeta; // @synthesize relatedMaterialMeta=_relatedMaterialMeta;
@property(retain, nonatomic) NSURL *requestURL; // @synthesize requestURL=_requestURL;
- (void)responseViewClick:(struct BUWebViewClickStruct)arg1;
- (void)responseViewDidScroll:(struct BUWebViewClickStruct)arg1 offset:(struct CGPoint)arg2;
- (id)sdkUA;
- (void)sendTrackDataWithParameters:(id)arg1;
- (void)setEnterForegrounddate:(id)arg1;
- (void)setFinishdate:(id)arg1;
- (void)setShowdate:(id)arg1;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) NSDate *startdate;
@property(copy, nonatomic) NSString *stashCid; // @synthesize stashCid=_stashCid;
@property(copy, nonatomic) NSString *stashLogExtra; // @synthesize stashLogExtra=_stashLogExtra;
@property(nonatomic) __weak UIView *view; // @synthesize view=_view;
@property(retain, nonatomic) BUWebViewViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(copy, nonatomic) NSString *webTitle; // @synthesize webTitle=_webTitle;
@property(retain, nonatomic) BUWKWebViewClient *webView; // @synthesize webView=_webView;
- (_Bool)shouldTrack;
- (void)showCloseButton;
- (id)showdate;
- (void)startNewHeartBeatTime;
- (void)stopHeartBeatTime;
- (void)trackCloseWith:(long long)arg1 tag:(id)arg2;
- (void)trackEnterForeground;
- (void)trackLoadFailWithError:(id)arg1 tag:(id)arg2;
- (void)trackLoadFinishWithTag:(id)arg1;
- (void)trackLoadStartWith:(long long)arg1 tag:(id)arg2;
- (void)trackLoading;
- (void)trackOpenWithTag:(id)arg1;
- (void)trackShow;
- (void)trackStayWithTag:(id)arg1;
- (id)trackTag;
- (void)updatePCMData:(id)arg1;
- (_Bool)useCache;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (id)webClickTrack;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (double)webview_y;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

