//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface EncryptString : NSObject
{
}

- (id)GDTAntiPodd1fUNm:(id)arg1;
- (id)GDTAntiPodd8wY1v:(id)arg1 withSeed:(long long)arg2 withContent:(id)arg3;
- (int)GDTAntiPodh8TAtv;
- (unsigned char)GDTAntiPodi4xGpU;
- (id)GDTAntiPodl35wbE:(id)arg1 seed:(long long)arg2 nativeData:(id)arg3;
- (id)GDTAntiPodo1m5st:(id)arg1 seed:(long long)arg2 encryptData:(id)arg3;
- (id)GDTAntiPodp4XY5Z:(id)arg1;
- (int)GDTAntiPodp6IaxO;
- (unsigned char)GDTAntiPodq3Vv8k;
- (unsigned char)GDTAntiPodq8QaPb;
- (id)GDTAntiPodu6dL9O:(id)arg1 withSeed:(long long)arg2 withContent:(id)arg3;
- (unsigned char)GDTAntiPodv9nH3O;
- (int)GDTAntiPody1EEP2;
- (int)X__GDT__GDTAntiPod;
- (id)base64StringWithData:(id)arg1;
- (id)contentWithMuid:(id)arg1 seed:(long long)arg2 encryptData:(id)arg3;
- (id)encryptDataWithBase64String:(id)arg1;
- (id)encryptWithMuid:(id)arg1 withSeed:(long long)arg2 withContent:(id)arg3;

@end

