//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSError, NSString;

@interface GADAdNetworkResponseInfo : NSObject
{
    NSString *_adNetworkClassName;
    NSDictionary *_credentials;
    NSDictionary *_adUnitMapping;
    NSError *_error;
    double _latency;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *adNetworkClassName;
@property(retain, nonatomic) NSDictionary *adUnitMapping;
@property(retain, nonatomic) NSDictionary *credentials;
- (id)description;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
@property(retain, nonatomic) NSError *error;
@property(nonatomic) double latency;

@end

