//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVAssetResourceLoaderDelegate-Protocol.h"
#import "GADAVPlayerItemProvider-Protocol.h"

@class AVAssetResourceLoadingRequest, AVPlayerItem, GADKeyValueObserverController, GADResourceBuffer, GADVideoAssetLoader, GADVideoConfiguration, GADVideoPlayer, NSString, NSTimer, NSURL;
@protocol OS_dispatch_queue;

@interface GADAssetLoadingVideoPlayerItem : NSObject <GADAVPlayerItemProvider, AVAssetResourceLoaderDelegate>
{
    NSURL *_videoURL;
    GADVideoAssetLoader *_assetLoader;
    GADVideoConfiguration *_videoConfiguration;
    AVPlayerItem *_playerItem;
    NSTimer *_playerItemCheckSourceTimer;
    _Bool _loadingEnabled;
    AVAssetResourceLoadingRequest *_loadingRequest;
    GADResourceBuffer *_resourceBuffer;
    long long _resourceBufferStartingByteOffset;
    GADVideoPlayer *_player;
    id _playbackProgressObserver;
    float _videoBitRateInBitsPerSecond;
    double _playerItemCachingStartTimeInterval;
    double _playerItemCurrentTimeInterval;
    long long _loadedContentSizeWithNoBufferUpdate;
    long long _numberOfFailedResourceBuffer;
    NSObject<OS_dispatch_queue> *_lockQueue;
    GADKeyValueObserverController *_keyValueObserverController;
    _Bool _gcacheUsed;
    _Bool _gcacheHit;
    _Bool _gcacheDownloaded;
    long long _cachedBytes;
}

- (void).cxx_destruct;
@property(readonly) NSString *MIMEType;
@property(readonly, nonatomic) long long cachedBytes; // @synthesize cachedBytes=_cachedBytes;
- (void)dealloc;
@property(readonly, nonatomic) _Bool gcacheDownloaded; // @synthesize gcacheDownloaded=_gcacheDownloaded;
@property(readonly, nonatomic) _Bool gcacheHit; // @synthesize gcacheHit=_gcacheHit;
@property(readonly, nonatomic) _Bool gcacheUsed; // @synthesize gcacheUsed=_gcacheUsed;
- (void)handlePlayerItemUpdates;
- (id)initWithVideoURL:(id)arg1 assetLoader:(id)arg2 videoConfiguration:(id)arg3 gcacheUsed:(_Bool)arg4 gcacheHit:(_Bool)arg5;
- (_Bool)loadContentRequest:(id)arg1 withError:(id *)arg2;
- (_Bool)loadDataRequest:(id)arg1 withError:(id *)arg2;
- (void)loadPlayerItemData;
@property(readonly, nonatomic) long long loadedBytes;
- (id)playerItem;
- (_Bool)prepareForLoadingByteOffset:(long long)arg1;
- (void)processLoadingRequest;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
- (void)setPlayer:(id)arg1;
- (void)startPlayerItemCheckSourceTimer;
- (void)stopPlayerItemCheckSourceTimer;
@property(readonly, nonatomic) long long totalBytes;
- (id)videoURL;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

