//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface GADAdCache : NSObject
{
    NSMutableDictionary *_pools;
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSString *_cacheKeySignals;
}

- (void).cxx_destruct;
- (void)addServerTransaction:(id)arg1 forKey:(id)arg2;
- (id)entryForRequestID:(id)arg1 key:(id)arg2;
- (void)evictPoolForKey:(id)arg1;
- (id)initWithCacheKeySignals:(id)arg1;
- (void)removeRenderedAd:(id)arg1 configurationKey:(id)arg2;
- (void)removeServerTransactionForRequestID:(id)arg1 poolKey:(id)arg2;
- (id)serverTransactionEntryForKey:(id)arg1;

@end

