//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GADInternalNativeAd, GADVideoController, UIImage;
@protocol GADMediaContentDisplaying;

@interface GADMediaContent : NSObject
{
    UIImage *_mainImage;
    id <GADMediaContentDisplaying> _internalMediaContent;
    GADVideoController *_videoController;
    GADInternalNativeAd *_internalCustomNativeAd;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double aspectRatio;
@property(readonly, nonatomic) double currentTime;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) _Bool hasVideoContent;
@property(nonatomic) __weak GADInternalNativeAd *internalCustomNativeAd; // @synthesize internalCustomNativeAd=_internalCustomNativeAd;
@property(retain, nonatomic) id <GADMediaContentDisplaying> internalMediaContent; // @synthesize internalMediaContent=_internalMediaContent;
- (id)mainImage;
- (void)setMainImage:(id)arg1;
@property(readonly, nonatomic) GADVideoController *videoController; // @synthesize videoController=_videoController;

@end

