//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDT_GCDAsyncSocketPreBuffer : NSObject
{
    char *preBuffer;
    unsigned long long preBufferSize;
    char *readPointer;
    char *writePointer;
}

- (void)GDTfunctiond54hh4:(unsigned long long)arg1;
- (unsigned long long)GDTfunctioni2VjFM;
- (void)GDTfunctionl4C7IP:(char **)arg1 GDTfunctionz6HAJb:(unsigned long long *)arg2;
- (void)GDTfunctionm784nm:(unsigned long long)arg1;
- (char *)GDTfunctiono5xyrP;
- (void)GDTfunctionq8zGnG:(char **)arg1 GDTfunctioni2VjFM:(unsigned long long *)arg2;
- (char *)GDTfunctionw8pCvu;
- (unsigned long long)GDTfunctionz6HAJb;
- (void)GDTfunctionz6VTBS:(unsigned long long)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCapacity:(unsigned long long)arg1;
- (void)reset;

@end

