//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

@interface GDTAntiSpam : NSObject
{
    _Bool _closeBtnDisplayed;
    _Bool _needP;
    int _xo;
    int _yo;
    long long _playBeginTime;
    long long _aa;
    long long _ab;
    long long _ba;
    long long _bb;
    long long _g;
    long long _ec;
    long long _sc;
    NSString *_d;
    NSString *_f;
    NSString *_sz;
    NSString *_dd;
    long long _p;
    NSString *_x;
    long long _preClickTime;
    long long _postClickTime;
    double _tp;
    double _ts;
    double _dp;
    long long _dx;
    long long _dy;
    long long _pw;
    long long _ph;
    long long _ra;
    long long _rb;
    long long _da;
    long long _db;
    NSString *_tid;
    long long _dataType;
    long long _clickArea;
    long long _vp;
    double _vs;
    double _dpn;
    long long _sg;
    NSString *_td;
    NSString *_sld;
    NSSet *_otherParams;
}

+ (id)addPParamToExposureUrl:(id)arg1 currentViewFrame:(struct CGRect)arg2 rootViewFrame:(struct CGRect)arg3 antiSpamClickData:(id)arg4 baseUrl:(id)arg5 needP:(_Bool)arg6 dataType:(long long)arg7;
+ (id)addParamToBaseUrlString:(id)arg1 withKeyString:(id)arg2 valueString:(id)arg3;
+ (id)antiSpamParamWithTemplateId:(id)arg1 isCloseBtnDisplayed:(_Bool)arg2 playBeginTime:(long long)arg3;
+ (long long)currentTime;
+ (id)encodeURL:(id)arg1;
+ (id)exposureUrlWithAntiSpamClickData:(id)arg1 baseUrl:(id)arg2 needP:(_Bool)arg3;
+ (struct CGRect)getAdToScreenWithView:(id)arg1 frame:(struct CGRect)arg2;
+ (struct CGSize)getAdValidateAreaWithView:(id)arg1 frameA:(struct CGRect)arg2 frameB:(struct CGRect)arg3;
+ (id)jsonStringFromObject:(id)arg1;
+ (id)mid;
+ (id)pParamsPlaintextWithString:(id)arg1;
+ (id)urlParamForAntiSpamWithTemplateId:(id)arg1 antiSpamClickData:(id)arg2 isCloseBtnDisplayed:(_Bool)arg3 playBeginTime:(long long)arg4 dataType:(long long)arg5;
- (void).cxx_destruct;
- (id)GDTAntiPodb0d1H4:(id)arg1;
- (void)GDTAntiPodc5Lcdu:(id)arg1;
- (id)GDTAntiPodf9zpKB;
- (void)GDTAntiPodg3apP6:(id)arg1;
- (id)GDTAntiPodj9Nmig;
- (id)GDTAntiPodn5uSDD;
- (id)GDTAntiPodp31Mvx:(id)arg1;
- (id)GDTAntiPodp7zlJF:(id)arg1;
- (id)GDTAntiPods0RskV;
- (id)GDTAntiPodu4jIFx:(id)arg1;
- (id)GDTAntiPodu7HEAC:(id)arg1;
- (id)GDTAntiPodx3pJMn;
- (void)GDTAntiPody4ACgs:(id)arg1;
@property(nonatomic) long long aa; // @synthesize aa=_aa;
@property(nonatomic) long long ab; // @synthesize ab=_ab;
@property(nonatomic) long long ba; // @synthesize ba=_ba;
@property(nonatomic) long long bb; // @synthesize bb=_bb;
@property(nonatomic) long long clickArea; // @synthesize clickArea=_clickArea;
@property(nonatomic) _Bool closeBtnDisplayed; // @synthesize closeBtnDisplayed=_closeBtnDisplayed;
@property(copy, nonatomic) NSString *d; // @synthesize d=_d;
@property(nonatomic) long long da; // @synthesize da=_da;
@property(nonatomic) long long dataType; // @synthesize dataType=_dataType;
@property(nonatomic) long long db; // @synthesize db=_db;
@property(copy, nonatomic) NSString *dd; // @synthesize dd=_dd;
@property(nonatomic) double dp; // @synthesize dp=_dp;
@property(nonatomic) double dpn; // @synthesize dpn=_dpn;
@property(nonatomic) long long dx; // @synthesize dx=_dx;
@property(nonatomic) long long dy; // @synthesize dy=_dy;
@property(nonatomic) long long ec; // @synthesize ec=_ec;
@property(copy, nonatomic) NSString *f; // @synthesize f=_f;
@property(nonatomic) long long g; // @synthesize g=_g;
- (id)init;
@property(nonatomic) _Bool needP; // @synthesize needP=_needP;
@property(copy, nonatomic) NSSet *otherParams; // @synthesize otherParams=_otherParams;
@property(nonatomic) long long p; // @synthesize p=_p;
- (id)pParamClickUrlWithBaseClickUrl:(id)arg1;
- (id)pParamEncryptedString;
- (id)pParamWithClickData:(id)arg1;
@property(nonatomic) long long ph; // @synthesize ph=_ph;
@property(nonatomic) long long playBeginTime; // @synthesize playBeginTime=_playBeginTime;
@property(nonatomic) long long postClickTime; // @synthesize postClickTime=_postClickTime;
@property(nonatomic) long long preClickTime; // @synthesize preClickTime=_preClickTime;
@property(nonatomic) long long pw; // @synthesize pw=_pw;
@property(nonatomic) long long ra; // @synthesize ra=_ra;
@property(nonatomic) long long rb; // @synthesize rb=_rb;
@property(nonatomic) long long sc; // @synthesize sc=_sc;
@property(nonatomic) long long sg; // @synthesize sg=_sg;
@property(copy, nonatomic) NSString *sld; // @synthesize sld=_sld;
@property(copy, nonatomic) NSString *sz; // @synthesize sz=_sz;
@property(copy, nonatomic) NSString *td; // @synthesize td=_td;
@property(copy, nonatomic) NSString *tid; // @synthesize tid=_tid;
@property(nonatomic) double tp; // @synthesize tp=_tp;
@property(nonatomic) double ts; // @synthesize ts=_ts;
@property(nonatomic) long long vp; // @synthesize vp=_vp;
@property(nonatomic) double vs; // @synthesize vs=_vs;
@property(copy, nonatomic) NSString *x; // @synthesize x=_x;
@property(nonatomic) int xo; // @synthesize xo=_xo;
@property(nonatomic) int yo; // @synthesize yo=_yo;
- (id)spamSParamClickUrlWithBaseClickUrl:(id)arg1 antiSpamClickData:(id)arg2 antiSpamDictFromH5:(id)arg3;

@end

