//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDTAntispamFacade : NSObject
{
}

+ (id)antispamExposeUrlWithAdType:(long long)arg1 adView:(id)arg2 referenceView:(id)arg3 exposeUrl:(id)arg4 businessData:(id)arg5;
+ (id)channelParam;
+ (id)clickUrlWithAdType:(long long)arg1 baseClickUrl:(id)arg2 antiSpamData:(id)arg3 playBeginTime:(long long)arg4 templateId:(id)arg5 businessData:(id)arg6;
+ (id)clickUrlWithAdType:(long long)arg1 baseClickUrl:(id)arg2 antiSpamFromH5:(id)arg3 baseView:(id)arg4 currentFrame:(struct CGRect)arg5 rootViewFrame:(struct CGRect)arg6 clickArea:(long long)arg7 adViewType:(long long)arg8 videoPlayedTime:(long long)arg9 businessData:(id)arg10;
+ (id)createRewardParam:(_Bool)arg1;
+ (id)createSZParamsWithAdType:(long long)arg1;
+ (id)createShakeAccelerationParam:(id)arg1;
+ (id)createSlideParamWithAdType:(long long)arg1 interactiveMode:(long long)arg2;
+ (id)deviceParams;
+ (id)ifaParam;
+ (id)inForgroundParam;
+ (id)pkgParam;
+ (id)preloadSignParam:(_Bool)arg1;
+ (id)simulatorParam;
+ (id)taidParam;

@end

