//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTClickFacadeDelegate-Protocol.h"
#import "GDTHandlerContextProtocol-Protocol.h"
#import "GDTVideoStoreViewControllerDelegate-Protocol.h"
#import "GDTWebViewDelegate-Protocol.h"

@class GDTAdWKWebView, GDTClickFacade, NSString, UIViewController;

@interface GDTAdWebViewClient : NSObject <GDTHandlerContextProtocol, GDTClickFacadeDelegate, GDTWebViewDelegate, GDTVideoStoreViewControllerDelegate>
{
    UIViewController *_rootViewController;
    GDTAdWKWebView *_webView;
    GDTClickFacade *_clickFacade;
    long long _webViewKilledRetryCnt;
}

- (void).cxx_destruct;
- (void)GDTfunctionb3lP7O;
- (void)GDTfunctionh41Rgz;
- (_Bool)GDTfunctioni0vhEA:(id)arg1;
- (void)GDTfunctioni2zlKg:(id)arg1;
- (void)GDTfunctionl1mmJB;
- (void)GDTfunctionl4XGke:(id)arg1 didLoadFailWithError:(id)arg2;
- (void)GDTfunctionl6ZBlY;
- (void)GDTfunctionm55QS3:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)GDTfunctionq3ZTze:(id)arg1;
- (void)GDTfunctionq6zszL;
- (void)GDTfunctiony3HbPY:(id)arg1;
@property(retain, nonatomic) GDTClickFacade *clickFacade; // @synthesize clickFacade=_clickFacade;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) __weak GDTAdWKWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) long long webViewKilledRetryCnt; // @synthesize webViewKilledRetryCnt=_webViewKilledRetryCnt;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

