//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTAdContentViewCheckerDelegate-Protocol.h"
#import "GDTVideoPlayerViewDelegate-Protocol.h"

@class GDTAdBaseModel, GDTCommandInvoker, GDTVideoEndCardView, GDTVideoPlayProgressReporter, GDTVideoPlayerView, NSString, UIViewController;
@protocol GDTBizVideoPlayerViewDelegate><GDTVideoStoreViewControllerDelegate;

@interface GDTBizFeedVideoPlayerView : UIView <GDTVideoPlayerViewDelegate, GDTAdContentViewCheckerDelegate>
{
    _Bool _hiddenLogoButton;
    _Bool _detailPageVideoMuted;
    _Bool _hasShownEndcard;
    _Bool _hasDirectVideoTypeExposed;
    GDTAdBaseModel *_adBizBaseModel;
    UIViewController *_viewController;
    id <GDTBizVideoPlayerViewDelegate><GDTVideoStoreViewControllerDelegate> _delegate;
    GDTVideoPlayerView *_videoPlayerView;
    GDTVideoPlayProgressReporter *_playProgressReporter;
    CDUnknownBlockType _endCardBodyClickedCallback;
    long long _playBeginTime;
    GDTCommandInvoker *_commandInvoker;
    long long _sdkAdType;
    GDTVideoEndCardView *_endcardView;
}

- (void).cxx_destruct;
- (void)GDTfunctionb9dpC4;
- (void)GDTfunctionf3prAp:(unsigned long long)arg1 duration:(long long)arg2;
- (_Bool)GDTfunctionj4ecZs;
- (void)GDTfunctionm760MR;
- (void)GDTfunctionm8WqpP;
- (long long)GDTfunctionn9BWFR;
- (_Bool)GDTfunctiono2pKq7;
- (void)GDTfunctionp8sQtf;
- (void)GDTfunctionq1dSJD;
- (void)GDTfunctionr9JWSj;
- (void)GDTfunctions78mON:(id)arg1 shouldMute:(_Bool)arg2;
- (void)GDTfunctiont6DgtJ;
- (void)GDTfunctiont7MBeN;
- (_Bool)GDTfunctionu2TL4w;
- (void)GDTfunctionv0xr8G;
- (void)GDTfunctionv3J29O;
- (void)GDTfunctionv3UWvl;
- (void)GDTfunctionx8HJ4G;
@property(readonly, nonatomic) unsigned long long GDTfunctionz2gCI4;
- (void)GDTfunctionz6Re37;
@property(retain, nonatomic) GDTAdBaseModel *adBizBaseModel; // @synthesize adBizBaseModel=_adBizBaseModel;
- (void)autoPlay;
@property(retain, nonatomic) GDTCommandInvoker *commandInvoker; // @synthesize commandInvoker=_commandInvoker;
- (void)dealloc;
@property(nonatomic) __weak id <GDTBizVideoPlayerViewDelegate><GDTVideoStoreViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool detailPageVideoMuted; // @synthesize detailPageVideoMuted=_detailPageVideoMuted;
@property(copy, nonatomic) CDUnknownBlockType endCardBodyClickedCallback; // @synthesize endCardBodyClickedCallback=_endCardBodyClickedCallback;
@property(retain, nonatomic) GDTVideoEndCardView *endcardView; // @synthesize endcardView=_endcardView;
@property(nonatomic) _Bool hasDirectVideoTypeExposed; // @synthesize hasDirectVideoTypeExposed=_hasDirectVideoTypeExposed;
@property(nonatomic) _Bool hasShownEndcard; // @synthesize hasShownEndcard=_hasShownEndcard;
@property(nonatomic) _Bool hiddenLogoButton; // @synthesize hiddenLogoButton=_hiddenLogoButton;
- (void)initLc5ua1P:(double)arg1 height:(double)arg2;
- (void)initLg1L2Cs;
- (void)initLj6q114;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithSize:(struct CGSize)arg1 adBizBaseModel:(id)arg2 viewController:(id)arg3;
- (void)pause;
- (void)play;
@property(nonatomic) long long playBeginTime; // @synthesize playBeginTime=_playBeginTime;
@property(retain, nonatomic) GDTVideoPlayProgressReporter *playProgressReporter; // @synthesize playProgressReporter=_playProgressReporter;
@property(readonly, nonatomic) unsigned long long playState;
@property(nonatomic) long long sdkAdType; // @synthesize sdkAdType=_sdkAdType;
- (void)setAssetURL:(id)arg1;
- (void)setCoverImageUrlString:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setPlayButtonImage:(id)arg1 size:(struct CGSize)arg2;
@property(nonatomic) _Bool videoMuted;
@property(retain, nonatomic) GDTVideoPlayerView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (void)stop;
@property(readonly, nonatomic) double videoDuration;
@property(readonly, nonatomic) double videoPlayTime;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

