//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTBottomCardAppearance-Protocol.h"

@class GDTAdBaseModel, NSString, UIButton, UIImageView, UILabel;

@interface GDTBottomCardView : UIView <GDTBottomCardAppearance>
{
    UIImageView *_iconImageView;
    UIImageView *_logoImageView;
    UILabel *_adTitleLabel;
    UILabel *_descLabel;
    UIButton *_downloadButton;
    GDTAdBaseModel *_adModel;
}

- (void).cxx_destruct;
- (id)GDTfunctiona8gG5I;
- (void)GDTfunctionl2zkMJ;
- (void)GDTfunctionl6fJpB;
- (void)GDTfunctionz47mOp;
@property(retain, nonatomic) GDTAdBaseModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) UILabel *adTitleLabel; // @synthesize adTitleLabel=_adTitleLabel;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (id)initLb48sas:(id)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

