//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTExtensionView.h"

@class UIColor;

@interface GDTBorderView : GDTExtensionView
{
    UIColor *_borderColor;
    double _borderWidth;
}

+ (Class)layerClass;
- (void).cxx_destruct;
- (void)GDTfunctiono2BWVn;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)shapeLayer;

@end

