//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDT_GCDAsyncSocketDelegate-Protocol.h"

@class GDT_GCDAsyncSocket, NSString;

@interface GDTCellularNetworkRequester : NSObject <GDT_GCDAsyncSocketDelegate>
{
    _Bool _SECURE_CONNECTION;
    long long _timeoutInterval;
    NSString *_url;
    NSString *_host;
    NSString *_path;
    NSString *_paramStr;
    CDUnknownBlockType _completion;
    GDT_GCDAsyncSocket *_asyncSocket;
}

+ (id)requesterWithURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (void)GDTfunctiond18Bsx:(id)arg1 withError:(id)arg2;
- (id)GDTfunctionh0kHic:(id)arg1;
- (void)GDTfunctionh3G6GZ;
- (void)GDTfunctionw8bP8S:(id)arg1;
@property(nonatomic) _Bool SECURE_CONNECTION; // @synthesize SECURE_CONNECTION=_SECURE_CONNECTION;
@property(retain, nonatomic) GDT_GCDAsyncSocket *asyncSocket; // @synthesize asyncSocket=_asyncSocket;
- (void)cancel;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void)dealloc;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
@property(copy, nonatomic) NSString *paramStr; // @synthesize paramStr=_paramStr;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(nonatomic) long long timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)socket:(id)arg1 didReceiveTrust:(struct __SecTrust *)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)socket:(id)arg1 didWriteDataWithTag:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

