//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBaseFullScreenViewController.h"

#import "GDTAdViewExposureWithAntiSpamCheckerDelegate-Protocol.h"
#import "GDTClickFacadeDelegate-Protocol.h"

@class GDTAdViewExposureWithAntiSpamChecker, NSString, UIView;
@protocol GDTVideoEndcardAppearanceProtocol;

@interface GDTCustomFullScreenViewController : GDTBaseFullScreenViewController <GDTAdViewExposureWithAntiSpamCheckerDelegate, GDTClickFacadeDelegate>
{
    UIView<GDTVideoEndcardAppearanceProtocol> *_endcardView;
    GDTAdViewExposureWithAntiSpamChecker *_viewExposureChecker;
}

- (void).cxx_destruct;
- (void)GDTfunctionb3lP7O;
- (void)GDTfunctionc2mpUP;
- (void)GDTfunctiond7aCvd;
- (void)GDTfunctiond8sXPG:(id)arg1 clickArea:(long long)arg2;
- (void)GDTfunctiond8wmDv;
- (void)GDTfunctionf2D3iT;
- (void)GDTfunctionf5JNbh:(id)arg1;
- (void)GDTfunctionh41Rgz;
- (void)GDTfunctionj6iGCN;
- (void)GDTfunctionj6jg41;
- (void)GDTfunctionk2T4g2;
- (void)GDTfunctionk68ynC:(id)arg1;
- (void)GDTfunctionl1mmJB;
- (void)GDTfunctionl5Xwnp;
- (void)GDTfunctionl6ZBlY;
- (void)GDTfunctionp2v63S;
- (void)GDTfunctionp4GmvA;
- (void)GDTfunctionq6zszL;
- (void)GDTfunctionr0HyKf:(id)arg1;
- (void)GDTfunctionr6vzIE;
- (void)GDTfunctiont3q2Bx;
- (void)GDTfunctiont6E5tT;
- (void)GDTfunctiont7MBeN;
- (void)GDTfunctionx5c2i9;
- (void)GDTfunctiony1Udc1;
- (void)dealloc;
- (id)endcardView;
- (void)setEndcardView:(id)arg1;
@property(retain, nonatomic) GDTAdViewExposureWithAntiSpamChecker *viewExposureChecker; // @synthesize viewExposureChecker=_viewExposureChecker;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

