//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CALayer, NSMutableArray, NSMutableDictionary, NSString, UIView;

@interface GDTDLViewNode : NSObject
{
    _Bool _hidden;
    _Bool _updatingNeedsResize;
    GDTDLViewNode *_superNode;
    NSMutableArray *_subNodes;
    NSString *_templateType;
    NSString *_className;
    UIView *_cocoaView;
    CALayer *_rootCanvasLayer;
    UIView *_rootCocoaView;
    double _layoutX;
    double _layoutY;
    double _layoutWidth;
    double _layoutHeight;
    unsigned long long _layoutGravity;
    double _layoutPaddingTop;
    double _layoutPaddingLeft;
    double _layoutPaddingBottom;
    double _layoutPaddingRight;
    double _layoutMarginTop;
    double _layoutMarginLeft;
    double _layoutMarginBottom;
    double _layoutMarginRight;
    unsigned long long _visibility;
    double _nodeX;
    double _nodeY;
    double _nodeWidth;
    double _nodeHeight;
    unsigned long long _layoutInsetsPaddingFromSafeArea;
    NSMutableDictionary *_runtimeProperties;
    NSMutableDictionary *_dynamicProperties;
    unsigned long long _eventType;
    NSString *_eventAction;
    NSString *_eventTarget;
    struct CGRect _nodeFrame;
}

- (void).cxx_destruct;
- (void)GDTfunctionb1V5l4;
- (_Bool)GDTfunctionb6Dvlc;
- (void)GDTfunctionc1oqRc;
- (_Bool)GDTfunctiond8Yfzs;
- (_Bool)GDTfunctione9LihX;
- (void)GDTfunctione9SfzV;
- (void)GDTfunctionj2JxtD;
- (void)GDTfunctionk5tczD;
- (_Bool)GDTfunctiono2WdZt;
- (_Bool)GDTfunctiono5IBDV;
@property(readonly, nonatomic) struct CGSize GDTfunctionp5s9az; // @dynamic GDTfunctionp5s9az;
- (void)GDTfunctionq4PG8Z;
- (void)GDTfunctionr8qJpy:(id)arg1;
- (_Bool)GDTfunctionr9gPQc;
@property(readonly, nonatomic) struct CGSize GDTfunctionv19QeI; // @dynamic GDTfunctionv19QeI;
- (void)GDTfunctionv1BlqA;
- (void)GDTfunctionx2OcER:(id)arg1;
- (_Bool)GDTfunctionx4EyVX;
- (void)GDTfunctionx5n2XQ;
- (_Bool)GDTfunctionx6uXvx:(id)arg1 value:(id)arg2;
- (struct CGSize)GDTfunctiony89oVp:(struct CGSize)arg1;
@property(copy, nonatomic) NSString *className; // @synthesize className=_className;
@property(readonly, nonatomic) UIView *cocoaView; // @synthesize cocoaView=_cocoaView;
@property(readonly, nonatomic) struct CGSize contentSize; // @dynamic contentSize;
- (void)dealloc;
@property(retain, nonatomic) NSMutableDictionary *dynamicProperties; // @synthesize dynamicProperties=_dynamicProperties;
@property(copy, nonatomic) NSString *eventAction; // @synthesize eventAction=_eventAction;
@property(copy, nonatomic) NSString *eventTarget; // @synthesize eventTarget=_eventTarget;
@property(nonatomic) unsigned long long eventType; // @synthesize eventType=_eventType;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
- (id)hitTest:(struct CGPoint)arg1;
- (id)init;
@property(nonatomic) unsigned long long layoutGravity; // @synthesize layoutGravity=_layoutGravity;
@property(nonatomic) double layoutHeight; // @synthesize layoutHeight=_layoutHeight;
@property(nonatomic) unsigned long long layoutInsetsPaddingFromSafeArea; // @synthesize layoutInsetsPaddingFromSafeArea=_layoutInsetsPaddingFromSafeArea;
@property(nonatomic) double layoutMarginBottom; // @synthesize layoutMarginBottom=_layoutMarginBottom;
@property(nonatomic) double layoutMarginLeft; // @synthesize layoutMarginLeft=_layoutMarginLeft;
@property(nonatomic) double layoutMarginRight; // @synthesize layoutMarginRight=_layoutMarginRight;
@property(nonatomic) double layoutMarginTop; // @synthesize layoutMarginTop=_layoutMarginTop;
@property(nonatomic) double layoutPaddingBottom; // @synthesize layoutPaddingBottom=_layoutPaddingBottom;
@property(nonatomic) double layoutPaddingLeft; // @synthesize layoutPaddingLeft=_layoutPaddingLeft;
@property(nonatomic) double layoutPaddingRight; // @synthesize layoutPaddingRight=_layoutPaddingRight;
@property(nonatomic) double layoutPaddingTop; // @synthesize layoutPaddingTop=_layoutPaddingTop;
@property(nonatomic) double layoutWidth; // @synthesize layoutWidth=_layoutWidth;
@property(nonatomic) double layoutX; // @synthesize layoutX=_layoutX;
@property(nonatomic) double layoutY; // @synthesize layoutY=_layoutY;
@property(nonatomic) struct CGRect nodeFrame; // @synthesize nodeFrame=_nodeFrame;
@property(nonatomic) double nodeHeight; // @synthesize nodeHeight=_nodeHeight;
@property(nonatomic) double nodeWidth; // @synthesize nodeWidth=_nodeWidth;
@property(nonatomic) double nodeX; // @synthesize nodeX=_nodeX;
@property(nonatomic) double nodeY; // @synthesize nodeY=_nodeY;
@property(nonatomic) __weak CALayer *rootCanvasLayer; // @synthesize rootCanvasLayer=_rootCanvasLayer;
@property(nonatomic) __weak UIView *rootCocoaView; // @synthesize rootCocoaView=_rootCocoaView;
@property(retain, nonatomic) NSMutableDictionary *runtimeProperties; // @synthesize runtimeProperties=_runtimeProperties;
- (void)setGDTfunctionb0nC8f;
- (void)setGDTfunctione2jfSc:(id)arg1 value:(id)arg2;
- (void)setGDTfunctionu4CcdV;
- (void)setNeedsLayout;
@property(retain, nonatomic) NSMutableArray *subNodes; // @synthesize subNodes=_subNodes;
@property(nonatomic) __weak GDTDLViewNode *superNode; // @synthesize superNode=_superNode;
@property(nonatomic) _Bool updatingNeedsResize; // @synthesize updatingNeedsResize=_updatingNeedsResize;
@property(nonatomic) unsigned long long visibility; // @synthesize visibility=_visibility;
@property(readonly, copy, nonatomic) NSString *templateType; // @synthesize templateType=_templateType;

@end

