//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTDLLayerFramelayout.h"

@class CALayer, UIView;

@interface GDTDLFrameLayout : GDTDLLayerFramelayout
{
    UIView *_rootCocoaView;
    CALayer *_rootCanvasLayer;
    unsigned long long _layoutGravity;
    UIView *_containerView;
    struct CGRect nodeFrame;
}

- (void).cxx_destruct;
- (void)GDTfunctionx5n2XQ;
- (id)cocoaView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (id)init;
- (unsigned long long)layoutGravity;
@property(nonatomic) struct CGRect nodeFrame; // @synthesize nodeFrame;
- (id)rootCanvasLayer;
- (id)rootCocoaView;
- (void)setLayoutGravity:(unsigned long long)arg1;
- (void)setRootCanvasLayer:(id)arg1;
- (void)setRootCocoaView:(id)arg1;

@end

