//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBaseHandler.h"

#import "GDTHandlerProtocol-Protocol.h"

@class NSString;

@interface GDTDeepLinkHandler : GDTBaseHandler <GDTHandlerProtocol>
{
}

+ (void)GDTfunctione9hdDW:(id)arg1 context:(id)arg2 jsRequest:(id)arg3;
+ (void)GDTfunctionj39OSI:(_Bool)arg1 success:(id)arg2 error:(id)arg3 jsBridge:(id)arg4 jsRequest:(id)arg5;
+ (void)execute:(id)arg1 request:(id)arg2;
+ (id)name;
+ (void)openDeepLink:(id)arg1 success:(CDUnknownBlockType)arg2;
+ (void)openUniversalLink:(id)arg1 success:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

