//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol GDTEventStoreProtocol <NSObject>
- (NSDictionary *)GDTfunctionp8mGQG;
@property(copy, nonatomic) NSString *content;
- (long long)eventType;
@property(nonatomic) _Bool isDirectEvent;
@property(nonatomic) long long sendCount;
@property(nonatomic) long long status;
@property(nonatomic) long long storeId;
@property(nonatomic) long long timestamp;
@end

