//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTFullScreenWebViewOverlayView.h"

@interface GDTInterstitialWebViewOverlayView : GDTFullScreenWebViewOverlayView
{
    _Bool _noticeTimeoutCount;
}

- (void)GDTfunctiona1zkNo;
- (void)GDTfunctionl3EPiB;
- (void)GDTfunctionz44QV4;
- (id)initLz6dki4:(id)arg1;
@property(nonatomic) _Bool noticeTimeoutCount; // @synthesize noticeTimeoutCount=_noticeTimeoutCount;

@end

