//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface GDTLoadAdParams : NSObject
{
    int _loginType;
    NSString *_loginAppId;
    NSString *_loginOpenId;
    NSDictionary *_dictionary;
    NSDictionary *_devExtra;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *devExtra; // @synthesize devExtra=_devExtra;
@property(retain, nonatomic) NSDictionary *dictionary; // @synthesize dictionary=_dictionary;
@property(copy, nonatomic) NSString *loginAppId; // @synthesize loginAppId=_loginAppId;
@property(copy, nonatomic) NSString *loginOpenId; // @synthesize loginOpenId=_loginOpenId;
@property(nonatomic) int loginType; // @synthesize loginType=_loginType;

@end

