//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTWebViewController.h"

@class GDTAdBaseModel, GDTWebViewDurationReport, UIButton;
@protocol GDTLandingPageWebViewControllerDelegate;

@interface GDTLandingPageWebViewController : GDTWebViewController
{
    _Bool _supportPerformanceReport;
    id <GDTLandingPageWebViewControllerDelegate> delegate;
    GDTAdBaseModel *_adModel;
    UIButton *_closeButton;
    UIButton *_backButton;
    GDTWebViewDurationReport *_durationReport;
    double _webViewStartLoading;
    struct CGPoint _closeButtonClickPoint;
}

- (void).cxx_destruct;
- (void)GDTfunctiona9UTIk;
- (void)GDTfunctionb95dqv:(id)arg1 event:(id)arg2;
- (void)GDTfunctionf4VkSG:(id)arg1 event:(id)arg2;
- (void)GDTfunctionf67e9N;
- (void)GDTfunctionh2lw0Y:(id)arg1;
- (void)GDTfunctionr42Fxo;
- (void)GDTfunctionr4ngXh:(_Bool)arg1;
- (void)GDTfunctiont6bT8a:(_Bool)arg1;
- (void)GDTfunctiony28bK0;
@property(retain, nonatomic) GDTAdBaseModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) struct CGPoint closeButtonClickPoint; // @synthesize closeButtonClickPoint=_closeButtonClickPoint;
- (void)dealloc;
@property(nonatomic) __weak id <GDTLandingPageWebViewControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) GDTWebViewDurationReport *durationReport; // @synthesize durationReport=_durationReport;
- (id)init;
- (void)loadRequest;
- (void)setLandingPageReportUrl:(id)arg1;
@property(nonatomic) _Bool supportPerformanceReport; // @synthesize supportPerformanceReport=_supportPerformanceReport;
@property(nonatomic) double webViewStartLoading; // @synthesize webViewStartLoading=_webViewStartLoading;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end

