//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTTrackingInfoService, GDT_SDKConfig, GDT_TaskQueue, NSString, NSTimer;

@interface GDTMobileTracking : NSObject
{
    GDT_SDKConfig *_sdkConfig;
    NSString *_sdkConfigURL;
    GDT_TaskQueue *_sendQueue;
    GDT_TaskQueue *_failedQueue;
    GDTTrackingInfoService *_trackingInfoService;
    NSTimer *_failedQueueTimer;
    NSTimer *_sendQueueTimer;
}

+ (void)setAppNetworkStatus:(long long)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)GDTfunctiond1riaZ;
- (void)GDTfunctionf81r84;
- (_Bool)GDTfunctiong8000R;
- (_Bool)GDTfunctionj0Kc9C;
- (id)GDTfunctionk9m7PL:(id)arg1 forCompany:(id)arg2 defaultOrigin:(_Bool)arg3;
- (id)GDTfunctionm82Cwi:(id)arg1;
- (void)GDTfunctionn8ifyC:(id)arg1;
- (id)GDTfunctionr9l6bH:(id)arg1;
- (void)GDTfunctiont1Q0mf:(id)arg1;
- (void)GDTfunctionu2Suit:(id)arg1;
- (void)GDTfunctionu4JUmk;
- (void)GDTfunctionv5LzCI:(id)arg1;
- (void)GDTfunctionw0UjvW:(_Bool)arg1;
- (void)GDTfunctionw5RKAV:(id)arg1;
- (void)GDTfunctionw8p675;
- (void)click:(id)arg1;
@property(retain, nonatomic) GDT_TaskQueue *failedQueue; // @synthesize failedQueue=_failedQueue;
@property(retain, nonatomic) NSTimer *failedQueueTimer; // @synthesize failedQueueTimer=_failedQueueTimer;
- (id)init;
- (void)initLb6C3Gq;
- (void)initLh6TOc1;
- (void)initLi70ynD;
@property(retain) GDT_SDKConfig *sdkConfig; // @synthesize sdkConfig=_sdkConfig;
@property(retain, nonatomic) NSString *sdkConfigURL; // @synthesize sdkConfigURL=_sdkConfigURL;
@property(retain, nonatomic) GDT_TaskQueue *sendQueue; // @synthesize sendQueue=_sendQueue;
@property(retain, nonatomic) NSTimer *sendQueueTimer; // @synthesize sendQueueTimer=_sendQueueTimer;
@property(retain, nonatomic) GDTTrackingInfoService *trackingInfoService; // @synthesize trackingInfoService=_trackingInfoService;
- (void)view:(id)arg1;

@end

