//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTMAdapterLoader.h"

@interface GDTMBiddingLoader : GDTMAdapterLoader
{
    _Bool isLoading;
}

- (id)GDTfunctiond1XjiO:(id)arg1;
- (void)GDTfunctionm6aDXM:(_Bool)arg1;
- (double)GDTfunctionr3thBL:(id)arg1;
- (_Bool)GDTfunctionr8DgMS;
- (id)currentTopOne;
- (id)initLs2fFJz:(id)arg1;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading;
- (void)start;

@end

