//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTNativeExpressAdImpDelegate-Protocol.h"

@class GDTAdParams, GDTNativeExpressAdImp, NSString;
@protocol GDTNativeExpressProAdManagerDelegate;

@interface GDTNativeExpressProAdManager : NSObject <GDTNativeExpressAdImpDelegate>
{
    id <GDTNativeExpressProAdManagerDelegate> _delegate;
    GDTAdParams *_adParams;
    GDTNativeExpressAdImp *_expressAdImp;
}

- (void).cxx_destruct;
- (void)GDTfunctionj5dN2i:(id)arg1 views:(id)arg2;
- (void)GDTfunctionn8r3kZ:(id)arg1 error:(id)arg2;
@property(readonly, nonatomic) GDTAdParams *adParams; // @synthesize adParams=_adParams;
@property(nonatomic) __weak id <GDTNativeExpressProAdManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GDTNativeExpressAdImp *expressAdImp; // @synthesize expressAdImp=_expressAdImp;
- (id)initWithPlacementId:(id)arg1 adPrams:(id)arg2;
- (void)loadAd:(long long)arg1;
@property(readonly, nonatomic) NSString *placementId;
- (void)sendLossNotificationWithWinnerPrice:(long long)arg1 lossReason:(long long)arg2 winnerAdnID:(id)arg3;
- (void)sendWinNotificationWithPrice:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

