//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBaseClickChainHandler.h"

#import "GDTVideoStoreViewControllerDelegate-Protocol.h"

@class GDTClickParam, NSString;
@protocol GDTClickFacadeDelegate;

@interface GDTOpenVideoStoreViewControllerChainHandler : GDTBaseClickChainHandler <GDTVideoStoreViewControllerDelegate>
{
    id <GDTClickFacadeDelegate> _delegate;
    double _handleBegin;
    GDTClickParam *_clickParam;
}

- (void).cxx_destruct;
- (void)GDTfunctioni2zlKg:(id)arg1;
- (void)GDTfunctionl1OJK0:(id)arg1 itunesId:(id)arg2 pageUrl:(id)arg3 req:(id)arg4;
- (void)GDTfunctionq3ZTze:(id)arg1;
- (void)GDTfunctionr1Kjri:(id)arg1 shouldMute:(_Bool)arg2;
- (void)GDTfunctionr5gYVq:(id)arg1;
- (void)GDTfunctions78mON:(id)arg1 shouldMute:(_Bool)arg2;
- (void)GDTfunctionu9kyyR:(id)arg1;
- (id)GDTfunctionx3kI25:(id)arg1;
- (void)GDTfunctionz2zKf2:(id)arg1;
- (_Bool)canHandleRequest:(id)arg1;
@property(nonatomic) __weak GDTClickParam *clickParam; // @synthesize clickParam=_clickParam;
@property(nonatomic) __weak id <GDTClickFacadeDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double handleBegin; // @synthesize handleBegin=_handleBegin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

