//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTPlayer.h"

@class GDTOrientationObserver;

@interface GDTPlayer (GDTPlayerOrientationRotation)
- (void)addDeviceOrientationObserver;
@property(nonatomic) _Bool allowOrentitaionRotation;
@property(readonly, nonatomic) long long currentOrientation;
- (void)enterFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
- (void)enterLandscapeFullScreen:(long long)arg1 animated:(_Bool)arg2;
- (void)enterPortraitFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) _Bool isFullScreen;
@property(nonatomic, getter=isLockedScreen) _Bool lockedScreen;
- (_Bool)isNeedAdaptiveiOS8Rotation;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden;
@property(copy, nonatomic) CDUnknownBlockType orientationDidChanged;
@property(readonly, nonatomic) GDTOrientationObserver *orientationObserver;
@property(copy, nonatomic) CDUnknownBlockType orientationWillChange;
- (void)removeDeviceOrientationObserver;
@property(readonly, nonatomic) _Bool shouldAutorotate;
@end

