//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UITouch;

@protocol GDTPlayerControlViewProtocol <NSObject>

@optional
- (void)GDTfunctionc9teZP;
- (void)GDTfunctiong10aTg;
- (void)GDTfunctionj9MeCo:(_Bool)arg1;
- (void)GDTfunctiono0IIgT;
- (_Bool)GDTfunctiono3U829:(struct CGPoint)arg1 gestureType:(unsigned long long)arg2 touch:(UITouch *)arg3;
- (void)GDTfunctiont8ttTZ;
@end

