//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTPlayer.h"

@interface GDTPlayer (Background)
+ (void)load;
- (void)GDTfunctiona8AXDd;
- (void)GDTfunctiont2NXW3:(id)arg1;
- (id)GDTfunctiont3tEkw;
- (void)GDTfunctionu0drkI:(id)arg1;
- (void)GDTfunctionu0drkI:(id)arg1 withBlurLevel:(float)arg2;
- (void)bg_dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeObserver;
- (void)setGDTfunctiont3tEkw:(id)arg1;
@end

