//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTMBaseAdMediator.h"

#import "GDTRewardVideoAdImpProtocol-Protocol.h"
#import "GDTRewardVideoAdNetworkConnectorProtocol-Protocol.h"

@class GDTLoadAdParams, GDTRewardVideoAd, GDTServerSideVerificationOptions, NSDictionary, NSMutableArray, NSString;
@protocol GDTRewardedVideoAdImpDelegate;

@interface GDTRewardVideoAdMediator : GDTMBaseAdMediator <GDTRewardVideoAdImpProtocol, GDTRewardVideoAdNetworkConnectorProtocol>
{
    _Bool videoMuted;
    id <GDTRewardedVideoAdImpDelegate> delegate;
    GDTRewardVideoAd *rewardVideoAd;
    NSDictionary *tagDict;
    NSString *adNetworkName;
    GDTLoadAdParams *loadAdParams;
    id adDelegate;
    GDTServerSideVerificationOptions *serverSideVerificationOptions;
    NSDictionary *mediationExtDict;
    NSMutableArray *_loadedAdapterArray;
}

- (void).cxx_destruct;
- (void)GDTfunctionh8TRVl;
- (id)GDTfunctionq8IHzD;
- (void)GDTfunctions9ozpy;
- (void)GDTfunctionz7YmtL;
@property(nonatomic) __weak id adDelegate; // @synthesize adDelegate;
@property(copy, nonatomic) NSString *adNetworkName; // @synthesize adNetworkName;
- (void)adapterLoadAd:(id)arg1;
- (void)adapter_rewardVideoAd:(id)arg1 didFailWithError:(id)arg2;
- (void)adapter_rewardVideoAdDidClicked:(id)arg1;
- (void)adapter_rewardVideoAdDidClose:(id)arg1;
- (void)adapter_rewardVideoAdDidExposed:(id)arg1;
- (void)adapter_rewardVideoAdDidLoad:(id)arg1;
- (void)adapter_rewardVideoAdDidPlayFinish:(id)arg1;
- (void)adapter_rewardVideoAdDidRewardEffective:(id)arg1;
- (void)adapter_rewardVideoAdVideoDidLoad:(id)arg1;
- (void)adapter_rewardVideoAdWillVisible:(id)arg1;
@property(nonatomic) __weak id <GDTRewardedVideoAdImpDelegate> delegate; // @synthesize delegate;
@property(readonly, nonatomic) long long expiredTimestamp;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
- (void)loadAd;
@property(retain, nonatomic) GDTLoadAdParams *loadAdParams; // @synthesize loadAdParams;
@property(retain, nonatomic) NSMutableArray *loadedAdapterArray; // @synthesize loadedAdapterArray=_loadedAdapterArray;
@property(retain, nonatomic) NSDictionary *mediationExtDict; // @synthesize mediationExtDict;
@property(nonatomic) __weak GDTRewardVideoAd *rewardVideoAd; // @synthesize rewardVideoAd;
@property(retain, nonatomic) GDTServerSideVerificationOptions *serverSideVerificationOptions; // @synthesize serverSideVerificationOptions;
@property(retain, nonatomic) NSDictionary *tagDict; // @synthesize tagDict;
@property(nonatomic) _Bool videoMuted; // @synthesize videoMuted;
- (_Bool)showAdFromRootViewController:(id)arg1;
- (double)videoDuration;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *placementId;
@property(readonly) Class superclass;

@end

