//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol GDTStoreProductFacadeDelegate <NSObject>

@optional
- (void)GDTfunctiona1L0D4;
- (void)GDTfunctionp7J3Zx;
- (void)GDTfunctionv9HTEh;
- (void)GDTfunctionx2wOdp;
@end

