//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTLoadAdParams, GDTSplashZoomOutView, UIColor, UIImage, UIImageView, UIWindow;
@protocol GDTSplashAdDelegate, GDTSplashAdImpProtocol;

@interface GDTSplashAd : NSObject
{
    id <GDTSplashAdImpProtocol> _mediator;
    UIWindow *_window;
    UIImageView *_defaultView;
    double _loadStartTime;
    long long _splashAdType;
}

- (void).cxx_destruct;
- (void)GDTfunctiond5HYa1:(long long)arg1;
- (id)GDTfunctions7xy7p;
- (id)adNetworkName;
@property(copy, nonatomic) UIColor *backgroundColor;
@property(retain, nonatomic) UIImage *backgroundImage;
- (void)dealloc;
@property(retain, nonatomic) UIImageView *defaultView; // @synthesize defaultView=_defaultView;
@property(nonatomic) __weak id <GDTSplashAdDelegate> delegate;
- (long long)eCPM;
- (id)eCPMLevel;
@property(nonatomic) double fetchDelay;
- (id)initWithAppId:(id)arg1 placementId:(id)arg2;
- (id)initWithPlacementId:(id)arg1;
- (id)initWithPlacementId:(id)arg1 s2sToken:(id)arg2 isFromS2S:(_Bool)arg3;
- (id)initWithPlacementId:(id)arg1 token:(id)arg2;
- (_Bool)isAdValid;
- (void)loadAd;
- (void)loadAdAndShowFullScreenInWindow:(id)arg1 withLogoImage:(id)arg2 skipView:(id)arg3;
- (void)loadAdAndShowInWindow:(id)arg1;
- (void)loadAdAndShowInWindow:(id)arg1 withBottomView:(id)arg2;
- (void)loadAdAndShowInWindow:(id)arg1 withBottomView:(id)arg2 skipView:(id)arg3;
@property(retain, nonatomic) GDTLoadAdParams *loadAdParams;
- (void)loadFullScreenAd;
@property(nonatomic) double loadStartTime; // @synthesize loadStartTime=_loadStartTime;
@property(retain, nonatomic) id <GDTSplashAdImpProtocol> mediator; // @synthesize mediator=_mediator;
@property(nonatomic) _Bool needZoomOut;
- (void)preloadSplashOrderWithPlacementId:(id)arg1;
- (void)sendLossNotificationWithWinnerPrice:(long long)arg1 lossReason:(long long)arg2 winnerAdnID:(id)arg3;
- (void)sendWinNotificationWithPrice:(long long)arg1;
- (void)setBidECPM:(long long)arg1;
@property(nonatomic) struct CGPoint skipButtonCenter;
@property(nonatomic) long long splashAdType; // @synthesize splashAdType=_splashAdType;
@property(nonatomic) __weak UIWindow *window; // @synthesize window=_window;
- (void)showAdInWindow:(id)arg1 adProviderView:(id)arg2 skipView:(id)arg3;
- (void)showAdInWindow:(id)arg1 withBottomView:(id)arg2 skipView:(id)arg3;
- (void)showFullScreenAdInWindow:(id)arg1 withLogoImage:(id)arg2 skipView:(id)arg3;
@property(readonly, nonatomic) GDTSplashZoomOutView *splashZoomOutView;

@end

