//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTAdService.h"

@interface GDTSplashService : GDTAdService
{
}

+ (void)exposureAdWithAdModel:(id)arg1 replacementData:(id)arg2 placementID:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (void)fetchSplashAdModelWithParams:(id)arg1 success:(CDUnknownBlockType)arg2 notice:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (id)getOrderWhiteListDict:(id)arg1;
+ (id)getValidateOrderIndexMapForService:(id)arg1 placementID:(id)arg2;
+ (void)sendEmptyOrder:(id)arg1 placementId:(id)arg2;

@end

