//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface GDTStoreProductPreloadManager : NSObject
{
    NSMutableDictionary *_ituneStores;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)defaultManager;
+ (id)sharedGDTStoreProductPreloadManager;
- (void).cxx_destruct;
- (void)GDTfunctionb0Wn3T:(id)arg1 viewController:(id)arg2;
- (id)GDTfunctionk4Gsc2:(id)arg1;
- (_Bool)GDTfunctionn3961G:(id)arg1 campaignId:(id)arg2 providerId:(id)arg3;
- (void)GDTfunctions9Sv5u;
- (_Bool)GDTfunctiont1lTDH:(id)arg1;
- (_Bool)GDTfunctionv9FeXz:(id)arg1 campaignId:(id)arg2 providerId:(id)arg3 adNetwork:(id)arg4;
- (long long)GDTfunctionz2Qiop:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
@property(retain, nonatomic) NSMutableDictionary *ituneStores; // @synthesize ituneStores=_ituneStores;

@end

