//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBottomCardView.h"

@class UILabel;

@interface GDTStrictBottomCardView : GDTBottomCardView
{
    UILabel *_jumpNoticeLabel;
}

- (void).cxx_destruct;
- (id)GDTfunctiona8gG5I;
- (void)GDTfunctionl2zkMJ;
- (void)GDTfunctionl6fJpB;
- (void)GDTfunctionz47mOp;
- (id)initLb48sas:(id)arg1;
@property(retain, nonatomic) UILabel *jumpNoticeLabel; // @synthesize jumpNoticeLabel=_jumpNoticeLabel;

@end

