//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface GDTSplashSkipContentView : UIView
{
    UILabel *_skipLabel;
    UILabel *_timeLabel;
}

- (void).cxx_destruct;
- (void)GDTfunctionf2hhEH;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setGDTfunctiong5tlfF:(long long)arg1;
@property(retain, nonatomic) UILabel *skipLabel; // @synthesize skipLabel=_skipLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)setTitle:(id)arg1;

@end

