//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GDTUnifiedTemplateModel, UIViewController;

@protocol GDTTemplateViewProtocol <NSObject>
- (void)GDTfunctioni6eKiP:(_Bool)arg1;
- (_Bool)GDTfunctionj34OUt;
- (void)GDTfunctionn1ab4f:(UIViewController *)arg1;
- (double)GDTfunctionn9ecFI;
- (void)GDTfunctionu5zvFM:(_Bool)arg1;
- (void)GDTfunctionv16mQd:(_Bool)arg1;
- (_Bool)GDTfunctionx5uY8V;
- (double)GDTfunctiony0aJVS;
- (void)inner_render;

@optional
@property(retain, nonatomic) GDTUnifiedTemplateModel *adModel;
@end

