//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GDTUnifiedNativeAdDataObject, NSDictionary;
@protocol GDTUnifiedNativeAdViewImpProtocol;

@protocol GDTUnifiedNativeAdViewImpDelegate <NSObject>

@optional
- (void)GDTfunctionc0hBjb:(id <GDTUnifiedNativeAdViewImpProtocol>)arg1;
- (void)GDTfunctiond0R7hB:(id <GDTUnifiedNativeAdViewImpProtocol>)arg1;
- (void)GDTfunctionk4AcGY:(id <GDTUnifiedNativeAdViewImpProtocol>)arg1;
- (void)GDTfunctiono0cqmk:(id <GDTUnifiedNativeAdViewImpProtocol>)arg1;
- (void)GDTfunctionq4twy0:(id <GDTUnifiedNativeAdViewImpProtocol>)arg1;
- (void)GDTfunctionq7NncR:(id <GDTUnifiedNativeAdViewImpProtocol>)arg1 originDataObject:(GDTUnifiedNativeAdDataObject *)arg2 vastAdEventType:(long long)arg3;
- (void)GDTfunctionq7NncR:(id <GDTUnifiedNativeAdViewImpProtocol>)arg1 playerStatusChanged:(unsigned long long)arg2 userInfo:(NSDictionary *)arg3;
@end

