//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTLoadAdParams, NSDictionary;
@protocol GDTUnifiedNativeAdDelegate, GDTUnifiedNativeAdImpProtocol;

@interface GDTUnifiedNativeAd : NSObject
{
    id <GDTUnifiedNativeAdImpProtocol> _mediator;
}

- (void).cxx_destruct;
- (void)GDTfunctions2PkDE:(id)arg1;
- (id)adNetworkName;
@property(nonatomic) __weak id <GDTUnifiedNativeAdDelegate> delegate;
- (id)initWithAppId:(id)arg1 placementId:(id)arg2;
- (id)initWithPlacementId:(id)arg1;
- (id)initWithPlacementId:(id)arg1 s2sToken:(id)arg2 isFromS2S:(_Bool)arg3;
- (id)initWithPlacementId:(id)arg1 token:(id)arg2;
- (void)loadAd;
@property(retain, nonatomic) GDTLoadAdParams *loadAdParams;
- (void)loadAdWithAdCount:(long long)arg1;
@property(nonatomic) long long maxVideoDuration;
@property(retain, nonatomic) id <GDTUnifiedNativeAdImpProtocol> mediator; // @synthesize mediator=_mediator;
@property(nonatomic) long long minVideoDuration;
- (void)sendLossNotificationWithWinnerPrice:(long long)arg1 lossReason:(long long)arg2 winnerAdnID:(id)arg3;
- (void)sendWinNotificationWithPrice:(long long)arg1;
- (void)setBidECPM:(long long)arg1;
@property(retain, nonatomic) NSDictionary *tagDict;
- (void)setVastClassName:(id)arg1;
@property(nonatomic) unsigned long long videoPlayPolicy;
@property(nonatomic) unsigned long long videoRenderType;

@end

