//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;
@protocol GDTUnifiedBannerAdNetworkAdapterProtocol;

@protocol GDTUnifiedBannerAdNetworkConnectorProtocol <NSObject>

@optional
- (void)adapter_unifiedBannerViewClicked:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewDidDismissFullScreenModal:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewDidLoad:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewDidPresentFullScreenModal:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewFailedToLoad:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1 error:(NSError *)arg2;
- (void)adapter_unifiedBannerViewWillClose:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewWillDismissFullScreenModal:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewWillExpose:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewWillLeaveApplication:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
- (void)adapter_unifiedBannerViewWillPresentFullScreenModal:(id <GDTUnifiedBannerAdNetworkAdapterProtocol>)arg1;
@end

