//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBaseAdAdapter.h"

#import "GDTUnifiedNativeAdDelegate-Protocol.h"
#import "GDTUnifiedNativeAdNetworkAdapterProtocol-Protocol.h"

@class GDTUnifiedNativeAdImp, GDTUnifiedNativeAdMediator, NSArray, NSString;

@interface GDTUnifiedNativeAdAdapter : GDTBaseAdAdapter <GDTUnifiedNativeAdNetworkAdapterProtocol, GDTUnifiedNativeAdDelegate>
{
    long long maxVideoDuration;
    long long minVideoDuration;
    GDTUnifiedNativeAdMediator *_connector;
    GDTUnifiedNativeAdImp *_unifiedNativeAdImp;
    NSArray *_dataObjectArray;
}

- (void).cxx_destruct;
- (id)adImp;
@property(nonatomic) __weak GDTUnifiedNativeAdMediator *connector; // @synthesize connector=_connector;
@property(retain, nonatomic) NSArray *dataObjectArray; // @synthesize dataObjectArray=_dataObjectArray;
- (long long)eCPM;
- (void)gdt_unifiedNativeAdLoaded:(id)arg1 error:(id)arg2;
- (id)initWithAdNetworkConnector:(id)arg1 posId:(id)arg2;
- (_Bool)isContractAd;
- (void)loadAdWithCount:(long long)arg1;
@property(nonatomic) long long maxVideoDuration; // @synthesize maxVideoDuration;
- (id)mediationPrice;
@property(nonatomic) long long minVideoDuration; // @synthesize minVideoDuration;
- (void)setMediationExtDict:(id)arg1;
@property(retain, nonatomic) GDTUnifiedNativeAdImp *unifiedNativeAdImp; // @synthesize unifiedNativeAdImp=_unifiedNativeAdImp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

