//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTAdViewClickWithAntiSpamCheckerDelegate-Protocol.h"
#import "GDTHandlerContextProtocol-Protocol.h"
#import "GDTPlayerControlProtocol-Protocol.h"
#import "GDTVideoEndcardAppearanceProtocol-Protocol.h"
#import "GDTWebViewDelegate-Protocol.h"

@class GDTAdBaseModel, GDTAdViewClickWithAntiSpamChecker, GDTAdWKWebView, GDTExtensionButton, GDTPlayDemoLoadingView, GDTPlayer, NSString, UIViewController;

@interface GDTVideoEndCardView : UIView <GDTWebViewDelegate, GDTAdViewClickWithAntiSpamCheckerDelegate, GDTVideoEndcardAppearanceProtocol, GDTPlayerControlProtocol, GDTHandlerContextProtocol>
{
    _Bool _hasExposured;
    _Bool _closeButHangUp;
    _Bool _supportNativeEndcard;
    _Bool _webviewLoadSuccess;
    _Bool _webviewHasLoaded;
    _Bool _hasShowNativeEndcard;
    _Bool _hasRecordedWebviewTerminate;
    float _pressForce;
    float _pressRadius;
    GDTPlayer *_player;
    GDTAdBaseModel *_adModel;
    CDUnknownBlockType _endCardBodyClickedCallback;
    CDUnknownBlockType _endCardReplayButtonClickedCallback;
    CDUnknownBlockType _loadFailureCallback;
    CDUnknownBlockType _loadSuccessCallback;
    CDUnknownBlockType _endCardCloseButtonClickedCallback;
    long long _playBeginTime;
    unsigned long long _status;
    UIViewController *_rootViewController;
    long long _preloadTriggerTime;
    GDTAdWKWebView *_webView;
    GDTExtensionButton *_closeButton;
    UIView *_nativeEndcard;
    GDTAdViewClickWithAntiSpamChecker *_clickChecker;
    long long _clickArea;
    GDTPlayDemoLoadingView *_loadingView;
    long long _retryCount;
    double _timeout;
    long long _preloadTime;
    struct CGPoint _closeButtonClickPoint;
}

- (void).cxx_destruct;
- (void)GDTfunctionf2D3iT:(id)arg1;
- (void)GDTfunctionf3W1cs;
- (void)GDTfunctionh6WE1k:(_Bool)arg1;
- (void)GDTfunctionk9otvV;
- (_Bool)GDTfunctionm55QS3:(id)arg1 GDTfunctionh6AJjU:(id)arg2;
- (void)GDTfunctionm55QS3:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)GDTfunctionm55QS3:(id)arg1 didFinishNavigation:(id)arg2;
- (void)GDTfunctionm55QS3:(id)arg1 handleJsRequest:(id)arg2;
- (void)GDTfunctionn3gSpo;
- (_Bool)GDTfunctionn7elcl;
- (void)GDTfunctionp4GmvA:(id)arg1;
- (void)GDTfunctionq1UPQO;
- (id)GDTfunctionq8QnT3;
- (void)GDTfunctionr9tpCF;
- (_Bool)GDTfunctiont0Dc72;
- (void)GDTfunctiont6bT8a:(_Bool)arg1;
- (void)GDTfunctionw9w9hp;
- (void)GDTfunctiony3HbPY:(id)arg1;
- (void)GDTfunctiony5kjZF;
- (void)GDTfunctionz44QV4:(id)arg1 event:(id)arg2;
@property(retain, nonatomic) GDTAdBaseModel *adModel; // @synthesize adModel=_adModel;
@property(nonatomic) long long clickArea; // @synthesize clickArea=_clickArea;
@property(retain, nonatomic) GDTAdViewClickWithAntiSpamChecker *clickChecker; // @synthesize clickChecker=_clickChecker;
@property(nonatomic) _Bool closeButHangUp; // @synthesize closeButHangUp=_closeButHangUp;
@property(retain, nonatomic) GDTExtensionButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) struct CGPoint closeButtonClickPoint; // @synthesize closeButtonClickPoint=_closeButtonClickPoint;
- (void)dealloc;
@property(copy, nonatomic) CDUnknownBlockType endCardBodyClickedCallback; // @synthesize endCardBodyClickedCallback=_endCardBodyClickedCallback;
@property(copy, nonatomic) CDUnknownBlockType endCardCloseButtonClickedCallback; // @synthesize endCardCloseButtonClickedCallback=_endCardCloseButtonClickedCallback;
@property(copy, nonatomic) CDUnknownBlockType endCardReplayButtonClickedCallback; // @synthesize endCardReplayButtonClickedCallback=_endCardReplayButtonClickedCallback;
- (void)gdt_player:(id)arg1 currentTime:(double)arg2 totalTime:(double)arg3;
- (void)gdt_player:(id)arg1 playStateChanged:(unsigned long long)arg2;
- (void)gestureView:(id)arg1 didClickWithClickData:(id)arg2;
@property(nonatomic) _Bool hasExposured; // @synthesize hasExposured=_hasExposured;
@property(nonatomic) _Bool hasRecordedWebviewTerminate; // @synthesize hasRecordedWebviewTerminate=_hasRecordedWebviewTerminate;
@property(nonatomic) _Bool hasShowNativeEndcard; // @synthesize hasShowNativeEndcard=_hasShowNativeEndcard;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 adModel:(id)arg2;
- (id)isViewable;
- (void)layoutSubviews;
@property(copy, nonatomic) CDUnknownBlockType loadFailureCallback; // @synthesize loadFailureCallback=_loadFailureCallback;
- (void)loadRequest;
@property(copy, nonatomic) CDUnknownBlockType loadSuccessCallback; // @synthesize loadSuccessCallback=_loadSuccessCallback;
@property(retain, nonatomic) GDTPlayDemoLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIView *nativeEndcard; // @synthesize nativeEndcard=_nativeEndcard;
@property(nonatomic) long long playBeginTime; // @synthesize playBeginTime=_playBeginTime;
@property(nonatomic) __weak GDTPlayer *player; // @synthesize player=_player;
- (void)preloadRequest;
@property(nonatomic) long long preloadTime; // @synthesize preloadTime=_preloadTime;
@property(nonatomic) long long preloadTriggerTime; // @synthesize preloadTriggerTime=_preloadTriggerTime;
@property(nonatomic) float pressForce; // @synthesize pressForce=_pressForce;
@property(nonatomic) float pressRadius; // @synthesize pressRadius=_pressRadius;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void)setHidden:(_Bool)arg1;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(nonatomic) _Bool supportNativeEndcard; // @synthesize supportNativeEndcard=_supportNativeEndcard;
@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(retain, nonatomic) GDTAdWKWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) _Bool webviewHasLoaded; // @synthesize webviewHasLoaded=_webviewHasLoaded;
@property(nonatomic) _Bool webviewLoadSuccess; // @synthesize webviewLoadSuccess=_webviewLoadSuccess;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(copy, nonatomic) CDUnknownBlockType deepLinkCallback;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) CDUnknownBlockType jumpToAppstoreCallback;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *xjLandingPageUrl;

@end

