//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class GDTAdBaseModel, GDTAppStoreAdNetWorkModel, GDTExtensionButton, GDTMutiGestureScrollView, GDTPlayer, GDTStoreProductController, GDTVideoPlayProgressReporter, GDTWebViewController, NSString, UIView;
@protocol GDTVideoStoreViewControllerDelegate;

@interface GDTVideoStoreViewController : UIViewController <UIScrollViewDelegate, SKStoreProductViewControllerDelegate>
{
    _Bool _verticalVideo;
    _Bool _originVideoMuted;
    _Bool _videoMuted;
    _Bool _landingPageVC;
    _Bool _videoPausedWhenVideoPackOff;
    NSString *_clickId;
    NSString *_itunesId;
    id <GDTVideoStoreViewControllerDelegate> _delegate;
    GDTAppStoreAdNetWorkModel *_adNetwork;
    unsigned long long _originPlayerControlViewType;
    GDTVideoPlayProgressReporter *_playProgressReporter;
    GDTPlayer *_playerController;
    UIView *_containerView;
    NSString *_rl;
    GDTStoreProductController *_storeProductController;
    GDTWebViewController *_webViewController;
    UIView *_videoSuperView;
    GDTMutiGestureScrollView *_bottomScrollView;
    GDTExtensionButton *_suspendedCloseButton;
    double _webViewMaxHeight;
    double _verticalVideoShrinkValue;
    double _verticalVideoMaxHeight;
    GDTAdBaseModel *_adModel;
    struct CGRect _sourceFrame;
    struct CGRect _horizontalVideoFrame;
}

- (void).cxx_destruct;
- (double)GDTfunctiona6nRQe;
- (void)GDTfunctionc2Zc0b:(id)arg1;
- (float)GDTfunctionc6dsD8;
- (_Bool)GDTfunctionf0ndhw;
- (void)GDTfunctionf2D3iT;
- (void)GDTfunctionf2qGpm:(_Bool)arg1;
- (struct CGSize)GDTfunctionj1p4OR;
- (void)GDTfunctionp4GmvA;
- (void)GDTfunctionu2DUrH;
- (void)GDTfunctionu7FLCd;
- (double)GDTfunctiony6qm3b;
- (double)GDTfunctionz1qPYB;
@property(retain, nonatomic) GDTAdBaseModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) GDTAppStoreAdNetWorkModel *adNetwork; // @synthesize adNetwork=_adNetwork;
@property(retain, nonatomic) GDTMutiGestureScrollView *bottomScrollView; // @synthesize bottomScrollView=_bottomScrollView;
@property(copy, nonatomic) NSString *clickId; // @synthesize clickId=_clickId;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void)dealloc;
@property(nonatomic) __weak id <GDTVideoStoreViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismissViewController;
@property(nonatomic) struct CGRect horizontalVideoFrame; // @synthesize horizontalVideoFrame=_horizontalVideoFrame;
- (id)initWithPlayer:(id)arg1 superView:(id)arg2 itunesId:(id)arg3 rl:(id)arg4 adModel:(id)arg5;
@property(copy, nonatomic) NSString *itunesId; // @synthesize itunesId=_itunesId;
@property(nonatomic) _Bool landingPageVC; // @synthesize landingPageVC=_landingPageVC;
@property(nonatomic) unsigned long long originPlayerControlViewType; // @synthesize originPlayerControlViewType=_originPlayerControlViewType;
@property(nonatomic) _Bool originVideoMuted; // @synthesize originVideoMuted=_originVideoMuted;
@property(retain, nonatomic) GDTVideoPlayProgressReporter *playProgressReporter; // @synthesize playProgressReporter=_playProgressReporter;
@property(retain, nonatomic) GDTPlayer *playerController; // @synthesize playerController=_playerController;
- (long long)preferredInterfaceOrientationForPresentation;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersHomeIndicatorAutoHidden;
- (void)productViewControllerDidFinish:(id)arg1;
@property(copy, nonatomic) NSString *rl; // @synthesize rl=_rl;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
@property(nonatomic) struct CGRect sourceFrame; // @synthesize sourceFrame=_sourceFrame;
@property(retain, nonatomic) GDTStoreProductController *storeProductController; // @synthesize storeProductController=_storeProductController;
@property(retain, nonatomic) GDTExtensionButton *suspendedCloseButton; // @synthesize suspendedCloseButton=_suspendedCloseButton;
@property(nonatomic) _Bool verticalVideo; // @synthesize verticalVideo=_verticalVideo;
@property(nonatomic) double verticalVideoMaxHeight; // @synthesize verticalVideoMaxHeight=_verticalVideoMaxHeight;
@property(nonatomic) double verticalVideoShrinkValue; // @synthesize verticalVideoShrinkValue=_verticalVideoShrinkValue;
@property(nonatomic) _Bool videoMuted; // @synthesize videoMuted=_videoMuted;
@property(nonatomic) _Bool videoPausedWhenVideoPackOff; // @synthesize videoPausedWhenVideoPackOff=_videoPausedWhenVideoPackOff;
@property(retain, nonatomic) UIView *videoSuperView; // @synthesize videoSuperView=_videoSuperView;
@property(retain, nonatomic) GDTWebViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(nonatomic) double webViewMaxHeight; // @synthesize webViewMaxHeight=_webViewMaxHeight;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

