//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HMDBUCrashModel.h"

@class NSDictionary;

@interface HMDBUCrashRegisters : HMDBUCrashModel
{
    NSDictionary *_registers;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *registers; // @synthesize registers=_registers;
- (void)updateWithDictionary:(id)arg1;

@end

