//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HMDBUCrashModel.h"

@class HMDBUCrashHeaderInfo, HMDBUCrashMetaData, HMDBUCrashProcessState, HMDBUCrashRuntimeInfo, HMDBUCrashStorage, HMDBUCrashThreadInfo, NSArray, NSDictionary, NSMutableString, NSString;

@interface HMDBUCrashInfo : HMDBUCrashModel
{
    NSMutableString *_str;
    _Bool _isEnvAbnormal;
    _Bool _isCorrupted;
    _Bool _fileIOError;
    _Bool _isInvalid;
    NSArray *_regions;
    NSArray *_images;
    HMDBUCrashMetaData *_meta;
    HMDBUCrashHeaderInfo *_headerInfo;
    NSArray *_threads;
    HMDBUCrashThreadInfo *_stackRecord;
    NSArray *_queueNames;
    NSArray *_threadNames;
    HMDBUCrashProcessState *_processState;
    HMDBUCrashStorage *_storage;
    NSDictionary *_dynamicInfo;
    NSDictionary *_extraDynamicInfo;
    HMDBUCrashRuntimeInfo *_runtimeInfo;
    NSArray *_registerAnalysis;
    NSArray *_stackAnalysis;
    NSString *_sdklog;
    NSString *_gameScriptStack;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *dynamicInfo; // @synthesize dynamicInfo=_dynamicInfo;
- (void)error:(id)arg1;
@property(copy, nonatomic) NSDictionary *extraDynamicInfo; // @synthesize extraDynamicInfo=_extraDynamicInfo;
@property(nonatomic) _Bool fileIOError; // @synthesize fileIOError=_fileIOError;
@property(copy, nonatomic) NSString *gameScriptStack; // @synthesize gameScriptStack=_gameScriptStack;
@property(retain, nonatomic) HMDBUCrashHeaderInfo *headerInfo; // @synthesize headerInfo=_headerInfo;
@property(copy, nonatomic) NSArray *images; // @synthesize images=_images;
- (void)info:(id)arg1;
- (id)init;
@property(readonly, nonatomic) _Bool isComplete;
@property(nonatomic) _Bool isCorrupted; // @synthesize isCorrupted=_isCorrupted;
@property(nonatomic) _Bool isEnvAbnormal; // @synthesize isEnvAbnormal=_isEnvAbnormal;
@property(nonatomic) _Bool isInvalid; // @synthesize isInvalid=_isInvalid;
@property(retain, nonatomic) HMDBUCrashMetaData *meta; // @synthesize meta=_meta;
@property(readonly, nonatomic) NSString *processLog;
@property(retain, nonatomic) HMDBUCrashProcessState *processState; // @synthesize processState=_processState;
@property(copy, nonatomic) NSArray *queueNames; // @synthesize queueNames=_queueNames;
@property(copy, nonatomic) NSArray *regions; // @synthesize regions=_regions;
@property(copy, nonatomic) NSArray *registerAnalysis; // @synthesize registerAnalysis=_registerAnalysis;
@property(retain, nonatomic) HMDBUCrashRuntimeInfo *runtimeInfo; // @synthesize runtimeInfo=_runtimeInfo;
@property(copy, nonatomic) NSString *sdklog; // @synthesize sdklog=_sdklog;
@property(copy, nonatomic) NSArray *stackAnalysis; // @synthesize stackAnalysis=_stackAnalysis;
@property(retain, nonatomic) HMDBUCrashThreadInfo *stackRecord; // @synthesize stackRecord=_stackRecord;
@property(retain, nonatomic) HMDBUCrashStorage *storage; // @synthesize storage=_storage;
@property(copy, nonatomic) NSArray *threadNames; // @synthesize threadNames=_threadNames;
@property(copy, nonatomic) NSArray *threads; // @synthesize threads=_threads;
- (void)tag:(id)arg1 format:(id)arg2 args:(char *)arg3;
- (void)warn:(id)arg1;

@end

