//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HMDBUCrashDynamicDataProvider : NSObject
{
    _Bool _needRefreshContext;
    _Bool _needRefreshFilters;
}

- (void)applicationStateChanged:(id)arg1;
- (void)applicationWillTerminate;
- (void)dealloc;
- (id)init;
- (void)networkAccessChanged:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)refreshCustomContext;
- (void)refreshFilters;
- (void)removeObserver;
- (void)requestRefreshCustomContext;
- (void)requestRefreshFilters;
- (void)sceneDidUpdate;
- (void)setup;

@end

