//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface HMDBUThreadBacktrace : NSObject
{
    _Bool _crashed;
    _Bool _isSymbol;
    unsigned long long _threadIndex;
    unsigned long long _threadID;
    NSString *_name;
    NSArray *_stackFrames;
    double _timestamp;
}

+ (id)backtraceOfAllThreadsWithKeyThread:(unsigned int)arg1 symbolicate:(_Bool)arg2 skippedDepth:(unsigned long long)arg3 suspend:(_Bool)arg4 maxThreadCount:(unsigned long long)arg5;
+ (id)backtraceOfCurrentThreadWithSymbolicate:(_Bool)arg1 skippedDepth:(unsigned long long)arg2 suspend:(_Bool)arg3;
+ (id)backtraceOfMainThreadWithSymbolicate:(_Bool)arg1 skippedDepth:(unsigned long long)arg2 suspend:(_Bool)arg3;
+ (id)backtraceOfThread:(unsigned int)arg1 symbolicate:(_Bool)arg2 skippedDepth:(unsigned long long)arg3 suspend:(_Bool)arg4;
+ (id)createBacktraceList:(struct hmdbubt_backtrace *)arg1 size:(long long)arg2 keyThread:(unsigned int)arg3 symbolicate:(_Bool)arg4;
+ (unsigned int)currentThread;
+ (void)load;
+ (unsigned int)mainThread;
- (void).cxx_destruct;
- (unsigned long long)bottomAppAddress;
@property(nonatomic) _Bool crashed; // @synthesize crashed=_crashed;
- (id)description;
- (id)init;
@property(readonly, nonatomic) _Bool isSymbol; // @synthesize isSymbol=_isSymbol;
- (id)jsonObject;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSArray *stackFrames; // @synthesize stackFrames=_stackFrames;
@property(nonatomic) unsigned long long threadID; // @synthesize threadID=_threadID;
@property(nonatomic) unsigned long long threadIndex; // @synthesize threadIndex=_threadIndex;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
- (_Bool)symbolicate;
- (unsigned long long)topAppAddress;

@end

