//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HMDBUCrashDirectory : NSObject
{
}

+ (id)UUID;
+ (id)activeDirectory;
+ (id)baseDirectory;
+ (_Bool)checkAndMarkLaunchState;
+ (id)currentDirectory;
+ (id)eventDirectory;
+ (_Bool)isUrgent;
+ (_Bool)lastTimeCrash;
+ (id)preparedDirectory;
+ (id)processingDirectory;
+ (void)removeLaunchState;
+ (void)setup;
+ (void)setupCurrentFolder;
+ (void)setupDirectory;
+ (void)setupUUID;

@end

