//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "HMDBUCrashKitDelegate-Protocol.h"
#import "HMDBUExcludeModule-Protocol.h"

@class HMDBUCrashDynamicDataProvider, NSString;

@interface HMDBUEmbedCrashTracker : NSObject <HMDBUExcludeModule, HMDBUCrashKitDelegate>
{
    _Bool _finishDetection;
    _Bool _detected;
    _Bool _isRunning;
    NSString *_crashPath;
    double _launchThreshold;
    HMDBUCrashDynamicDataProvider *_dynamicDataProvider;
}

+ (id)excludedModule;
+ (id)sharedTracker;
- (void).cxx_destruct;
- (void)crashKitDidDetectCrashForLastTime:(id)arg1;
@property(retain, nonatomic) NSString *crashPath; // @synthesize crashPath=_crashPath;
- (void)dealloc;
@property(retain, nonatomic) HMDBUCrashDynamicDataProvider *dynamicDataProvider; // @synthesize dynamicDataProvider=_dynamicDataProvider;
- (id)finishDetectionNotification;
- (id)init;
@property(getter=isDetected) _Bool detected; // @synthesize detected=_detected;
@property(getter=isFinishDetection) _Bool finishDetection; // @synthesize finishDetection=_finishDetection;
@property _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(readonly, nonatomic) double launchThreshold; // @synthesize launchThreshold=_launchThreshold;
- (void)notifyCrashDetect;
- (void)start;
- (void)updateSIGPIPEState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

