//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HMDBUCrashInfo, HMDBUCrashReportInfo, NSDictionary;

@interface HMDBUCrashlogProcessor : NSObject
{
    _Bool _needLastCrash;
    HMDBUCrashInfo *_latestCrashInfo;
    NSDictionary *_latestPostData;
    _Bool _needSymbolicate;
    _Bool _needEncrypt;
    double _launchCrashThreshold;
    HMDBUCrashReportInfo *_crashReport;
}

- (void).cxx_destruct;
- (id)crashDetail:(id)arg1;
@property(retain, nonatomic) HMDBUCrashReportInfo *crashReport; // @synthesize crashReport=_crashReport;
- (_Bool)generateCrashlogWithInputDir:(id)arg1 outputPath:(id)arg2;
@property(nonatomic) double launchCrashThreshold; // @synthesize launchCrashThreshold=_launchCrashThreshold;
@property(nonatomic) _Bool needEncrypt; // @synthesize needEncrypt=_needEncrypt;
@property(nonatomic) _Bool needSymbolicate; // @synthesize needSymbolicate=_needSymbolicate;
- (id)parseDynamicInfo:(id)arg1;
- (id)postDataWithCrashInfo:(id)arg1;
- (id)regionDicts:(id)arg1;
- (id)registerAnalysis:(id)arg1;
- (_Bool)shouldIgnorCrashInfo:(id)arg1;
- (id)stackAnalysis:(id)arg1;
- (void)startProcess:(_Bool)arg1;

@end

