//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, UIViewController;

@protocol KSAdSplashInteractDelegate <NSObject>

@optional
- (void)ksad_splashAdClicked;
- (UIViewController *)ksad_splashAdConversionRootVC;
- (void)ksad_splashAdDidShow;
- (void)ksad_splashAdDismiss:(_Bool)arg1;
- (void)ksad_splashAdVideoDidSkipped:(double)arg1;
- (void)ksad_splashAdVideoDidStartPlay;
- (void)ksad_splashAdVideoFailedToPlay:(NSError *)arg1;
@end

