//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class KSInterstitialAd, NSError;

@protocol KSInterstitialAdDelegate <NSObject>

@optional
- (void)ksad_interstitialAd:(KSInterstitialAd *)arg1 didSkip:(double)arg2;
- (void)ksad_interstitialAdDidClick:(KSInterstitialAd *)arg1;
- (void)ksad_interstitialAdDidClose:(KSInterstitialAd *)arg1;
- (void)ksad_interstitialAdDidCloseOtherController:(KSInterstitialAd *)arg1 interactionType:(long long)arg2;
- (void)ksad_interstitialAdDidLoad:(KSInterstitialAd *)arg1;
- (void)ksad_interstitialAdDidVisible:(KSInterstitialAd *)arg1;
- (void)ksad_interstitialAdRenderFail:(KSInterstitialAd *)arg1 error:(NSError *)arg2;
- (void)ksad_interstitialAdRenderSuccess:(KSInterstitialAd *)arg1;
- (void)ksad_interstitialAdWillClose:(KSInterstitialAd *)arg1;
- (void)ksad_interstitialAdWillVisible:(KSInterstitialAd *)arg1;
@end

