//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UIApplicationDelegate-Protocol.h"
#import "UNUserNotificationCenterDelegate-Protocol.h"

@class AFHTTPSessionManager, KSYD_AdvertModel, KSYD_NetworkManager, KSYD_TabBarController, NSString, UIWindow;

@interface KSYD_AppDelegate : UIResponder <UNUserNotificationCenterDelegate, UIApplicationDelegate>
{
    unsigned long long _bgTaskId;
    _Bool _isAppOpen;
    UIWindow *_window;
    KSYD_AdvertModel *_adM;
    KSYD_TabBarController *_tabbar;
    long long _allowRotate;
    long long _netStatus;
    NSString *_test;
    KSYD_NetworkManager *_loginManager;
    KSYD_NetworkManager *_netManager;
    AFHTTPSessionManager *_manager;
}

+ (unsigned long long)backgroundPlayerID:(unsigned long long)arg1;
- (void).cxx_destruct;
- (void)KSYD_BecomeActive;
- (void)KSYD_GetAppConfigInfo;
- (void)KSYD_reloadUser;
- (void)KSYD_setupXHLaunchAdWithStyle:(long long)arg1;
@property(retain, nonatomic) KSYD_AdvertModel *adM; // @synthesize adM=_adM;
- (void)addShaperLayerToWindow;
@property(nonatomic) long long allowRotate; // @synthesize allowRotate=_allowRotate;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)checkInitSDK;
- (void)checkUserNetworkStatus;
- (void)dealwithCrashMessage:(id)arg1;
- (id)getADConfigModelWith:(id)arg1;
- (void)initADSSDK;
- (void)initNativeADSDK;
@property(nonatomic) _Bool isAppOpen; // @synthesize isAppOpen=_isAppOpen;
- (id)launchAdSubViews_alreadyView:(_Bool)arg1;
- (void)load_imageAd_networkDataStyle:(long long)arg1;
- (id)logDic:(id)arg1;
@property(retain, nonatomic) KSYD_NetworkManager *loginManager; // @synthesize loginManager=_loginManager;
@property(retain, nonatomic) AFHTTPSessionManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) KSYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
@property(nonatomic) long long netStatus; // @synthesize netStatus=_netStatus;
@property(retain, nonatomic) KSYD_TabBarController *tabbar; // @synthesize tabbar=_tabbar;
@property(retain, nonatomic) NSString *test; // @synthesize test=_test;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)setupBugly;
- (_Bool)shouldAutorotate;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)xhLaunchAd:(id)arg1 clickAndOpenModel:(id)arg2 clickPoint:(struct CGPoint)arg3;
- (void)xhLaunchAd:(id)arg1 clickAndOpenURLString:(id)arg2;
- (void)xhLaunchAd:(id)arg1 imageDownLoadFinish:(id)arg2;
- (void)xhLaunchAdShowFinish:(id)arg1 clickAndOpenModel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

