//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_BaseViewController.h"

#import "KSYD_AdvertContentViewDelegate-Protocol.h"
#import "SPPageMenuDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class FDDemoScrollView, KSYD_AdvertContentView, NSMutableArray, NSString, SPPageMenu, UISearchBar;

@interface KSYD_SearchContentController : KSYD_BaseViewController <KSYD_AdvertContentViewDelegate, UIScrollViewDelegate, SPPageMenuDelegate>
{
    _Bool _isInTab;
    _Bool _isOpenSecond;
    _Bool _isLoading;
    UISearchBar *_searchBar;
    NSString *_searchKeyWord;
    FDDemoScrollView *_scrollView;
    SPPageMenu *_pageMenu;
    KSYD_AdvertContentView *_topADContentView;
    double _ADViewHeight;
    NSMutableArray *_keyArr;
}

- (void).cxx_destruct;
@property(nonatomic) double ADViewHeight; // @synthesize ADViewHeight=_ADViewHeight;
- (void)KSYD_addChildViewControllers;
- (void)KSYD_buildScorllView;
- (void)KSYD_initInfoADView;
- (void)KSYD_initScrollPage;
- (void)KSYD_setScrollViewY:(double)arg1;
- (void)dealloc;
- (void)deleteADViewWith:(id)arg1 andADHeight:(float)arg2 andSelfView:(id)arg3;
@property(nonatomic) _Bool isInTab; // @synthesize isInTab=_isInTab;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool isOpenSecond; // @synthesize isOpenSecond=_isOpenSecond;
@property(retain, nonatomic) NSMutableArray *keyArr; // @synthesize keyArr=_keyArr;
@property(nonatomic) __weak SPPageMenu *pageMenu; // @synthesize pageMenu=_pageMenu;
- (void)pageMenu:(id)arg1 itemSelectedAtIndex:(long long)arg2;
- (void)pageMenu:(id)arg1 itemSelectedFromIndex:(long long)arg2 toIndex:(long long)arg3;
@property(nonatomic) __weak FDDemoScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchData;
@property(copy, nonatomic) NSString *searchKeyWord; // @synthesize searchKeyWord=_searchKeyWord;
@property(retain, nonatomic) KSYD_AdvertContentView *topADContentView; // @synthesize topADContentView=_topADContentView;
- (void)showADContentWith:(id)arg1 andADHeight:(float)arg2 andIsLoadSuccess:(_Bool)arg3 andSelfView:(id)arg4 andADView:(id)arg5;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

