//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class DALabeledCircularProgressView, KSYD_BookIndexIcon, KSYD_BookStoreMainTypeModel, NSLayoutConstraint, UIImageView, UILabel;

@interface KSYD_BookStoreHeaderCell : UICollectionViewCell
{
    KSYD_BookStoreMainTypeModel *_typeModel;
    KSYD_BookIndexIcon *_iconModel;
    NSLayoutConstraint *_imageTop;
    NSLayoutConstraint *_imageLeft;
    NSLayoutConstraint *_imageRight;
    UIImageView *_mainTypeCover;
    UILabel *_mainTypeNameLabel;
    DALabeledCircularProgressView *_mainTypeProgressView;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(retain, nonatomic) KSYD_BookIndexIcon *iconModel; // @synthesize iconModel=_iconModel;
@property(nonatomic) __weak NSLayoutConstraint *imageLeft; // @synthesize imageLeft=_imageLeft;
@property(nonatomic) __weak NSLayoutConstraint *imageRight; // @synthesize imageRight=_imageRight;
@property(nonatomic) __weak NSLayoutConstraint *imageTop; // @synthesize imageTop=_imageTop;
@property(nonatomic) __weak UIImageView *mainTypeCover; // @synthesize mainTypeCover=_mainTypeCover;
@property(nonatomic) __weak UILabel *mainTypeNameLabel; // @synthesize mainTypeNameLabel=_mainTypeNameLabel;
@property(nonatomic) __weak DALabeledCircularProgressView *mainTypeProgressView; // @synthesize mainTypeProgressView=_mainTypeProgressView;
@property(retain, nonatomic) KSYD_BookStoreMainTypeModel *typeModel; // @synthesize typeModel=_typeModel;

@end

