//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_BaseViewController.h"

#import "UITextViewDelegate-Protocol.h"

@class KSYD_StarRateView, NSString, UILabel, UITextView, UIView;

@interface KSYD_StarCommentController : KSYD_BaseViewController <UITextViewDelegate>
{
    _Bool _isComic;
    _Bool _isLoading;
    double _percentage;
    NSString *_book_id;
    CDUnknownBlockType _SuccessBlock;
    UIView *_contentView;
    KSYD_StarRateView *_star;
    UILabel *_starLabel;
    UITextView *_textView;
}

- (void).cxx_destruct;
- (void)KSYD_buildTitle;
- (void)KSYD_close;
- (void)KSYD_closeTips;
- (void)KSYD_registerForKeyboardNotifications;
@property(copy, nonatomic) CDUnknownBlockType SuccessBlock; // @synthesize SuccessBlock=_SuccessBlock;
@property(copy, nonatomic) NSString *book_id; // @synthesize book_id=_book_id;
- (void)clickComment;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) _Bool isComic; // @synthesize isComic=_isComic;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (void)keyboardWasHidden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
@property(nonatomic) double percentage; // @synthesize percentage=_percentage;
@property(retain, nonatomic) KSYD_StarRateView *star; // @synthesize star=_star;
@property(retain, nonatomic) UILabel *starLabel; // @synthesize starLabel=_starLabel;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

