//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface KSYD_DownTipsView : UIView
{
    _Bool _hideTips;
    NSString *_sureBtnStr;
    NSString *_titleStr;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _cancelBlock;
    UIView *_tipsView;
    NSString *_tips;
}

- (void).cxx_destruct;
- (void)KSYD_buildUI;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
- (void)clickSure;
- (void)disMiss;
@property(nonatomic) _Bool hideTips; // @synthesize hideTips=_hideTips;
- (id)init;
- (id)initWithTips:(id)arg1;
- (id)initWithTips:(id)arg1 title:(id)arg2 sureStr:(id)arg3;
- (id)initWithTips:(id)arg1 title:(id)arg2 sureStr:(id)arg3 hideTips:(_Bool)arg4;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) NSString *sureBtnStr; // @synthesize sureBtnStr=_sureBtnStr;
@property(copy, nonatomic) NSString *tips; // @synthesize tips=_tips;
@property(nonatomic) __weak UIView *tipsView; // @synthesize tipsView=_tipsView;
@property(copy, nonatomic) NSString *titleStr; // @synthesize titleStr=_titleStr;
- (void)show;

@end

