//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KSYD_NetworkManager, NSURLSessionTask;

@interface KSYD_SearchTool : NSObject
{
    NSURLSessionTask *_searchAutoTask;
    KSYD_NetworkManager *_netManager;
}

+ (void)KSYD_clickSearch:(id)arg1;
+ (id)KSYD_lenovoSearchText:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) KSYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
@property(retain, nonatomic) NSURLSessionTask *searchAutoTask; // @synthesize searchAutoTask=_searchAutoTask;
- (void)searchViewController:(id)arg1 didSearchWithsearchBar:(id)arg2 searchText:(id)arg3;

@end

