//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TTTAttributedLabelDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class KSYD_AreaCodeDataModel, KSYD_NetworkManager, KSYD_SQLiteManager, NSArray, NSMutableArray, NSString, NSURLSessionTask, UIButton, UILabel, UITextField;

@interface KSYD_MineCommitViewController : UIViewController <UITextFieldDelegate, TTTAttributedLabelDelegate>
{
    _Bool _isRegst;
    _Bool _isLoading;
    CDUnknownBlockType _successBlock;
    UILabel *_userLabel;
    UILabel *_pwdLabel;
    UITextField *_userTextField;
    UITextField *_pwdTextField;
    UIButton *_landBtn;
    NSMutableArray *_dataArrM;
    KSYD_AreaCodeDataModel *_codeModel;
    UIButton *_areaBtn;
    KSYD_SQLiteManager *_sqliteM;
    NSArray *_booksArr;
    KSYD_NetworkManager *_netManager;
    KSYD_NetworkManager *_shareLoginManager;
    NSURLSessionTask *_loginTask;
    NSURLSessionTask *_UserFavSynTask;
}

- (void).cxx_destruct;
- (void)KSYD_LoginIn:(id)arg1;
- (void)KSYD_UserComicFavSyn;
- (void)KSYD_UserFavSyn;
- (void)KSYD_back;
- (_Bool)KSYD_checkBookInBookCache:(id)arg1 array:(id)arg2;
- (void)KSYD_clickTips;
- (id)KSYD_createLabelWithfont:(id)arg1 textColor:(id)arg2;
- (void)KSYD_forgetClick;
- (void)KSYD_landClick;
- (void)KSYD_regist;
- (void)KSYD_saveHeaderIcon;
- (void)KSYD_saveImage:(id)arg1 withName:(id)arg2;
- (void)KSYD_setHeaderIconView;
- (void)KSYD_setUpubViews;
@property(retain, nonatomic) NSURLSessionTask *UserFavSynTask; // @synthesize UserFavSynTask=_UserFavSynTask;
@property(nonatomic) __weak UIButton *areaBtn; // @synthesize areaBtn=_areaBtn;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
@property(retain, nonatomic) NSArray *booksArr; // @synthesize booksArr=_booksArr;
- (void)buidBtnWithTitle:(id)arg1 image:(id)arg2 frame:(struct CGRect)arg3 action:(SEL)arg4;
- (_Bool)checkIsPhone;
- (void)clickAreaCode;
@property(retain, nonatomic) KSYD_AreaCodeDataModel *codeModel; // @synthesize codeModel=_codeModel;
- (id)createLabelWithfont:(id)arg1 textColor:(id)arg2;
@property(retain, nonatomic) NSMutableArray *dataArrM; // @synthesize dataArrM=_dataArrM;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool isRegst; // @synthesize isRegst=_isRegst;
@property(retain, nonatomic) UIButton *landBtn; // @synthesize landBtn=_landBtn;
@property(retain, nonatomic) NSURLSessionTask *loginTask; // @synthesize loginTask=_loginTask;
@property(retain, nonatomic) KSYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (_Bool)prefersStatusBarHidden;
@property(retain, nonatomic) UILabel *pwdLabel; // @synthesize pwdLabel=_pwdLabel;
@property(retain, nonatomic) UITextField *pwdTextField; // @synthesize pwdTextField=_pwdTextField;
@property(retain, nonatomic) KSYD_NetworkManager *shareLoginManager; // @synthesize shareLoginManager=_shareLoginManager;
@property(retain, nonatomic) KSYD_SQLiteManager *sqliteM; // @synthesize sqliteM=_sqliteM;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(retain, nonatomic) UILabel *userLabel; // @synthesize userLabel=_userLabel;
@property(retain, nonatomic) UITextField *userTextField; // @synthesize userTextField=_userTextField;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidChanged:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)topViewController;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

