//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class KSYD_NetworkManager, KSYD_RankingModel, NSMutableArray, NSString;

@interface KSYD_RankContentViewController : UITableViewController
{
    KSYD_RankingModel *_rankingM;
    NSString *_rankStyle;
    NSMutableArray *_sourceArr;
    KSYD_NetworkManager *_netManager;
}

- (void).cxx_destruct;
- (void)backBtnAction:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)getRankingDetailSource;
- (void)loadData;
@property(retain, nonatomic) KSYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
@property(retain, nonatomic) NSString *rankStyle; // @synthesize rankStyle=_rankStyle;
@property(retain, nonatomic) KSYD_RankingModel *rankingM; // @synthesize rankingM=_rankingM;
@property(retain, nonatomic) NSMutableArray *sourceArr; // @synthesize sourceArr=_sourceArr;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

