//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YBaseModel.h"

@class NSString;

@interface KSYD_RankingDetialModel : YBaseModel
{
    long long _banned;
    NSString *_cat;
    long long _latelyFollower;
    long long _latelyFollowerBase;
    long long _minRetentionRatio;
    NSString *_retentionRatio;
    NSString *_site;
}

- (void).cxx_destruct;
@property(nonatomic) long long banned; // @synthesize banned=_banned;
@property(retain, nonatomic) NSString *cat; // @synthesize cat=_cat;
@property(nonatomic) long long latelyFollower; // @synthesize latelyFollower=_latelyFollower;
@property(nonatomic) long long latelyFollowerBase; // @synthesize latelyFollowerBase=_latelyFollowerBase;
@property(nonatomic) long long minRetentionRatio; // @synthesize minRetentionRatio=_minRetentionRatio;
@property(retain, nonatomic) NSString *retentionRatio; // @synthesize retentionRatio=_retentionRatio;
@property(retain, nonatomic) NSString *site; // @synthesize site=_site;

// Remaining properties
@property(retain, nonatomic) NSString *author;
@property(retain, nonatomic) NSString *shortIntro;
@property(retain, nonatomic) NSString *title;

@end

