//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "KSYD_RewardedVideoAdManagerDelegate-Protocol.h"

@class DMCustomBtn, KSYD_RewardedVideoAdManager, KSYD_SignData, KSYD_SignWeek, NSArray, NSString;

@interface KSYD_SignTipsView : UIView <KSYD_RewardedVideoAdManagerDelegate>
{
    _Bool _rewardFail;
    NSArray *_signArr;
    UIView *_tipsView;
    DMCustomBtn *_closeBtn;
    KSYD_SignData *_model;
    KSYD_SignWeek *_week;
    KSYD_RewardedVideoAdManager *_adManager;
}

- (void).cxx_destruct;
- (void)KSYD_clickSign;
- (void)KSYD_sign;
- (void)RewardedVideoShowSucess:(long long)arg1;
@property(retain, nonatomic) KSYD_RewardedVideoAdManager *adManager; // @synthesize adManager=_adManager;
- (void)buildUI;
@property(retain, nonatomic) DMCustomBtn *closeBtn; // @synthesize closeBtn=_closeBtn;
- (void)disMiss;
- (id)initWithModel:(id)arg1;
@property(retain, nonatomic) KSYD_SignData *model; // @synthesize model=_model;
@property(nonatomic) _Bool rewardFail; // @synthesize rewardFail=_rewardFail;
@property(retain, nonatomic) NSArray *signArr; // @synthesize signArr=_signArr;
@property(retain, nonatomic) UIView *tipsView; // @synthesize tipsView=_tipsView;
@property(retain, nonatomic) KSYD_SignWeek *week; // @synthesize week=_week;
- (void)show;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

