//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionView.h>

#import "KSYD_ComicPageViewCellCellDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDataSourcePrefetching-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class KSYD_ComicChapterEndView, KSYD_ComicChapterManager, KSYD_ComicDownLoadManager, NSIndexPath, NSString, UICollectionReusableView, UICollectionViewFlowLayout, WNYD_ComicReadPageAdView;

@interface KSYD_ConicReadCollectionView : UICollectionView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDataSourcePrefetching, UIScrollViewDelegate, KSYD_ComicPageViewCellCellDelegate>
{
    _Bool _canShowAD;
    _Bool _noNetWorkCacheImage;
    _Bool _isHeaderFail;
    _Bool _isFooterFail;
    _Bool _isRefreshing;
    _Bool _canShowFirst;
    _Bool _canShowLast;
    _Bool _isScrollUp;
    _Bool _isReloadCollectionView;
    _Bool _isReloadBarrage;
    NSIndexPath *_lastIndexPath;
    unsigned long long _scrollDirection;
    double _viewH;
    KSYD_ComicChapterEndView *_chapterEndView;
    WNYD_ComicReadPageAdView *_pageAdView;
    long long _currentChapter;
    KSYD_ComicDownLoadManager *_downLoadManager;
    KSYD_ComicChapterManager *_chapterManager;
    CDUnknownBlockType _infoMessageBlock;
    CDUnknownBlockType _adChangeBlock;
    CDUnknownBlockType _barrageNumBlock;
    CDUnknownBlockType _topTipViewBlock;
    CDUnknownBlockType _lockBlock;
    NSIndexPath *_barrageIndexPath;
    UICollectionViewFlowLayout *_flowLayout;
    UICollectionReusableView *_headerView;
    UICollectionReusableView *_footerView;
    double _lastContentOffset;
}

- (void).cxx_destruct;
- (_Bool)KSYD_canLoadChapter;
- (void)KSYD_cancelBarrageMessage;
- (void)KSYD_cancelLoadChapter;
- (void)KSYD_clickNextPage;
- (void)KSYD_clickPerPage;
- (void)KSYD_collectionViewWillLoadIndex:(long long)arg1 indexPath:(id)arg2;
- (id)KSYD_getRecord;
- (void)KSYD_jumpPageByRecord:(id)arg1;
- (void)KSYD_laodPage:(long long)arg1;
- (void)KSYD_loadCell:(id)arg1 cell:(id)arg2;
- (void)KSYD_loadContent;
- (void)KSYD_loadNextChapter;
- (void)KSYD_loadPreviousChapter;
- (void)KSYD_starBarrageMessage;
- (void)KSYD_stopBarrageMessage;
- (void)KSYD_willLoad;
@property(copy, nonatomic) CDUnknownBlockType adChangeBlock; // @synthesize adChangeBlock=_adChangeBlock;
@property(retain, nonatomic) NSIndexPath *barrageIndexPath; // @synthesize barrageIndexPath=_barrageIndexPath;
@property(copy, nonatomic) CDUnknownBlockType barrageNumBlock; // @synthesize barrageNumBlock=_barrageNumBlock;
- (void)buildData;
@property(nonatomic) _Bool canShowAD; // @synthesize canShowAD=_canShowAD;
@property(nonatomic) _Bool canShowFirst; // @synthesize canShowFirst=_canShowFirst;
@property(nonatomic) _Bool canShowLast; // @synthesize canShowLast=_canShowLast;
@property(nonatomic) __weak KSYD_ComicChapterEndView *chapterEndView; // @synthesize chapterEndView=_chapterEndView;
@property(retain, nonatomic) KSYD_ComicChapterManager *chapterManager; // @synthesize chapterManager=_chapterManager;
- (_Bool)checkIsCancelImage:(long long)arg1 indexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3 isAuto:(_Bool)arg4;
- (void)collectionView:(id)arg1 willDisplaySupplementaryView:(id)arg2 forElementKind:(id)arg3 atIndexPath:(id)arg4;
- (void)collectionViewReloadContentChapter:(id)arg1;
- (void)collectionViewReloadContentPage:(id)arg1;
- (void)collectionViewReloadImagePage:(id)arg1;
- (void)collectionViewReloadPage:(id)arg1;
@property(nonatomic) long long currentChapter; // @synthesize currentChapter=_currentChapter;
- (void)dealloc;
- (void)downLoadImageWithModel:(id)arg1 chapterModel:(id)arg2 indexPath:(id)arg3 cell:(id)arg4;
@property(retain, nonatomic) KSYD_ComicDownLoadManager *downLoadManager; // @synthesize downLoadManager=_downLoadManager;
@property(retain, nonatomic) UICollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) UICollectionReusableView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UICollectionReusableView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) CDUnknownBlockType infoMessageBlock; // @synthesize infoMessageBlock=_infoMessageBlock;
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2 downLoadManager:(id)arg3 chapterManager:(id)arg4;
@property(nonatomic) _Bool isFooterFail; // @synthesize isFooterFail=_isFooterFail;
@property(nonatomic) _Bool isHeaderFail; // @synthesize isHeaderFail=_isHeaderFail;
@property(nonatomic) _Bool isRefreshing; // @synthesize isRefreshing=_isRefreshing;
@property(nonatomic) _Bool isReloadBarrage; // @synthesize isReloadBarrage=_isReloadBarrage;
@property(nonatomic) _Bool isReloadCollectionView; // @synthesize isReloadCollectionView=_isReloadCollectionView;
@property(nonatomic) _Bool isScrollUp; // @synthesize isScrollUp=_isScrollUp;
@property(nonatomic) double lastContentOffset; // @synthesize lastContentOffset=_lastContentOffset;
@property(retain, nonatomic) NSIndexPath *lastIndexPath; // @synthesize lastIndexPath=_lastIndexPath;
@property(copy, nonatomic) CDUnknownBlockType lockBlock; // @synthesize lockBlock=_lockBlock;
@property(nonatomic) _Bool noNetWorkCacheImage; // @synthesize noNetWorkCacheImage=_noNetWorkCacheImage;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
@property(nonatomic) __weak WNYD_ComicReadPageAdView *pageAdView; // @synthesize pageAdView=_pageAdView;
- (void)prefareCellForIndexPath:(id)arg1 chapterModel:(id)arg2;
@property(nonatomic) unsigned long long scrollDirection; // @synthesize scrollDirection=_scrollDirection;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType topTipViewBlock; // @synthesize topTipViewBlock=_topTipViewBlock;
@property(nonatomic) double viewH; // @synthesize viewH=_viewH;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

