//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "KSNativeAdDelegate-Protocol.h"
#import "KSNativeAdsManagerDelegate-Protocol.h"

@class KSNativeAd, KSNativeAdRelatedView, KSNativeAdsManager, KSYD_AdvertConfigModel, KSYD_ReaderSettings, NSMutableArray, NSString, UIButton, UIImageView, UILabel;
@protocol KSYD_KSNativeFeedsViewDelegate;

@interface KSYD_KSNativeFeedsView : UIView <KSNativeAdsManagerDelegate, KSNativeAdDelegate>
{
    KSYD_AdvertConfigModel *_ADModel;
    id <KSYD_KSNativeFeedsViewDelegate> _mydelegate;
    KSYD_ReaderSettings *_settings;
    KSNativeAdRelatedView *_relatedView;
    KSNativeAdsManager *_nativeAdsManager;
    KSNativeAd *_dataObject;
    NSString *_ADKey;
    NSMutableArray *_expressAdViews;
    UIButton *_clickButton;
    UILabel *_logoLabel;
    UILabel *_descriptionLabel;
    UIImageView *_logoImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *ADKey; // @synthesize ADKey=_ADKey;
@property(retain, nonatomic) KSYD_AdvertConfigModel *ADModel; // @synthesize ADModel=_ADModel;
@property(retain, nonatomic) UIButton *clickButton; // @synthesize clickButton=_clickButton;
@property(retain, nonatomic) KSNativeAd *dataObject; // @synthesize dataObject=_dataObject;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) NSMutableArray *expressAdViews; // @synthesize expressAdViews=_expressAdViews;
- (id)getRootNavController;
- (void)initNativeBanner;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UILabel *logoLabel; // @synthesize logoLabel=_logoLabel;
@property(nonatomic) __weak id <KSYD_KSNativeFeedsViewDelegate> mydelegate; // @synthesize mydelegate=_mydelegate;
- (void)nativeAd:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdDidBecomeVisible:(id)arg1;
- (void)nativeAdDidClick:(id)arg1 withView:(id)arg2;
- (void)nativeAdDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (void)nativeAdDidLoad:(id)arg1;
- (void)nativeAdDidShowOtherController:(id)arg1 interactionType:(long long)arg2;
@property(retain, nonatomic) KSNativeAdsManager *nativeAdsManager; // @synthesize nativeAdsManager=_nativeAdsManager;
- (void)nativeAdsManager:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdsManagerSuccessToLoad:(id)arg1 nativeAds:(id)arg2;
@property(retain, nonatomic) KSNativeAdRelatedView *relatedView; // @synthesize relatedView=_relatedView;
@property(retain, nonatomic) KSYD_ReaderSettings *settings; // @synthesize settings=_settings;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

