//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

#import "KSYD_ComicPageTableCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CADisplayLink, KSYD_ComicChapterEndView, KSYD_ComicChapterManager, KSYD_ComicDownLoadManager, NSIndexPath, NSMutableArray, NSString, UIView, WNYD_ComicReadPageAdView;

@interface KSYD_ComicReadTableView : UITableView <UITableViewDelegate, UITableViewDataSource, KSYD_ComicPageTableCellDelegate>
{
    _Bool _canShowAD;
    _Bool _noNetWorkCacheImage;
    _Bool _isSrollviewFast;
    _Bool _isReloadTableView;
    _Bool _isHeaderFail;
    _Bool _isFooterFail;
    _Bool _isScrollUp;
    _Bool _isRefreshing;
    _Bool _canShowFirst;
    _Bool _canShowLast;
    _Bool _isReloadBarrage;
    NSIndexPath *_lastIndexPath;
    double _viewH;
    KSYD_ComicChapterEndView *_chapterEndView;
    WNYD_ComicReadPageAdView *_pageAdView;
    long long _currentChapter;
    KSYD_ComicDownLoadManager *_downLoadManager;
    KSYD_ComicChapterManager *_chapterManager;
    CDUnknownBlockType _infoMessageBlock;
    CDUnknownBlockType _adChangeBlock;
    CDUnknownBlockType _barrageNumBlock;
    CDUnknownBlockType _topTipViewBlock;
    CDUnknownBlockType _lockBlock;
    NSIndexPath *_barrageIndexPath;
    UIView *_footerView;
    NSMutableArray *_needLoadArr;
    double _scrolliewY;
    double _lastY;
    double _lastContentOffset;
    CADisplayLink *_autoLink;
    long long _autoSpeech;
}

- (void).cxx_destruct;
- (void)CalCulateLocationWithScrollViewY:(id)arg1;
- (void)CalCulateLocationWithScrollViewY:(id)arg1 isScroll:(_Bool)arg2;
- (void)KSYD_AutoRead:(id)arg1;
- (_Bool)KSYD_canLoadChapter;
- (void)KSYD_cancelBarrageMessage;
- (void)KSYD_cancelLoadChapter;
- (_Bool)KSYD_checkCanScroll:(long long)arg1 row:(long long)arg2;
- (void)KSYD_clickNextPage;
- (void)KSYD_clickPerPage;
- (id)KSYD_getRecord;
- (void)KSYD_jumpPageByRecord:(id)arg1;
- (void)KSYD_laodPage:(long long)arg1;
- (void)KSYD_loadCell:(id)arg1 cell:(id)arg2;
- (void)KSYD_loadContent;
- (void)KSYD_loadNextChapter;
- (void)KSYD_loadPreviousChapter;
- (void)KSYD_starBarrageMessage;
- (void)KSYD_stopBarrageMessage;
- (void)KSYD_tableViewWillLoadIndex:(long long)arg1 indexPath:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType adChangeBlock; // @synthesize adChangeBlock=_adChangeBlock;
@property(retain, nonatomic) CADisplayLink *autoLink; // @synthesize autoLink=_autoLink;
@property(nonatomic) long long autoSpeech; // @synthesize autoSpeech=_autoSpeech;
@property(retain, nonatomic) NSIndexPath *barrageIndexPath; // @synthesize barrageIndexPath=_barrageIndexPath;
@property(copy, nonatomic) CDUnknownBlockType barrageNumBlock; // @synthesize barrageNumBlock=_barrageNumBlock;
- (void)buildData;
@property(nonatomic) _Bool canShowAD; // @synthesize canShowAD=_canShowAD;
@property(nonatomic) _Bool canShowFirst; // @synthesize canShowFirst=_canShowFirst;
@property(nonatomic) _Bool canShowLast; // @synthesize canShowLast=_canShowLast;
@property(nonatomic) __weak KSYD_ComicChapterEndView *chapterEndView; // @synthesize chapterEndView=_chapterEndView;
@property(retain, nonatomic) KSYD_ComicChapterManager *chapterManager; // @synthesize chapterManager=_chapterManager;
- (_Bool)checkIsCancelImage:(long long)arg1 indexPath:(id)arg2;
@property(nonatomic) long long currentChapter; // @synthesize currentChapter=_currentChapter;
- (void)dealloc;
- (void)downLoadImageWithModel:(id)arg1 chapterModel:(id)arg2 indexPath:(id)arg3 cell:(id)arg4;
- (void)downLoadImageWithModel:(id)arg1 chapterModel:(id)arg2 indexPath:(id)arg3 cell:(id)arg4 isPreLoad:(_Bool)arg5;
@property(retain, nonatomic) KSYD_ComicDownLoadManager *downLoadManager; // @synthesize downLoadManager=_downLoadManager;
- (void)drawCell:(id)arg1 withIndexPath:(id)arg2 isLoadMoreImage:(_Bool)arg3;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType infoMessageBlock; // @synthesize infoMessageBlock=_infoMessageBlock;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2 downLoadManager:(id)arg3 chapterManager:(id)arg4;
@property(nonatomic) _Bool isFooterFail; // @synthesize isFooterFail=_isFooterFail;
@property(nonatomic) _Bool isHeaderFail; // @synthesize isHeaderFail=_isHeaderFail;
@property(nonatomic) _Bool isRefreshing; // @synthesize isRefreshing=_isRefreshing;
@property(nonatomic) _Bool isReloadBarrage; // @synthesize isReloadBarrage=_isReloadBarrage;
@property(nonatomic) _Bool isReloadTableView; // @synthesize isReloadTableView=_isReloadTableView;
@property(nonatomic) _Bool isScrollUp; // @synthesize isScrollUp=_isScrollUp;
@property(nonatomic) _Bool isSrollviewFast; // @synthesize isSrollviewFast=_isSrollviewFast;
@property(nonatomic) double lastContentOffset; // @synthesize lastContentOffset=_lastContentOffset;
@property(retain, nonatomic) NSIndexPath *lastIndexPath; // @synthesize lastIndexPath=_lastIndexPath;
@property(nonatomic) double lastY; // @synthesize lastY=_lastY;
@property(copy, nonatomic) CDUnknownBlockType lockBlock; // @synthesize lockBlock=_lockBlock;
@property(retain, nonatomic) NSMutableArray *needLoadArr; // @synthesize needLoadArr=_needLoadArr;
@property(nonatomic) _Bool noNetWorkCacheImage; // @synthesize noNetWorkCacheImage=_noNetWorkCacheImage;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) __weak WNYD_ComicReadPageAdView *pageAdView; // @synthesize pageAdView=_pageAdView;
- (void)prefareCellForIndexPath:(id)arg1 chapterModel:(id)arg2;
- (void)remove;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
@property(nonatomic) double scrolliewY; // @synthesize scrolliewY=_scrolliewY;
@property(copy, nonatomic) CDUnknownBlockType topTipViewBlock; // @synthesize topTipViewBlock=_topTipViewBlock;
@property(nonatomic) double viewH; // @synthesize viewH=_viewH;
- (void)starRead;
- (void)startAuto;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 isAuto:(_Bool)arg4;
- (void)tableView:(id)arg1 willDisplayFooterView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (void)tableViewReloadContentChapter:(id)arg1;
- (void)tableViewReloadContentPage:(id)arg1;
- (void)tableViewReloadImagePage:(id)arg1;
- (void)tableViewReloadPage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

