//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface KSYD_SigninData : NSObject
{
    _Bool _isDouble;
    _Bool _isSevenDay;
    long long _min;
    long long _double_min;
    NSString *_service_datetime;
    NSString *_ad_end_datetime;
    NSString *_msg;
    long long _min7;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *ad_end_datetime; // @synthesize ad_end_datetime=_ad_end_datetime;
@property(nonatomic) long long double_min; // @synthesize double_min=_double_min;
@property(nonatomic) _Bool isDouble; // @synthesize isDouble=_isDouble;
@property(nonatomic) _Bool isSevenDay; // @synthesize isSevenDay=_isSevenDay;
@property(nonatomic) long long min; // @synthesize min=_min;
@property(nonatomic) long long min7; // @synthesize min7=_min7;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(copy, nonatomic) NSString *service_datetime; // @synthesize service_datetime=_service_datetime;

@end

