//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KSYD_URLManager : NSObject
{
}

+ (id)encodeToPercentEscapeString:(id)arg1;
+ (id)getNowDoMain;
+ (id)getURLKSYD_With:(long long)arg1 parameter:(id)arg2;
+ (long long)searchType;

@end

