//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KSYD_BookIndexDataModel, NSArray, NSString;

@interface KSYD_BookIndexData : NSObject
{
    KSYD_BookIndexDataModel *_top_book;
    KSYD_BookIndexDataModel *_end_book;
    KSYD_BookIndexDataModel *_hot_book;
    KSYD_BookIndexDataModel *_theNew_book;
    KSYD_BookIndexDataModel *_view_book;
    KSYD_BookIndexDataModel *_week_book;
    KSYD_BookIndexDataModel *_added_book;
    KSYD_BookIndexDataModel *_search;
    KSYD_BookIndexDataModel *_recommend;
    NSString *_image;
    NSArray *_banner;
    NSArray *_icon;
}

+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
- (void).cxx_destruct;
@property(retain, nonatomic) KSYD_BookIndexDataModel *added_book; // @synthesize added_book=_added_book;
@property(copy, nonatomic) NSArray *banner; // @synthesize banner=_banner;
@property(retain, nonatomic) KSYD_BookIndexDataModel *end_book; // @synthesize end_book=_end_book;
@property(retain, nonatomic) KSYD_BookIndexDataModel *hot_book; // @synthesize hot_book=_hot_book;
@property(retain, nonatomic) NSArray *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) KSYD_BookIndexDataModel *recommend; // @synthesize recommend=_recommend;
@property(retain, nonatomic) KSYD_BookIndexDataModel *search; // @synthesize search=_search;
@property(retain, nonatomic) KSYD_BookIndexDataModel *theNew_book; // @synthesize theNew_book=_theNew_book;
@property(retain, nonatomic) KSYD_BookIndexDataModel *top_book; // @synthesize top_book=_top_book;
@property(retain, nonatomic) KSYD_BookIndexDataModel *view_book; // @synthesize view_book=_view_book;
@property(retain, nonatomic) KSYD_BookIndexDataModel *week_book; // @synthesize week_book=_week_book;

@end

