//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KSYD_ComicBookTool : NSObject
{
}

+ (void)KSYD_goDetailByBookId:(id)arg1 form:(long long)arg2 nav:(id)arg3;

@end

