//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KSYD_BookSummaryModel, KSYD_DataBaseManager;

@interface KSYD_BookSummaryDataManager : NSObject
{
    KSYD_DataBaseManager *_manager;
    KSYD_BookSummaryModel *_summaryModel;
}

+ (id)instance;
- (void).cxx_destruct;
- (_Bool)createBookSummaryTableWithBookDetailModel:(id)arg1;
- (void)deleteAllObjectsFromBookSummary:(id)arg1 andBookDetailModel:(id)arg2;
- (_Bool)deleteBookSummayTableWithBookModel:(id)arg1;
- (void)deleteObjectsFromBookSummaryWithBookDetailModel:(id)arg1 andSummaryModel:(id)arg2;
- (void)deleteOneObjectFromBookSummaryWIthBookDetailModel:(id)arg1 andSummaryModel:(id)arg2;
- (id)getAllObjectsFromBookSummaryBySelect:(id)arg1 andBookDetailModel:(id)arg2;
- (id)getAllObjectsFromBookSummaryByUpdate:(id)arg1 andBookDetailModel:(id)arg2;
- (unsigned long long)getFileSizeWithBookModel:(id)arg1;
- (id)getOneObjectFromBookSummaryModelWithBookDetailModel:(id)arg1;
- (id)getPathsWithBookModel:(id)arg1;
- (id)insertObjectsIntoBookSummaryModelWithSummaryArr:(id)arg1 andBookDetailModel:(id)arg2;
- (id)insertSelectObjectIntoBookSummaryWithSelectModel:(id)arg1 andBookDetailModel:(id)arg2;
@property(retain, nonatomic) KSYD_DataBaseManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) KSYD_BookSummaryModel *summaryModel; // @synthesize summaryModel=_summaryModel;

@end

