//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_BaseViewController.h"

#import "KSYD_RewardedVideoAdManagerDelegate-Protocol.h"

@class DMCustomBtn, KSYD_BottomButton, KSYD_DownloadManager, KSYD_MenuSettingView, KSYD_NetworkManager, KSYD_OtherRewardVideoAdManager, KSYD_ReaderManager, KSYD_ReaderSettings, KSYD_RewardedVideoAdManager, NSArray, NSLayoutConstraint, NSString, NSURLSessionTask, UIButton, UILabel, UISlider, UIView, YBookDetailModel;
@protocol KSYD_MenuViewControllerDelegate;

@interface KSYD_MenuViewController : KSYD_BaseViewController <KSYD_RewardedVideoAdManagerDelegate>
{
    _Bool _isNowSpeaking;
    _Bool _isListen;
    NSArray *_themeArr;
    CDUnknownBlockType _menuTapAction;
    CDUnknownBlockType _selectChapterBlock;
    long long _totalCount;
    long long _currentChapter;
    NSString *_book_id;
    UIButton *_sourceBtn;
    id <KSYD_MenuViewControllerDelegate> _mydelegate;
    KSYD_ReaderManager *_readerManager;
    UIView *_topView;
    UIButton *_topWebBtn;
    UIButton *_voiceBtn;
    UIButton *_messageBtn;
    UIView *_topWebView;
    UIButton *_menuBtn;
    NSLayoutConstraint *_topWebViewTop;
    UIView *_bottomView;
    UIView *_bgView;
    UIView *_downloadView;
    UILabel *_downloadLabel;
    NSLayoutConstraint *_bottomViewBottom;
    NSLayoutConstraint *_downloadViewBottom;
    NSLayoutConstraint *_topViewTop;
    NSLayoutConstraint *_topViewHeight;
    NSLayoutConstraint *_bottomViewHeight;
    NSLayoutConstraint *_moreCenterTop;
    NSLayoutConstraint *_bgViewBottom;
    KSYD_BottomButton *_settingBtn;
    KSYD_DownloadManager *_downloadManager;
    YBookDetailModel *_downloadBook;
    KSYD_ReaderSettings *_settings;
    long long _selectTheme;
    KSYD_BottomButton *_msgBtn;
    KSYD_BottomButton *_dayNightBtn;
    KSYD_NetworkManager *_netManager;
    NSURLSessionTask *_bookFeedTask;
    UIButton *_adButton;
    UISlider *_chapterSlider;
    UIView *_chapterView;
    UILabel *_chapterLabel;
    UILabel *_percentage;
    long long _lastChapterIndex;
    UIButton *_capBtn;
    UIView *_menuView;
    KSYD_MenuSettingView *_setScrollView;
    UIButton *_changeSource;
    UIView *_nightBtn;
    UIView *_addBookBtn;
    UIButton *_listenBtn;
    UIButton *_souBtn;
    UIView *_adBtn;
    DMCustomBtn *_adTipsBtn;
    KSYD_RewardedVideoAdManager *_adManager;
    KSYD_OtherRewardVideoAdManager *_otherAdManager;
    KSYD_OtherRewardVideoAdManager *_otherManager;
}

- (void).cxx_destruct;
- (void)KSYD_FreeADTips;
- (void)KSYD_NoAdDownloadBook;
- (void)KSYD_addShaperLayerToWindow;
- (void)KSYD_bookFeed:(id)arg1;
- (void)KSYD_changeColor;
- (void)KSYD_clickADBtn;
- (void)KSYD_clickDarkBtn:(id)arg1;
- (void)KSYD_downloadBook;
- (void)KSYD_downloadChpatersWith:(long long)arg1;
- (void)KSYD_downloadStatusViewCheckShow;
- (double)KSYD_getStringW:(id)arg1;
- (void)KSYD_hideAddBtn:(_Bool)arg1;
- (void)KSYD_hideDownloadView;
- (void)KSYD_hideMenuLFView;
- (void)KSYD_hideSettingView;
- (void)KSYD_hideSettingViewWithDown:(_Bool)arg1;
- (void)KSYD_removeLayerToWindow;
- (void)KSYD_setDownloadBookCallback;
- (void)KSYD_setupBottomViewUI;
- (void)KSYD_showCapterView;
- (void)KSYD_showChangeSource;
- (void)KSYD_showDownloadView;
- (void)KSYD_showMenuView;
- (void)KSYD_showSettingLeadView;
- (void)KSYD_showSettingView;
- (void)KSYD_showfeedLFView;
- (void)KSYD_updateBadge;
- (void)KSYD_updateBright;
- (void)KSYD_updateNightAndDay;
- (void)KSYD_updateRewardVideoTime;
- (id)KSYD_webSiteCheck;
- (id)OriginImage:(id)arg1 scaleToSize:(struct CGSize)arg2;
- (void)RewardedVideoShowSucess:(long long)arg1;
@property(nonatomic) __weak UIView *adBtn; // @synthesize adBtn=_adBtn;
@property(nonatomic) __weak UIButton *adButton; // @synthesize adButton=_adButton;
@property(retain, nonatomic) KSYD_RewardedVideoAdManager *adManager; // @synthesize adManager=_adManager;
@property(nonatomic) __weak DMCustomBtn *adTipsBtn; // @synthesize adTipsBtn=_adTipsBtn;
@property(nonatomic) __weak UIView *addBookBtn; // @synthesize addBookBtn=_addBookBtn;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak NSLayoutConstraint *bgViewBottom; // @synthesize bgViewBottom=_bgViewBottom;
@property(retain, nonatomic) NSURLSessionTask *bookFeedTask; // @synthesize bookFeedTask=_bookFeedTask;
@property(copy, nonatomic) NSString *book_id; // @synthesize book_id=_book_id;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak NSLayoutConstraint *bottomViewBottom; // @synthesize bottomViewBottom=_bottomViewBottom;
@property(nonatomic) __weak NSLayoutConstraint *bottomViewHeight; // @synthesize bottomViewHeight=_bottomViewHeight;
- (void)btnLayer:(id)arg1;
@property(nonatomic) __weak UIButton *capBtn; // @synthesize capBtn=_capBtn;
@property(nonatomic) __weak UIButton *changeSource; // @synthesize changeSource=_changeSource;
@property(nonatomic) __weak UILabel *chapterLabel; // @synthesize chapterLabel=_chapterLabel;
@property(nonatomic) __weak UISlider *chapterSlider; // @synthesize chapterSlider=_chapterSlider;
- (void)chapterSliderAction:(id)arg1 forEvent:(id)arg2;
@property(nonatomic) __weak UIView *chapterView; // @synthesize chapterView=_chapterView;
- (void)checkSpeeckADTips;
- (void)clickAddBookBtn:(id)arg1;
- (void)clickCapterBtn:(id)arg1;
- (void)clickChapterViewBtn;
- (void)clickReturnBtn;
- (void)clickSlider:(id)arg1;
- (id)colorWithBg;
@property(nonatomic) long long currentChapter; // @synthesize currentChapter=_currentChapter;
@property(retain, nonatomic) KSYD_BottomButton *dayNightBtn; // @synthesize dayNightBtn=_dayNightBtn;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
@property(retain, nonatomic) YBookDetailModel *downloadBook; // @synthesize downloadBook=_downloadBook;
@property(nonatomic) __weak UILabel *downloadLabel; // @synthesize downloadLabel=_downloadLabel;
@property(retain, nonatomic) KSYD_DownloadManager *downloadManager; // @synthesize downloadManager=_downloadManager;
@property(nonatomic) __weak UIView *downloadView; // @synthesize downloadView=_downloadView;
@property(nonatomic) __weak NSLayoutConstraint *downloadViewBottom; // @synthesize downloadViewBottom=_downloadViewBottom;
- (void)enterBackgroundNotification;
- (id)formatFloat:(float)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (long long)getMaxChapterCount;
- (id)getNewColorWith:(id)arg1;
- (void)handleButton:(id)arg1;
@property(nonatomic) _Bool isListen; // @synthesize isListen=_isListen;
@property(nonatomic) _Bool isNowSpeaking; // @synthesize isNowSpeaking=_isNowSpeaking;
@property(nonatomic) long long lastChapterIndex; // @synthesize lastChapterIndex=_lastChapterIndex;
@property(nonatomic) __weak UIButton *listenBtn; // @synthesize listenBtn=_listenBtn;
- (void)memuAction:(id)arg1;
@property(nonatomic) __weak UIButton *menuBtn; // @synthesize menuBtn=_menuBtn;
@property(copy, nonatomic) CDUnknownBlockType menuTapAction; // @synthesize menuTapAction=_menuTapAction;
@property(nonatomic) __weak UIView *menuView; // @synthesize menuView=_menuView;
@property(nonatomic) __weak UIButton *messageBtn; // @synthesize messageBtn=_messageBtn;
- (id)moreActions;
@property(nonatomic) __weak NSLayoutConstraint *moreCenterTop; // @synthesize moreCenterTop=_moreCenterTop;
@property(retain, nonatomic) KSYD_BottomButton *msgBtn; // @synthesize msgBtn=_msgBtn;
@property(nonatomic) __weak id <KSYD_MenuViewControllerDelegate> mydelegate; // @synthesize mydelegate=_mydelegate;
@property(retain, nonatomic) KSYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
@property(nonatomic) __weak UIView *nightBtn; // @synthesize nightBtn=_nightBtn;
@property(retain, nonatomic) KSYD_OtherRewardVideoAdManager *otherAdManager; // @synthesize otherAdManager=_otherAdManager;
@property(retain, nonatomic) KSYD_OtherRewardVideoAdManager *otherManager; // @synthesize otherManager=_otherManager;
@property(nonatomic) __weak UILabel *percentage; // @synthesize percentage=_percentage;
@property(retain, nonatomic) KSYD_ReaderManager *readerManager; // @synthesize readerManager=_readerManager;
- (void)resetListenTime;
- (void)resetSpaceTime;
- (void)restetDownloadTime;
@property(copy, nonatomic) CDUnknownBlockType selectChapterBlock; // @synthesize selectChapterBlock=_selectChapterBlock;
@property(nonatomic) long long selectTheme; // @synthesize selectTheme=_selectTheme;
@property(nonatomic) __weak KSYD_MenuSettingView *setScrollView; // @synthesize setScrollView=_setScrollView;
@property(retain, nonatomic) KSYD_BottomButton *settingBtn; // @synthesize settingBtn=_settingBtn;
@property(retain, nonatomic) KSYD_ReaderSettings *settings; // @synthesize settings=_settings;
@property(nonatomic) __weak UIButton *souBtn; // @synthesize souBtn=_souBtn;
@property(nonatomic) __weak UIButton *sourceBtn; // @synthesize sourceBtn=_sourceBtn;
@property(retain, nonatomic) NSArray *themeArr; // @synthesize themeArr=_themeArr;
@property(nonatomic) __weak UIView *topView; // @synthesize topView=_topView;
@property(nonatomic) __weak NSLayoutConstraint *topViewHeight; // @synthesize topViewHeight=_topViewHeight;
@property(nonatomic) __weak NSLayoutConstraint *topViewTop; // @synthesize topViewTop=_topViewTop;
@property(nonatomic) __weak UIButton *topWebBtn; // @synthesize topWebBtn=_topWebBtn;
@property(nonatomic) __weak UIView *topWebView; // @synthesize topWebView=_topWebView;
@property(nonatomic) __weak NSLayoutConstraint *topWebViewTop; // @synthesize topWebViewTop=_topWebViewTop;
@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
@property(nonatomic) __weak UIButton *voiceBtn; // @synthesize voiceBtn=_voiceBtn;
- (void)showListenIsLookVideo:(_Bool)arg1;
- (void)sliderTouchUpInSide:(id)arg1;
- (id)textColor;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

