//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface KSYD_ReaderSQLiteManager : NSObject
{
    NSString *_documentFolder;
}

+ (id)shareManager;
- (void).cxx_destruct;
- (long long)KSYD_GetReadTime;
- (long long)KSYD_GetReadTimeKey:(id)arg1;
- (_Bool)KSYD_IsCanSendReaderSettingWithbook_id:(id)arg1;
- (void)KSYD_saveReadTime;
- (void)KSYD_saveReadTimeKey:(id)arg1;
- (void)KSYD_updateReadTimeWithTime:(long long)arg1;
- (void)KSYD_updateReadTimeWithTime:(long long)arg1 key:(id)arg2;
- (void)KSYD_updateReaderingWithBook:(id)arg1;
@property(retain, nonatomic) NSString *documentFolder; // @synthesize documentFolder=_documentFolder;
- (id)init;

@end

