//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class KSYD_AdvertModel, UIImageView, UILabel;

@interface KSYD_ShelfADCell : UITableViewCell
{
    KSYD_AdvertModel *_advertModel;
    UIImageView *_advertImage;
    UILabel *_advertTitle;
    UILabel *_advertDes;
    UIImageView *_advertMark;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *advertDes; // @synthesize advertDes=_advertDes;
@property(nonatomic) __weak UIImageView *advertImage; // @synthesize advertImage=_advertImage;
@property(nonatomic) __weak UIImageView *advertMark; // @synthesize advertMark=_advertMark;
@property(retain, nonatomic) KSYD_AdvertModel *advertModel; // @synthesize advertModel=_advertModel;
@property(nonatomic) __weak UILabel *advertTitle; // @synthesize advertTitle=_advertTitle;
- (void)awakeFromNib;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;

@end

