//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, YYCache;

@interface KSYD_SQLiteManager : NSObject
{
    YYCache *_cache;
    NSArray *_userBooks;
    NSString *_documentFolder;
}

+ (id)shareManager;
- (void).cxx_destruct;
- (void)KSYD_updateBookSummaryWith:(id)arg1 summaryM:(id)arg2;
- (void)RefreshBookShelfData;
- (id)addUserBooksArrWith:(id)arg1;
- (id)addUserBooksWith:(id)arg1;
@property(retain, nonatomic) YYCache *cache; // @synthesize cache=_cache;
- (void)deleteBookCacheWith:(id)arg1;
- (void)deleteBookWith:(id)arg1;
@property(retain, nonatomic) NSString *documentFolder; // @synthesize documentFolder=_documentFolder;
- (void)fattenUserBookWith:(id)arg1;
- (id)fattenUserBooksWith:(id)arg1;
- (id)getBookShelfBooksArr;
- (id)getBookSummaryWith:(id)arg1;
- (id)getHistorySearchTextArray;
- (id)getReaderConfigSetting;
- (id)init;
- (void)removeAllBook;
- (id)reorderUserBooksWith:(id)arg1;
- (void)saveReaderConfigWith:(id)arg1;
@property(copy, nonatomic) NSArray *userBooks; // @synthesize userBooks=_userBooks;
- (void)stickyUserBookWith:(id)arg1;
- (void)updateBookShelfStatus;
- (void)updateHistorySearchTextArrayWith:(id)arg1;

@end

