//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class KSYD_ScrollBar;

@protocol KSYD_ScrollBarDelegate <NSObject>
- (void)scrollBarDidScroll:(KSYD_ScrollBar *)arg1;
- (void)scrollBarTouchAction:(KSYD_ScrollBar *)arg1;
@end

