//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_TaskCenterBaseModel.h"

@class KSYD_ClassifyDataModel;

@interface KSYD_ClassifyModel : KSYD_TaskCenterBaseModel
{
    KSYD_ClassifyDataModel *_data;
}

- (void).cxx_destruct;
@property(retain, nonatomic) KSYD_ClassifyDataModel *data; // @synthesize data=_data;

@end

