//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_BaseViewController.h"

#import "KSYD_AdvertContentViewDelegate-Protocol.h"
#import "SPPageMenuDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class BUNativeExpressInterstitialAd, DMCustomBtn, GDTUnifiedInterstitialAd, KSYD_AdvertConfigModel, KSYD_AdvertContentView, NSArray, NSString, SPPageMenu, UIScrollView;

@interface KSYD_BookSelfContentController : KSYD_BaseViewController <KSYD_AdvertContentViewDelegate, UIScrollViewDelegate, SPPageMenuDelegate>
{
    _Bool _isOpenSecond;
    _Bool _isLoading;
    _Bool _isFirstShowTips;
    _Bool _isShowTips;
    _Bool _canShowTips;
    UIScrollView *_scrollView;
    SPPageMenu *_pageMenu;
    double _ADViewHeight;
    BUNativeExpressInterstitialAd *_interstitialAd;
    GDTUnifiedInterstitialAd *_interstitial;
    KSYD_AdvertConfigModel *_BubbleModel;
    KSYD_AdvertContentView *_topADContentView;
    NSString *_type;
    DMCustomBtn *_cleanButton;
    NSArray *_titleArr;
}

- (void).cxx_destruct;
@property(nonatomic) double ADViewHeight; // @synthesize ADViewHeight=_ADViewHeight;
- (void)BookShelfRecBookLoad;
@property(retain, nonatomic) KSYD_AdvertConfigModel *BubbleModel; // @synthesize BubbleModel=_BubbleModel;
- (void)KSYD_GetAppConfigInfo;
- (void)KSYD_addChildViewControllers;
- (void)KSYD_buildConfig;
- (void)KSYD_buildScorllView;
- (void)KSYD_clickEditBook;
- (void)KSYD_clickHistory;
- (void)KSYD_clickMoreUserData:(id)arg1;
- (void)KSYD_clickSearch;
- (void)KSYD_comicChange;
- (void)KSYD_initInfoADView;
- (void)KSYD_initIntersTitialAD;
- (void)KSYD_initScrollPage;
- (void)KSYD_intolastReadBook:(id)arg1;
- (void)KSYD_refreshBookShelfView:(long long)arg1;
- (void)KSYD_setScrollViewY:(double)arg1;
- (void)KSYD_showReviewAlert;
- (void)KSYD_showSignTips;
- (void)KSYD_showSignView;
- (void)RefreshBookShelfView;
@property(nonatomic) _Bool canShowTips; // @synthesize canShowTips=_canShowTips;
- (void)changeNavColor;
@property(retain, nonatomic) DMCustomBtn *cleanButton; // @synthesize cleanButton=_cleanButton;
- (void)dealloc;
- (void)deleteADViewWith:(id)arg1 andADHeight:(float)arg2 andSelfView:(id)arg3;
@property(retain, nonatomic) GDTUnifiedInterstitialAd *interstitial; // @synthesize interstitial=_interstitial;
@property(retain, nonatomic) BUNativeExpressInterstitialAd *interstitialAd; // @synthesize interstitialAd=_interstitialAd;
@property(nonatomic) _Bool isFirstShowTips; // @synthesize isFirstShowTips=_isFirstShowTips;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool isOpenSecond; // @synthesize isOpenSecond=_isOpenSecond;
@property(nonatomic) _Bool isShowTips; // @synthesize isShowTips=_isShowTips;
- (void)launchSplashAd:(id)arg1;
- (void)nativeExpresInterstitialAd:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeExpresInterstitialAdDidClick:(id)arg1;
- (void)nativeExpresInterstitialAdDidClose:(id)arg1;
- (void)nativeExpresInterstitialAdRenderFail:(id)arg1 error:(id)arg2;
- (void)nativeExpresInterstitialAdRenderSuccess:(id)arg1;
- (void)nativeExpresInterstitialAdWillClose:(id)arg1;
- (void)nativeExpresInterstitialAdWillVisible:(id)arg1;
@property(nonatomic) __weak SPPageMenu *pageMenu; // @synthesize pageMenu=_pageMenu;
- (void)pageMenu:(id)arg1 itemSelectedAtIndex:(long long)arg2;
- (void)pageMenu:(id)arg1 itemSelectedFromIndex:(long long)arg2 toIndex:(long long)arg3;
- (_Bool)prefersStatusBarHidden;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)setTableViewY:(double)arg1;
@property(copy, nonatomic) NSArray *titleArr; // @synthesize titleArr=_titleArr;
@property(retain, nonatomic) KSYD_AdvertContentView *topADContentView; // @synthesize topADContentView=_topADContentView;
@property(nonatomic) NSString *type; // @synthesize type=_type;
- (void)showADContentWith:(id)arg1 andADHeight:(float)arg2 andIsLoadSuccess:(_Bool)arg3 andSelfView:(id)arg4 andADView:(id)arg5;
- (void)showTipsView;
- (void)traitCollectionDidChange:(id)arg1;
- (void)unifiedInterstitialDidDismissScreen:(id)arg1;
- (void)unifiedInterstitialDidPresentScreen:(id)arg1;
- (void)unifiedInterstitialFailToLoadAd:(id)arg1 error:(id)arg2;
- (void)unifiedInterstitialSuccessToLoadAd:(id)arg1;
- (void)unifiedInterstitialWillPresentScreen:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

