//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YZDisplayViewController.h"

@class KSYD_RankingModel;

@interface KSYD_RankScrollViewController : YZDisplayViewController
{
    KSYD_RankingModel *_rankingM;
}

- (void).cxx_destruct;
@property(retain, nonatomic) KSYD_RankingModel *rankingM; // @synthesize rankingM=_rankingM;
- (void)setUpAllViewController;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

