//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_BaseTableViewController.h"

#import "KSYD_ErrorStatusViewDelegate-Protocol.h"

@class KSYD_ErrorStatusView, NSMutableArray, NSString;

@interface KSYD_BookListViewController : KSYD_BaseTableViewController <KSYD_ErrorStatusViewDelegate>
{
    _Bool _isBookStoreThemeList;
    _Bool _isInTab;
    NSString *_sexName;
    NSString *_listTitle;
    long long _firstPageId;
    long long _secondPageId;
    NSMutableArray *_themesArr;
    KSYD_ErrorStatusView *_errorView;
}

- (void).cxx_destruct;
- (void)KSYD_buildUI;
- (void)KSYD_getData;
- (void)KSYD_resetBaseViewH:(double)arg1;
- (void)KSYD_setUpLFRefresh;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
@property(retain, nonatomic) KSYD_ErrorStatusView *errorView; // @synthesize errorView=_errorView;
@property(nonatomic) long long firstPageId; // @synthesize firstPageId=_firstPageId;
- (void)getBookStoreThemeMoreList;
@property(nonatomic) _Bool isBookStoreThemeList; // @synthesize isBookStoreThemeList=_isBookStoreThemeList;
@property(nonatomic) _Bool isInTab; // @synthesize isInTab=_isInTab;
@property(copy, nonatomic) NSString *listTitle; // @synthesize listTitle=_listTitle;
- (void)loadMoreLFData;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)refreshDataWithType:(id)arg1;
@property(nonatomic) long long secondPageId; // @synthesize secondPageId=_secondPageId;
@property(copy, nonatomic) NSString *sexName; // @synthesize sexName=_sexName;
@property(retain, nonatomic) NSMutableArray *themesArr; // @synthesize themesArr=_themesArr;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

