//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_BaseViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class KSYD_BookListsDataModel, KSYD_BookStoreBookListsData, KSYD_NetworkManager, KSYD_Themes, NSMutableArray, NSString, NSTimer, UIButton, UILabel, UITableView, UIView;

@interface KSYD_ThemeBookListController : KSYD_BaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    KSYD_BookStoreBookListsData *_listData;
    KSYD_Themes *_theme;
    long long _index;
    KSYD_BookListsDataModel *_dataModel;
    CDUnknownBlockType _collectBlock;
    UIButton *_rightButton;
    KSYD_NetworkManager *_netManager;
    NSMutableArray *_themes;
    KSYD_Themes *_themeList;
    UITableView *_tableView;
    NSMutableArray *_adsArr;
    NSTimer *_wanTimer;
    long long _wanIndex;
    UIView *_topView;
    UILabel *_topTitle;
    UIButton *_topBtn;
    UIButton *_backBtn;
}

- (void).cxx_destruct;
- (void)KSYD_addWanTimer;
- (void)KSYD_changeThemeFavStatus:(id)arg1;
- (void)KSYD_checkIsFav;
- (id)KSYD_getHeaderView;
- (void)KSYD_loadNewLFData;
- (void)KSYD_reloadWanRow;
- (void)KSYD_setUpLFNav;
- (void)KSYD_setupLFUI;
- (void)KSYD_showWanYiWan;
@property(retain, nonatomic) NSMutableArray *adsArr; // @synthesize adsArr=_adsArr;
@property(nonatomic) __weak UIButton *backBtn; // @synthesize backBtn=_backBtn;
- (void)cancel;
- (void)clickBack;
@property(copy, nonatomic) CDUnknownBlockType collectBlock; // @synthesize collectBlock=_collectBlock;
@property(retain, nonatomic) KSYD_BookListsDataModel *dataModel; // @synthesize dataModel=_dataModel;
- (void)dealloc;
- (void)downloadImage;
- (float)heightForString:(id)arg1 fontSize:(float)arg2 andWidth:(float)arg3;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) KSYD_BookStoreBookListsData *listData; // @synthesize listData=_listData;
@property(retain, nonatomic) KSYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
- (void)scrollViewDidScroll:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) KSYD_Themes *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) KSYD_Themes *themeList; // @synthesize themeList=_themeList;
@property(retain, nonatomic) NSMutableArray *themes; // @synthesize themes=_themes;
@property(nonatomic) __weak UIButton *topBtn; // @synthesize topBtn=_topBtn;
@property(nonatomic) __weak UILabel *topTitle; // @synthesize topTitle=_topTitle;
@property(nonatomic) __weak UIView *topView; // @synthesize topView=_topView;
@property(nonatomic) long long wanIndex; // @synthesize wanIndex=_wanIndex;
@property(retain, nonatomic) NSTimer *wanTimer; // @synthesize wanTimer=_wanTimer;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

