//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class KSYD_NetworkManager, NSMutableArray, NSString, YBookDetailModel, YDownloadModel;
@protocol OS_dispatch_semaphore;

@interface KSYD_DownloadManager : NSObject
{
    NSObject<OS_dispatch_semaphore> *_lock;
    YDownloadModel *_downloadReading;
    YBookDetailModel *_downloadBook;
    NSMutableArray *_downloadBooksArr;
    KSYD_NetworkManager *_netManager;
    NSMutableArray *_taskArray;
    NSString *_summary_id;
}

+ (id)shareManager;
- (void).cxx_destruct;
- (void)KSYD_cancelDownloadBookWith:(id)arg1;
- (void)KSYD_downloadReaderBookWith:(id)arg1 type:(long long)arg2;
- (void)addDownloadTaskWith:(id)arg1;
@property(retain, nonatomic) YBookDetailModel *downloadBook; // @synthesize downloadBook=_downloadBook;
@property(retain, nonatomic) NSMutableArray *downloadBooksArr; // @synthesize downloadBooksArr=_downloadBooksArr;
- (void)downloadChapterWith:(id)arg1;
- (void)downloadNextChapterWith:(id)arg1;
@property(retain, nonatomic) YDownloadModel *downloadReading; // @synthesize downloadReading=_downloadReading;
- (void)finishTaskWith:(id)arg1;
- (id)init;
@property(retain, nonatomic) KSYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (void)removeDownloadTaskWith:(id)arg1;
@property(retain, nonatomic) NSString *summary_id; // @synthesize summary_id=_summary_id;
@property(retain, nonatomic) NSMutableArray *taskArray; // @synthesize taskArray=_taskArray;
- (void)startNextTask;

@end

