//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KSYD_ComicBookSelfTool : NSObject
{
}

+ (void)KSYD_AddBook:(id)arg1;
+ (void)KSYD_DelBook:(id)arg1;
+ (void)KSYD_getComicStatusWithBookIDArr:(id)arg1 success:(CDUnknownBlockType)arg2;

@end

