//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface KSYD_ComicReadTipsView : UIView
{
    _Bool _isBook;
}

- (id)KSYD_buildLabelWithText:(id)arg1 frame:(struct CGRect)arg2 view:(id)arg3;
- (void)KSYD_setupBookUI;
- (void)KSYD_setupUI;
- (void)clcikDisMiss;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isBook; // @synthesize isBook=_isBook;
- (void)show;

@end

