//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, YYCache;

@interface KSYD_LikeSQliteManger : NSObject
{
    NSString *_documentFolder;
    NSArray *_commentLikeArr;
    NSArray *_replyLikeArr;
    YYCache *_cache;
}

+ (id)shareManager;
- (void).cxx_destruct;
- (_Bool)KSYD_IsClikeCommentLike:(id)arg1;
- (_Bool)KSYD_IsClikeReplyLike:(id)arg1;
- (void)KSYD_addCommentLikeWith:(id)arg1;
- (void)KSYD_addReplyLikeWith:(id)arg1;
- (void)KSYD_getCommentArr;
- (void)KSYD_getRelpyArr;
- (void)KSYD_updateCommentLikeStatus;
- (void)KSYD_updateRelpyLikeStatus;
@property(retain, nonatomic) YYCache *cache; // @synthesize cache=_cache;
@property(copy, nonatomic) NSArray *commentLikeArr; // @synthesize commentLikeArr=_commentLikeArr;
@property(retain, nonatomic) NSString *documentFolder; // @synthesize documentFolder=_documentFolder;
- (id)getBackupLike:(id)arg1;
- (id)init;
@property(copy, nonatomic) NSArray *replyLikeArr; // @synthesize replyLikeArr=_replyLikeArr;
- (void)saveBackupLike:(id)arg1 key:(id)arg2;

@end

