//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

#import "AvoidCrashProtocol-Protocol.h"

@class NSString;

@interface NSDictionary (KSYD_Extension) <AvoidCrashProtocol>
+ (id)apm_dictionaryWithHttpArgumentsString:(id)arg1;
+ (id)avoidCrashDictionaryWithObjects:(const id *)arg1 forKeys:(const id *)arg2 count:(unsigned long long)arg3;
+ (void)avoidCrashExchangeMethod;
+ (id)bu_dictionaryWithJSONData:(id)arg1 error:(id *)arg2;
+ (id)bu_dictionaryWithJSONString:(id)arg1 error:(id *)arg2;
+ (id)gdt_safeDictionaryWithObject:(id)arg1 forKey:(id)arg2;
+ (id)hmdbu_dictionaryWithObject:(id)arg1 forKey:(id)arg2;
- (id)apm_queryString;
- (id)bu_JSONRepresentation:(id *)arg1;
- (id)bu_arrayForKey:(id)arg1 defaultValue:(id)arg2;
- (_Bool)bu_boolForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (id)bu_dictionaryForKey:(id)arg1 defaultValue:(id)arg2;
- (float)bu_floatForKey:(id)arg1 defaultValue:(float)arg2;
- (long long)bu_integerForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)bu_longForKey:(id)arg1 defaultValue:(long long)arg2;
- (long long)bu_longLongForKey:(id)arg1 defaultValue:(long long)arg2;
- (void)bu_parserWithKey:(id)arg1 stringValue:(id *)arg2 dictValue:(id *)arg3 aryValue:(id *)arg4;
- (id)bu_stringForKey:(id)arg1 defaultValue:(id)arg2;
- (double)bu_timeIntervalForKey:(id)arg1 defaultValue:(double)arg2;
- (id)embed_arrayValueForKey:(id)arg1;
- (_Bool)embed_boolValueForKey:(id)arg1;
- (id)embed_dictionaryValueForKey:(id)arg1;
- (double)embed_doubleValueForKey:(id)arg1;
- (long long)embed_integerValueForKey:(id)arg1;
- (long long)embed_longlongValueForKey:(id)arg1;
- (id)embed_stringValueForKey:(id)arg1;
- (unsigned long long)embed_unsignedIntegerValueForKey:(id)arg1;
@property(nonatomic) _Bool gurd_forceRequest;
- (id)hmdbu_arrayForKey:(id)arg1;
- (_Bool)hmdbu_boolForKey:(id)arg1;
- (id)hmdbu_dictForKey:(id)arg1;
- (double)hmdbu_doubleForKey:(id)arg1;
- (float)hmdbu_floatForKey:(id)arg1;
- (_Bool)hmdbu_hasKey:(id)arg1;
- (int)hmdbu_intForKey:(id)arg1;
- (long long)hmdbu_integerForKey:(id)arg1;
- (_Bool)hmdbu_isValidJSONObject;
- (id)hmdbu_jsonData;
- (id)hmdbu_jsonData:(id *)arg1;
- (id)hmdbu_jsonString;
- (id)hmdbu_jsonString:(id *)arg1;
- (long long)hmdbu_longForKey:(id)arg1;
- (long long)hmdbu_longLongForKey:(id)arg1;
- (id)hmdbu_objectForKey:(id)arg1 class:(Class)arg2;
- (id)hmdbu_queryString;
- (id)hmdbu_safeObjectForKey:(id)arg1;
- (id)hmdbu_stringForKey:(id)arg1;
- (unsigned int)hmdbu_unsignedIntForKey:(id)arg1;
- (unsigned long long)hmdbu_unsignedIntegerForKey:(id)arg1;
- (unsigned long long)hmdbu_unsignedLongForKey:(id)arg1;
- (unsigned long long)hmdbu_unsignedLongLongForKey:(id)arg1;
- (id)toJsonData;
- (id)toJsonString;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

