//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSTimer.h>

@interface NSTimer (TXTimerTarget)
+ (void)bu_blockInvoke:(id)arg1;
+ (id)bu_scheduledTimerWithTimeInterval:(double)arg1 repeats:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
+ (void)startTimer:(id)arg1;
+ (id)tx_scheduledTimerWithTimeInterval:(double)arg1 repeat:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
- (void)GDTfunctionb7lr1f:(double)arg1;
- (void)GDTfunctione6GH4L;
- (void)GDTfunctionr41b1B;
@property(nonatomic) double GDTfunctionr6O1Yp;
@end

