//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString, TSFingerPrintContextUNBC, rn_3DGOSeTSEzfGbUNBC, rn_3DJhQnbeTPUTzQOUDNkWehUNBC, rn_3DKfQWdQDzlFZUNBC;
@protocol TSFinalTrackedItem;

@interface rn_3DISSikPUNBC : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _reported;
    long long _scene;
    long long _action;
    double _timestamp;
    rn_3DKfQWdQDzlFZUNBC<TSFinalTrackedItem> *_item;
    NSMutableDictionary *_externals;
    rn_3DJhQnbeTPUTzQOUDNkWehUNBC *_reportingStatistics;
    rn_3DJhQnbeTPUTzQOUDNkWehUNBC *_collectingStatistics;
    rn_3DGOSeTSEzfGbUNBC *_packageInfo;
    NSString *_storageUUID;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(nonatomic) long long action; // @synthesize action=_action;
@property(nonatomic) __weak rn_3DJhQnbeTPUTzQOUDNkWehUNBC *collectingStatistics; // @synthesize collectingStatistics=_collectingStatistics;
@property(retain, nonatomic) TSFingerPrintContextUNBC *context;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *externals; // @synthesize externals=_externals;
@property(retain, nonatomic) NSDictionary *features;
@property(retain, nonatomic) NSString *fingerprintTicketID;
- (id)initWithCoder:(id)arg1;
- (id)initWithTrackedItem:(id)arg1 scene:(long long)arg2 action:(long long)arg3 timestamp:(double)arg4;
@property(nonatomic) unsigned long long interfaceType;
@property(retain, nonatomic) rn_3DKfQWdQDzlFZUNBC<TSFinalTrackedItem> *item; // @synthesize item=_item;
@property(retain, nonatomic) rn_3DGOSeTSEzfGbUNBC *packageInfo; // @synthesize packageInfo=_packageInfo;
@property(nonatomic) _Bool reported; // @synthesize reported=_reported;
@property(nonatomic) __weak rn_3DJhQnbeTPUTzQOUDNkWehUNBC *reportingStatistics; // @synthesize reportingStatistics=_reportingStatistics;
@property(nonatomic) unsigned long long requireType;
@property(nonatomic) long long scene; // @synthesize scene=_scene;
@property(retain, nonatomic) NSString *storageUUID; // @synthesize storageUUID=_storageUUID;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSString *userIdentifier;

@end

