//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "rn_3DKfQWdQDzlFZUNBC.h"

#import "TSFinalTrackedItem-Protocol.h"

@interface rn_3D6afnr5TLeUNBC : rn_3DKfQWdQDzlFZUNBC <TSFinalTrackedItem>
{
    double _timestamp;
    double _duration;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)resampleForTouchesLimit:(unsigned long long)arg1 exclusiveHandler:(CDUnknownBlockType)arg2;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;

@end

