//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "rn_3DGOSeXf2LiVRUWUNBC.h"

@interface rn_3DGOSeXf3OSSX4HZTPjhUNBC : rn_3DGOSeXf2LiVRUWUNBC
{
    long long _commandID;
}

@property(nonatomic) long long commandID; // @synthesize commandID=_commandID;
- (id)initWithRequestData:(id)arg1 forCommandID:(long long)arg2;

@end

