//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface rn_3DGOSeTSEzfGbUNBC : NSObject <NSSecureCoding, NSCopying>
{
    NSString *_versionName;
    double _timestampOfInstall;
    double _timestampOfUpdate;
    NSString *_hashCodeOfBinary;
    unsigned long long _execuableSize;
    double _timestampOfModification;
    NSString *_storeKey;
}

+ (id)checkoutRecordForKey:(id)arg1 shouldResetInstallTimestamp:(_Bool)arg2;
+ (id)lastRecordForKey:(id)arg1;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) unsigned long long execuableSize; // @synthesize execuableSize=_execuableSize;
@property(retain, nonatomic) NSString *hashCodeOfBinary; // @synthesize hashCodeOfBinary=_hashCodeOfBinary;
- (id)initWithCoder:(id)arg1;
- (id)initWithKey:(id)arg1;
- (void)markUploaded;
@property(copy, nonatomic) NSString *storeKey; // @synthesize storeKey=_storeKey;
@property(nonatomic) double timestampOfInstall; // @synthesize timestampOfInstall=_timestampOfInstall;
@property(nonatomic) double timestampOfModification; // @synthesize timestampOfModification=_timestampOfModification;
@property(nonatomic) double timestampOfUpdate; // @synthesize timestampOfUpdate=_timestampOfUpdate;
@property(retain, nonatomic) NSString *versionName; // @synthesize versionName=_versionName;
@property(readonly, nonatomic) unsigned long long versionCode;

@end

