//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SKOverlay, SKOverlayTransitionContext;

@protocol SKOverlayDelegate <NSObject>

@optional
- (void)storeOverlay:(SKOverlay *)arg1 didFailToLoadWithError:(NSError *)arg2;
- (void)storeOverlay:(SKOverlay *)arg1 didFinishDismissal:(SKOverlayTransitionContext *)arg2;
- (void)storeOverlay:(SKOverlay *)arg1 didFinishPresentation:(SKOverlayTransitionContext *)arg2;
- (void)storeOverlay:(SKOverlay *)arg1 willStartDismissal:(SKOverlayTransitionContext *)arg2;
- (void)storeOverlay:(SKOverlay *)arg1 willStartPresentation:(SKOverlayTransitionContext *)arg2;
@end

