//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TAAbstractDotView.h"

@class UIColor;

@interface TAAnimatedDotView : TAAbstractDotView
{
    UIColor *_dotColor;
}

- (void).cxx_destruct;
- (void)animateToActiveState;
- (void)animateToDeactiveState;
- (void)changeActivityState:(_Bool)arg1;
@property(retain, nonatomic) UIColor *dotColor; // @synthesize dotColor=_dotColor;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initialization;

@end

