//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary;

@interface TSFingerprintConfigUNBC : NSObject
{
    struct TFC_FeatureConfigItem *_configItem;
}

+ (id)configWithJceItem:(struct TFC_FeatureConfigItem *)arg1;
+ (id)configWithOps:(id)arg1 customOps:(id)arg2 lifeTime:(double)arg3;
@property(readonly, copy, nonatomic) NSData *configData;
- (id)configDataWithResult:(int *)arg1;
@property(nonatomic) struct TFC_FeatureConfigItem *configItem; // @synthesize configItem=_configItem;
- (void)dealloc;
- (int)dumpToStruct:(struct TFC_FeatureConfigItem *)arg1;
@property(readonly, copy, nonatomic, getter=getCustomOps) NSDictionary *customOps;
@property(readonly, nonatomic, getter=getLifeTime) long long lifeTime;
@property(readonly, copy, nonatomic, getter=getOps) NSDictionary *ops;
@property(readonly, copy, nonatomic, getter=getPath) NSDictionary *path;
@property(readonly, nonatomic, getter=getSequence) long long sequence;
@property(readonly, nonatomic, getter=getVersion) long long version;
- (id)initWithData:(id)arg1;

@end

