//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TuringIDUNBC;

@interface TuringIDServiceUNBC : NSObject
{
}

+ (id)featureDelegate;
+ (id)information;
+ (void)setFeatureDelegate:(id)arg1;
+ (void)setUsesDebugServer:(_Bool)arg1;
+ (id)sharedService;
+ (_Bool)usesDebugServer;
@property(readonly, copy, nonatomic) TuringIDUNBC *cachedTuringID;
- (id)fetchTuringIDSynchronically;
- (void)fetchTuringIDWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initService;
- (void)startService;
- (void)startServiceWithUserID:(id)arg1;
- (void)stopService;

@end

