//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSError, NSMutableDictionary;

@interface TuringAnalysisPredictionUNBC : NSObject <NSCopying>
{
    _Bool _advice;
    float _posibility;
    NSError *_error;
    NSMutableDictionary *_externals;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool advice; // @synthesize advice=_advice;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSMutableDictionary *externals; // @synthesize externals=_externals;
- (id)initWithAdvice:(_Bool)arg1 posibility:(float)arg2;
- (id)initWithError:(id)arg1;
@property(nonatomic) float posibility; // @synthesize posibility=_posibility;

@end

