//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TuringPostRuleUNBC.h"

@interface TuringAutoPostRuleUNBC : TuringPostRuleUNBC
{
    _Bool _postsThroughWiFiOnly;
    _Bool _cachesRecordInCaseOfReachedMaximumPostsLimitation;
    _Bool _cachesRecordInCaseOfFailedPosting;
    _Bool _alsoPostsCachedRecordsIfPossible;
    unsigned long long _maximumPostsThroughCellulerPerDay;
    unsigned long long _maximumPostsThroughCellulerPerHour;
}

+ (id)autoPostRule;
- (_Bool)allowsPostingThroughCellulerForScene:(unsigned long long)arg1;
@property(nonatomic) _Bool alsoPostsCachedRecordsIfPossible; // @synthesize alsoPostsCachedRecordsIfPossible=_alsoPostsCachedRecordsIfPossible;
@property(nonatomic) _Bool cachesRecordInCaseOfFailedPosting; // @synthesize cachesRecordInCaseOfFailedPosting=_cachesRecordInCaseOfFailedPosting;
@property(nonatomic) _Bool cachesRecordInCaseOfReachedMaximumPostsLimitation; // @synthesize cachesRecordInCaseOfReachedMaximumPostsLimitation=_cachesRecordInCaseOfReachedMaximumPostsLimitation;
- (id)initForAutoPosting:(_Bool)arg1;
- (void)markPostingIfNeededForScene:(unsigned long long)arg1;
- (void)markPostingThroughCellulerForScene:(unsigned long long)arg1;
- (_Bool)matchesPostingNetworkConditionForScene:(unsigned long long)arg1;
@property(nonatomic) unsigned long long maximumPostsThroughCellulerPerDay; // @synthesize maximumPostsThroughCellulerPerDay=_maximumPostsThroughCellulerPerDay;
@property(nonatomic) unsigned long long maximumPostsThroughCellulerPerHour; // @synthesize maximumPostsThroughCellulerPerHour=_maximumPostsThroughCellulerPerHour;
@property(nonatomic) _Bool postsThroughWiFiOnly; // @synthesize postsThroughWiFiOnly=_postsThroughWiFiOnly;

@end

