//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

#import "BarrageViewProtocol-Protocol.h"

@class NSString, UIColor, UIFont;

@interface UILabel (Chameleon) <BarrageViewProtocol>
+ (id)bottomADLabel;
+ (id)labelWithTitle:(id)arg1 backgroundColor:(id)arg2 tinColor:(id)arg3 font:(long long)arg4 view:(id)arg5;
+ (id)setLineLabel:(id)arg1 frame:(struct CGRect)arg2 view:(id)arg3;
@property(nonatomic) double characterSpace;
- (void)configureWithParams:(id)arg1;
- (struct CGSize)getLableSizeWithMaxWidth:(double)arg1;
@property(copy, nonatomic) NSString *keywords;
@property(retain, nonatomic) UIColor *keywordsColor;
@property(retain, nonatomic) UIFont *keywordsFont;
@property(nonatomic) double lineSpace;
- (void)prepareForReuse;
- (void)setLabelAttributedText:(id)arg1 LineSpacing:(double)arg2;
- (void)setLabelAttributedText:(id)arg1 LineSpacing:(double)arg2 lineBreak:(long long)arg3;
- (id)setLabelWith:(id)arg1 color:(id)arg2 font:(id)arg3 aliment:(long long)arg4;
- (void)setSubstituteFontName:(id)arg1;
@property(retain, nonatomic) UIColor *underlineColor;
@property(copy, nonatomic) NSString *underlineStr;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

