//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarItem.h>

#import "WZLBadgeProtocol-Protocol.h"

@class NSString, UIColor, UIFont, UILabel;

@interface UITabBarItem (Badge) <WZLBadgeProtocol>
@property(nonatomic) unsigned long long aniType;
@property(retain, nonatomic) UILabel *badge;
@property(retain, nonatomic) UIColor *badgeBgColor;
@property(nonatomic) struct CGPoint badgeCenterOffset;
@property(retain, nonatomic) UIFont *badgeFont;
@property(nonatomic) struct CGRect badgeFrame;
@property(nonatomic) long long badgeMaximumBadgeNumber;
@property(retain, nonatomic) UIColor *badgeTextColor;
- (void)clearBadge;
- (id)find:(id)arg1 firstSubviewWithClass:(Class)arg2;
- (id)findSwappableImageViewByInView:(id)arg1;
- (id)getActualBadgeSuperView;
- (void)removeBadgeView;
- (void)resumeBadge;
- (void)showBadge;
- (void)showBadgeWithStyle:(unsigned long long)arg1 value:(long long)arg2 animationType:(unsigned long long)arg3;
- (id)yee_BadgeLable;
- (void)yee_MakeBadgeTextNum:(long long)arg1 textColor:(id)arg2 backColor:(id)arg3 Font:(id)arg4;
- (void)yee_MakeRedBadge:(double)arg1 color:(id)arg2;

// Remaining properties
@property(nonatomic) double badgeRadius;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

