//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSYD_BaseModel.h"

@class NSArray, NSNumber, NSString;

@interface YBaseModel : KSYD_BaseModel
{
    _Bool _collapse;
    int _wordCount;
    NSString *_bookidentifire;
    long long _bookupdatetime;
    NSString *_updated;
    double _bookrecentlytime;
    NSString *_image;
    NSString *_lastChapter;
    NSString *_shortIntro;
    NSString *_author;
    NSString *_title;
    NSString *_status;
    NSString *_type;
    NSString *_ltype;
    NSString *_stype;
    long long _comment_num;
    NSString *_total_count;
    NSString *_reading_site_path_reload;
    NSString *_lists_id;
    NSString *_ltype_id;
    NSString *_ltype_name;
    NSString *_ltype_image;
    NSArray *_ltype_list;
    NSString *_source;
    NSString *_body;
    NSString *_link;
    NSNumber *_is_liked;
    long long _likes_count;
    NSString *_book_count;
    NSString *_site_name;
    NSString *_sex;
    double _score;
    long long _form;
}

+ (id)modelCustomPropertyMapper;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *book_count; // @synthesize book_count=_book_count;
@property(nonatomic) NSString *bookidentifire; // @synthesize bookidentifire=_bookidentifire;
@property(nonatomic) double bookrecentlytime; // @synthesize bookrecentlytime=_bookrecentlytime;
@property(nonatomic) long long bookupdatetime; // @synthesize bookupdatetime=_bookupdatetime;
@property(nonatomic) _Bool collapse; // @synthesize collapse=_collapse;
@property(nonatomic) long long comment_num; // @synthesize comment_num=_comment_num;
@property(nonatomic) long long form; // @synthesize form=_form;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(nonatomic) NSNumber *is_liked; // @synthesize is_liked=_is_liked;
@property(retain, nonatomic) NSString *lastChapter; // @synthesize lastChapter=_lastChapter;
@property(nonatomic) long long likes_count; // @synthesize likes_count=_likes_count;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
@property(retain, nonatomic) NSString *lists_id; // @synthesize lists_id=_lists_id;
@property(retain, nonatomic) NSString *ltype; // @synthesize ltype=_ltype;
@property(copy, nonatomic) NSString *ltype_id; // @synthesize ltype_id=_ltype_id;
@property(copy, nonatomic) NSString *ltype_image; // @synthesize ltype_image=_ltype_image;
@property(copy, nonatomic) NSArray *ltype_list; // @synthesize ltype_list=_ltype_list;
@property(copy, nonatomic) NSString *ltype_name; // @synthesize ltype_name=_ltype_name;
@property(copy, nonatomic) NSString *reading_site_path_reload; // @synthesize reading_site_path_reload=_reading_site_path_reload;
@property(nonatomic) double score; // @synthesize score=_score;
@property(copy, nonatomic) NSString *sex; // @synthesize sex=_sex;
@property(retain, nonatomic) NSString *shortIntro; // @synthesize shortIntro=_shortIntro;
@property(copy, nonatomic) NSString *site_name; // @synthesize site_name=_site_name;
@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *stype; // @synthesize stype=_stype;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *total_count; // @synthesize total_count=_total_count;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *updated; // @synthesize updated=_updated;
@property(nonatomic) int wordCount; // @synthesize wordCount=_wordCount;

@end

