//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YBaseModel.h"

@class NSArray, NSString, YDownloadModel;

@interface YBookDetailModel : YBaseModel
{
    _Bool _bookshlefexist;
    _Bool _ReadingHistoryExist;
    _Bool _hasSticky;
    _Bool _hasUpdated;
    _Bool _closeUpdated;
    _Bool _hasLoadCompletion;
    NSArray *_related_data;
    unsigned long long _readingChapter;
    unsigned long long _readingPage;
    double _readingLocation;
    NSString *_readingChapterTitle;
    long long _ReadingHistoryTime;
    NSString *_is_top;
    long long _chaptersCount;
    NSArray *_author_book;
    NSArray *_relevant_book;
    NSArray *_sites;
    NSArray *_shield_data;
    long long _score_number;
    long long _view_count;
    long long _words_number;
    long long _source_count;
    long long _selectSummaryChapterCount;
    long long _selectSummaryReadingChapter;
    NSString *_lastReadingChapter;
    long long _is_fatten;
    long long _fatten_word_number;
    NSString *_reading_datetime;
    NSString *_reading_site_id;
    NSString *_reading_site_path;
    NSString *_reading_chapter_key;
    YDownloadModel *_downloadM;
    long long _loadStatus;
    CDUnknownBlockType _loadProgress;
    CDUnknownBlockType _loadCompletion;
    CDUnknownBlockType _loadFailure;
    CDUnknownBlockType _loadCancel;
}

+ (const struct WCTPropertyList *)AllProperties;
+ (const struct WCTAnyProperty *)AnyProperty;
+ (CDUnknownBlockType)PropertyNamed;
+ (const struct WCTProperty *)ReadingHistoryExist;
+ (const struct WCTProperty *)ReadingHistoryTime;
+ (const struct WCTProperty *)author;
+ (const struct WCTProperty *)author_book;
+ (const struct WCTProperty *)bookidentifire;
+ (const struct WCTProperty *)bookrecentlytime;
+ (const struct WCTProperty *)bookshlefexist;
+ (const struct WCTProperty *)bookupdatetime;
+ (const struct WCTProperty *)chaptersCount;
+ (const struct WCTProperty *)closeUpdated;
+ (const struct WCTProperty *)comment_num;
+ (const struct WCTProperty *)fatten_word_number;
+ (const struct WCTProperty *)hasSticky;
+ (const struct WCTProperty *)hasUpdated;
+ (const struct WCTProperty *)image;
+ (const struct WCTProperty *)is_fatten;
+ (const struct WCTProperty *)is_top;
+ (const struct WCTProperty *)lastChapter;
+ (const struct WCTProperty *)lastReadingChapter;
+ (const struct WCTProperty *)ltype;
+ (id)modelContainerPropertyGenericClass;
+ (id)modelPropertyBlacklist;
+ (id)modelPropertyWhitelist;
+ (const struct WCTBinding *)objectRelationalMappingForWCDB;
+ (const struct WCTProperty *)readingChapter;
+ (const struct WCTProperty *)readingChapterTitle;
+ (const struct WCTProperty *)readingLocation;
+ (const struct WCTProperty *)readingPage;
+ (const struct WCTProperty *)reading_chapter_key;
+ (const struct WCTProperty *)reading_datetime;
+ (const struct WCTProperty *)reading_site_id;
+ (const struct WCTProperty *)reading_site_path;
+ (const struct WCTProperty *)reading_site_path_reload;
+ (const struct WCTProperty *)relevant_book;
+ (const struct WCTProperty *)score;
+ (const struct WCTProperty *)score_number;
+ (const struct WCTProperty *)selectSummaryChapterCount;
+ (const struct WCTProperty *)selectSummaryReadingChapter;
+ (const struct WCTProperty *)shield_data;
+ (const struct WCTProperty *)shortIntro;
+ (const struct WCTProperty *)sites;
+ (const struct WCTProperty *)source_count;
+ (const struct WCTProperty *)status;
+ (const struct WCTProperty *)stype;
+ (const struct WCTProperty *)title;
+ (const struct WCTProperty *)total_count;
+ (const struct WCTProperty *)type;
+ (const struct WCTProperty *)updated;
+ (const struct WCTProperty *)view_count;
+ (const struct WCTProperty *)wordCount;
+ (const struct WCTProperty *)words_number;
- (void).cxx_destruct;
@property(nonatomic) _Bool ReadingHistoryExist; // @synthesize ReadingHistoryExist=_ReadingHistoryExist;
@property(nonatomic) long long ReadingHistoryTime; // @synthesize ReadingHistoryTime=_ReadingHistoryTime;
@property(retain, nonatomic) NSArray *author_book; // @synthesize author_book=_author_book;
@property(nonatomic) _Bool bookshlefexist; // @synthesize bookshlefexist=_bookshlefexist;
@property(nonatomic) long long chaptersCount; // @synthesize chaptersCount=_chaptersCount;
@property(nonatomic) _Bool closeUpdated; // @synthesize closeUpdated=_closeUpdated;
@property(nonatomic) __weak YDownloadModel *downloadM; // @synthesize downloadM=_downloadM;
@property(nonatomic) long long fatten_word_number; // @synthesize fatten_word_number=_fatten_word_number;
- (id)getBookWordCount;
@property(nonatomic) _Bool hasLoadCompletion; // @synthesize hasLoadCompletion=_hasLoadCompletion;
@property(nonatomic) _Bool hasSticky; // @synthesize hasSticky=_hasSticky;
@property(nonatomic) _Bool hasUpdated; // @synthesize hasUpdated=_hasUpdated;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) long long is_fatten; // @synthesize is_fatten=_is_fatten;
@property(retain, nonatomic) NSString *is_top; // @synthesize is_top=_is_top;
@property(copy, nonatomic) NSString *lastReadingChapter; // @synthesize lastReadingChapter=_lastReadingChapter;
@property(copy, nonatomic) CDUnknownBlockType loadCancel; // @synthesize loadCancel=_loadCancel;
@property(copy, nonatomic) CDUnknownBlockType loadCompletion; // @synthesize loadCompletion=_loadCompletion;
@property(copy, nonatomic) CDUnknownBlockType loadFailure; // @synthesize loadFailure=_loadFailure;
@property(copy, nonatomic) CDUnknownBlockType loadProgress; // @synthesize loadProgress=_loadProgress;
@property long long loadStatus; // @synthesize loadStatus=_loadStatus;
@property(nonatomic) unsigned long long readingChapter; // @synthesize readingChapter=_readingChapter;
@property(copy, nonatomic) NSString *readingChapterTitle; // @synthesize readingChapterTitle=_readingChapterTitle;
@property(nonatomic) double readingLocation; // @synthesize readingLocation=_readingLocation;
@property(nonatomic) unsigned long long readingPage; // @synthesize readingPage=_readingPage;
@property(copy, nonatomic) NSString *reading_chapter_key; // @synthesize reading_chapter_key=_reading_chapter_key;
@property(copy, nonatomic) NSString *reading_datetime; // @synthesize reading_datetime=_reading_datetime;
@property(copy, nonatomic) NSString *reading_site_id; // @synthesize reading_site_id=_reading_site_id;
@property(copy, nonatomic) NSString *reading_site_path; // @synthesize reading_site_path=_reading_site_path;
@property(retain, nonatomic) NSArray *related_data; // @synthesize related_data=_related_data;
@property(retain, nonatomic) NSArray *relevant_book; // @synthesize relevant_book=_relevant_book;
@property(nonatomic) long long score_number; // @synthesize score_number=_score_number;
@property(nonatomic) long long selectSummaryChapterCount; // @synthesize selectSummaryChapterCount=_selectSummaryChapterCount;
@property(nonatomic) long long selectSummaryReadingChapter; // @synthesize selectSummaryReadingChapter=_selectSummaryReadingChapter;
@property(copy, nonatomic) NSArray *shield_data; // @synthesize shield_data=_shield_data;
@property(retain, nonatomic) NSArray *sites; // @synthesize sites=_sites;
@property(nonatomic) long long source_count; // @synthesize source_count=_source_count;
@property(nonatomic) long long view_count; // @synthesize view_count=_view_count;
@property(nonatomic) long long words_number; // @synthesize words_number=_words_number;

@end

